### ISSUE TITLE
1.6.0版本在Root模式下无法查看任何目录

### ISSUE THREAD

**Issue by LindaFelicia** [zhanghai/MaterialFiles#1003]
Magisk版本26.1
质感文件版本1.6.0
仅Root模式下无法查看任何目录，自动模式下无法查看需要root才能查看的目录（例如Android/Data）
回退至1.5.2后可正常查看
已在Magisk确认赋予了root权限
![Screenshot_20230829-235113](https://github.com/zhanghai/MaterialFiles/assets/50535893/cb1f089b-6bfc-4305-99f2-a063e81b22d1)
![Screenshot_20230829-235715_1](https://github.com/zhanghai/MaterialFiles/assets/50535893/e8988af9-2941-4252-b98d-8a9c83558538)

**Comment by LindaFelicia** [comment]
![Screenshot_20230830-000858](https://github.com/zhanghai/MaterialFiles/assets/50535893/c501b546-d028-434f-88c5-2cf6b908f0c7)

**Comment by zhanghai** [comment]
感谢信息。这意味着 Material Files 使用 libsu 的 root 进程没能正确启动，需要看 logcat 才能得知具体原因。

请问你有 adb 或者其他形式的 logcat 访问吗？可以提供一下含有`.files`字样的
前后的 log 的话，可能可以更快地定位到具体原因。

**Comment by LindaFelicia** [comment]
[230830_2221.txt](https://github.com/zhanghai/MaterialFiles/files/12479520/230830_2221.txt)

**Comment by zhanghai** [comment]
```
08-30 22:22:06.136 I/me.zhanghai.android.files:root:0( 8783): System.exit called, status: 0
08-30 22:22:06.136 I/AndroidRuntime( 8783): VM exiting with result code 0.
```

log 说是主动调用 `System.exit(0)` 退出的，但我的代码并不会主动这样……可能还是要我尝试本地重现了

**Comment by zhanghai** [comment]
周末有时间了，使用 https://github.com/shakalaca/MagiskOnEmulator 创建了一个 Android 11 的带 Magisk 的模拟器，并安装了 GitHub Releases 上的 APK，但是未能复现这个问题——Root 访问一切正常……所以可能还是要从你那边来调试了。

1.  我在 master 分支上打开了 libsu 的 verbose logging，请问你可以下载一下 [这里](https://github.com/zhanghai/MaterialFiles/actions/runs/6061111519) 的 APK 然后再提供一次日志吗？

    如果希望减少上传的日志量来保护隐私，可以使用 `adb logcat -c` 清除之前的日志，然后打开 Material Files 尝试使用 root，然后再将这时的 `adb logcat >log.txt` 输出上传。

2.  1.6.0 中与 root 相关的变更主要是升级了 libsu 的版本，从 `com.github.topjohnwu.libsu:service:5.0.1` 升级到了 `com.github.topjohnwu.libsu:service:5.2.0`，所以比较有可能是这个升级导致的。为了定位有问题的版本，我创建了以下这些不同版本的 APK，请问可以帮忙用二分查找的方式定位到第一个有问题的版本吗？

    - [libsu 5.0.1](https://github.com/zhanghai/MaterialFiles/actions/runs/6061134800)
    - [libsu 5.0.2](https://github.com/zhanghai/MaterialFiles/actions/runs/6061147758)
    - [libsu 5.0.3](https://github.com/zhanghai/MaterialFiles/actions/runs/6061148057)
    - [libsu 5.0.4](https://github.com/zhanghai/MaterialFiles/actions/runs/6061148432)
    - [libsu 5.0.5](https://github.com/zhanghai/MaterialFiles/actions/runs/6061149044)
    - [libsu 5.1.0](https://github.com/zhanghai/MaterialFiles/actions/runs/6061149521)
    - [libsu 5.2.0](https://github.com/zhanghai/MaterialFiles/actions/runs/6061149582)

如果您有空在周末这两天试一试的话，我就可以尽快把几个修复一起发个新版。谢谢！

**Comment by zhanghai** [comment]
问了下 Magisk 的开发者们，他们也遇到了类似的问题：topjohnwu/Magisk#7214

似乎是主要和一加系统有关的，libsu 5.2.0 引入的一个 bug，所以退回 libsu 5.1.0 应该就好了。

**Comment by zhanghai** [comment]
你可以测试一下 https://github.com/zhanghai/MaterialFiles/actions/runs/6062428945 下的 APK，应该能够修复了。

**Comment by LindaFelicia** [comment]
👍已测试，这个版本解决了问题，谢谢
