### ISSUE TITLE
[Bug][UI] Switching small windows may cause the app bar color to be abnormal and not change back to white when scrolling to the top.

### ISSUE THREAD

**Issue by Jesse205** [zhanghai/MaterialFiles#1004]
https://github.com/zhanghai/MaterialFiles/assets/51242302/8f630ac3-8e19-4d4f-adb3-b38d137a8e06

切换小窗时可能导致应用栏颜色异常，滚动到顶部时未变回白色

Switching small windows may cause the app bar color to be abnormal and not change back to white when scrolling to the top.

**Comment by Jesse205** [comment]
![Screenshot_20230830_171048_me.zhanghai.android.files.jpg](https://github.com/zhanghai/MaterialFiles/assets/51242302/89622f77-1136-4a40-8fed-f18bff10dacc)

这会不会是MD自己的问题，还是华为的问题？
Is this the problem of MaterialComponents or HMOS?

**Comment by zhanghai** [comment]
Might be Huawei's issue, the card background should never be like that.
