### ISSUE TITLE
[Question] How can I move files between folders

### ISSUE THREAD

**Issue by kostadin-damyanov-prime** [zhanghai/MaterialFiles#1021]
Hello.

I just installed the latest version of this app from f-droid and I am trying to organize my files. I selected the files I ned to move but in the context menus I can not find an option to move the files to another folder. Does this app support moving files?

**Comment by mak7im01** [comment]
Use the “Cut” button in the menu, then go to the folder you want to paste into, click the “Paste” icon in the lower right corner.
