### ISSUE TITLE
使用Sui打开根目录崩溃

### ISSUE THREAD

**Issue by Citrinae-Lime** [zhanghai/MaterialFiles#1026]
App版本: v1.6.1@[1ed7316](https://github.com/zhanghai/MaterialFiles/actions/runs/6155305810)
Sui模块版本: v13.5.0@[3ffd023](https://github.com/RikkaApps/Sui/actions/runs/6025849570)

不只是根目录，所有基于shizuku的访问都崩溃，同样的错误。
日志》[me.zhanghai.android.files_2023-09-14T18_01_56.993.log](https://github.com/zhanghai/MaterialFiles/files/12611023/me.zhanghai.android.files_2023-09-14T18_01_56.993.log)

> 试了十次，有两次是提示超时。
> 现在检测到Sui拒绝后不会请求普通Root权限吗? 必须要Sui隐藏自己才能授权普通Root。

**Comment by zhanghai** [comment]
似乎是 Rikka 的问题，转给她了

https://github.com/RikkaApps/Shizuku-API/blob/b26fcc841efcec90ae83a9de59ce590b8f298e75/server-shared/src/main/java/rikka/shizuku/server/util/HandlerUtil.java#L17

关于 libarchive，肯定是 bug，但为什么会无法 mktemp 呢……我 Android 13 没有复现这个问题，你是在什么平台上怎么遇到的？

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/Sui/actions/runs/6194401942 试一试这个（如果它还在 build 就等一会（

**Comment by zhanghai** [comment]
居然是 Sui 而不是 Shizuku-API 的 bug…… @Citrinae-Lime 能请你试一下么？我目前手头没有 root 的设备（

**Comment by Citrinae-Lime** [comment]
现在是超时了
![Screenshot_2023-09-15-08-08-06-266_me.zhanghai.android.files.jpg](https://github.com/zhanghai/MaterialFiles/assets/85402382/8a8fea16-9d7f-43f4-ba77-e5e0dbd7534f)

**Comment by zhanghai** [comment]
请提供 log（

**Comment by Citrinae-Lime** [comment]
重新安装后好了😀

**Comment by Citrinae-Lime** [comment]
> 现在是超时了
> 

测试了一下，是在我使用AGP `8.2.0-beta04`并开启R8 full的情况下才会出现(~~属于是预期行为~~
