### ISSUE TITLE
libarchive压缩7z无法创建临时文件

### ISSUE THREAD

**Issue by Citrinae-Lime** [zhanghai/MaterialFiles#1027]
系统：MIUI12.5,A11

日志： [logcat *:W.txt](https://github.com/zhanghai/MaterialFiles/files/12618756/logcat__W.txt)

截图：![Screenshot_2023-09-15-08-01-58-065_me.zhanghai.android.files.png](https://github.com/zhanghai/MaterialFiles/assets/85402382/158a781c-13e4-4a1c-899e-3260c249226b)

**Comment by zhanghai** [comment]
感谢！在 zhanghai/libarchive-android@f2bde2f 里修复了问题并且在模拟器测试通过了，你也可以试试 https://github.com/zhanghai/MaterialFiles/actions/runs/6205027553
