### ISSUE TITLE
Change default directories?

### ISSUE THREAD

**Issue by Schnyarf** [zhanghai/MaterialFiles#1029]
I would understand if this is well outside the scope of this project, but I'm curious if it's possible to change things like the default 'Downloads' or 'Music' directories at a system-wide level. I wonder how apps know where the OS opts to place those directories, or whether they're in an SD card.

I've always wanted to move the Alarms, Music, Notifications, Podcasts, Recordings, and Ringtones directories into a single 'Audio' directory, for instance.

Is there some obscure ADB command or root app or something that accomplishes this? It'd be neat if this app had a UI for that, but I understand if that's not feasible.

Any knowledge would be appreciated :)

**Comment by zhanghai** [comment]
That is complicated but doable with the paid app [Storage Isolation](https://play.google.com/store/apps/details?id=moe.shizuku.redirectstorage) if your device is rooted.

Disclaimer: I'm not associated with that app and anything connected to rooting may be dangerous (e.g. device bricked, data loss), so I'm merely providing the info for your convenience and please proceed at your own risk.
