### ISSUE TITLE
[Feature Request] Implement Directory Picker

### ISSUE THREAD

**Issue by ayykamp** [zhanghai/MaterialFiles#1032]
Currently this app only support picking a file, and you still have to use documentsui to pick a directory. If I disable documentsui any app trying to pick a folder will crash. This is what it looks like currently:
![IMG_20230921_131512](https://github.com/zhanghai/MaterialFiles/assets/32194363/6ab58347-d3d3-49ca-800b-7767227974a7)
Is would be very nice to use Material Files to pick a directory instead.

**Comment by chenxiaolong** [comment]
I don't believe this is possible for any third party app to implement. There are 3 ways an app can open a file picker on Android:

* `ACTION_GET_CONTENT`
  * For selecting files.
  * File access goes through a third party app, like Material Files.
* `ACTION_OPEN_DOCUMENT`
  * For selecting files.
  * File access goes through the system's "document provider".
  * Only DocumentsUI has the ability to grant access to the system's document provider.
* `ACTION_OPEN_DOCUMENT_TREE`
  * For selecting directories.
  * Directory access (and files within the directory) goes through the system's "document provider".
  * Only DocumentsUI has the ability to grant access to the system's document provider.

While it's theoretically possible for a third party file manager to display a file picker for `ACTION_OPEN_DOCUMENT` and `ACTION_OPEN_DOCUMENT_TREE`, there's no way for it to actually grant permissions to the path that was selected.

**Comment by zhanghai** [comment]
You should never disable DocumentsUI and Material Files cannot replace DocumentsUI.

**Comment by ayykamp** [comment]
Alright thanks for clearing this up :)
