### ISSUE TITLE
FTP into external server rather than host server

### ISSUE THREAD

**Issue by tdadvocate** [zhanghai/MaterialFiles#1037]
I want to start off by saying I'm not very well versed in FTP stuff so i lack the proper terminology. I want to connect to another device that is hosting the FTP server so that i can copy files from said device onto my phone. The phone has to be the one connecting to the other device as the other device does not have the ability to connect to one being hosted from my phone. Is this possible currently? If not, is it possible to add this feature? Its the only thing stopping me currently from using this app for all file management on my phone currently. I really hate having to use another app (FTP Tool) just to copy files to and from this other device.

**Comment by zhanghai** [comment]
Add storage -> FTP server
