### ISSUE TITLE
Support physical keyboard shortcuts

### ISSUE THREAD

**Issue by Kelvinlby** [zhanghai/MaterialFiles#1054]
I often use this app on my tablet with a mouse and a keyboard, and I find it inconvenient to cut/copy/paste files/folders without Ctrl+x/c/v.

**Comment by Kelvinlby** [comment]
[Handle keyboard shortcut](https://developer.android.com/develop/ui/views/touch-and-input/keyboard-input/commands)

**Comment by zhanghai** [comment]
Another interesting thing: https://stackoverflow.com/questions/71062697/register-hardware-keyboard-shortcuts-in-androids-help-menu
