### ISSUE TITLE
一个从MT管理器所发现的插件及引发的建议

### ISSUE THREAD

**Issue by naloder** [zhanghai/MaterialFiles#106]
https://www.lanzous.com/i4hoync
(插件分流地址)

之前在高版本安卓上使用MT管理器时，选择打开方式，提醒我安装了这个插件，之前在分享菜单不可见的百度输入法(那个打开方式是用来从外部安装输入法皮肤的)，同理原来几个看不见的打开方式也出现了。希望可以研究一下加入:joy:

**Comment by zhanghai** [comment]
请问是怎样的分享菜单，以及有截图吗？“原来几个看不见的打开方式”是怎样的几个打开方式？

**Comment by naloder** [comment]
是选择打开方式的分享菜单，![](https://i.imgur.com/1nFKymS.jpg)，原来看不见的打开方式是一些由外部直接调用程序内功能的打开方式，如图上的百度输入法那个是用来在外部安装皮肤文件的

**Comment by zhanghai** [comment]
不太明白……
