### ISSUE TITLE
Support RAR archive files

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#107]
https://github.com/junrar/junrar
https://gitlab.com/axet/java-unrar

**Comment by zhanghai** [comment]
Maybe switch to p7zip: http://sevenzipjbind.sourceforge.net/

**Comment by zhanghai** [comment]
Or libarchive: https://github.com/libarchive/libarchive

**Comment by zhanghai** [comment]
Done with junrar.

**Comment by Suburbanno** [comment]
@zhanghai Hi, I can't extract a .rar file
![Screenshot_20191219-115652](https://user-images.githubusercontent.com/13632826/71183474-d0924480-2256-11ea-87a6-2cbeede46682.png)

**Comment by zhanghai** [comment]
It's probably a RAR5 file and `junrar` doesn't support it. There isn't much RAR5 support in any java library that I know for now, because the format is still relatively new.

**Comment by Suburbanno** [comment]
@zhanghai How can I tell if the .rar is RAR5? opening in properties shows only .rar
![image](https://user-images.githubusercontent.com/13632826/71222589-dbc58e80-22af-11ea-81b3-a31ecc43f80c.png)

**Comment by zhanghai** [comment]
Please see https://www.ghacks.net/2013/12/03/identify-open-rar5-archives/

**Comment by Suburbanno** [comment]
@zhanghai 
![image](https://user-images.githubusercontent.com/13632826/71226875-306f0680-22bc-11ea-94c5-642f7778338d.png)

**Comment by zhanghai** [comment]
`Version to extract` says `5.0`, so I believe it's an RAR5 archive.

**Comment by Suburbanno** [comment]
https://github.com/edmund-wagner/junrar/issues/48

**Comment by zhanghai** [comment]
The OP in that issue suggested to search for a new header signature to support RAR5, but I don't think the only archive format change in RAR5 is about changing signature. There are more likely structural and algorithm changes as well, which might need considerable amount of work in `junrar`. But neither me nor Amaze team seems to be interested in becoming the new maintainer for `junrar` 😅

The archive support in this file manager is not meant to fully replace a dedicated archive manager (with fancy archive formats, multi-threading and password support), so you can still open the archive file in one of those apps.
