### ISSUE TITLE
[Feature Request] Add http server as an option of sharing local file.

### ISSUE THREAD

**Issue by DasCrystal** [zhanghai/MaterialFiles#1072]
I know there already have a ftp server to share local files, but I found that most mobile browser (like Chrome, Opera etc.) doesn't support ftp protocol (ftp:// prefix goes to search page).

So, I want request a feature, which could start a server that can share files under a directory, but supports more browsers. Just like Apache and python http module.

**Comment by zhanghai** [comment]
#694
