### ISSUE TITLE
[Feature Request] Add storage support custom Linux path

### ISSUE THREAD

**Issue by ty114514** [zhanghai/MaterialFiles#1083]
Sometime I need edit some profile or dump some file from like /data/data/com.xxx/xxxxx/

Current Android/data or Android/obb or External Storage use URI, not Linux path

**Comment by zhanghai** [comment]
For now you can still edit the URI, the latter part of the URI is the encoded Linux path.

**Comment by ty114514** [comment]
Can you give some examples? I try to edit but doesn't work

**Comment by zhanghai** [comment]
> Can you give some examples? I try to edit but doesn't work

`content://com.android.externalstorage.documents/tree/primary/document/primary%3AAndroid%2Fdata%2Fcom.google.android.apps.maps` for Google Maps.

**Comment by ty114514** [comment]
Oh...

I mean is linux root path(already give root permission), like /data /system /etc, not /storage/emulated/0/Android/data (I know this can use External storage to set)

Mabe MaterialFiles can be a good root file manager

**Comment by zhanghai** [comment]
In that case you can use Go to... in three dot menu and bookmark that directory.

**Comment by ty114514** [comment]
Sorry for my bad English, I just understood your suggestion just now
