### ISSUE TITLE
想问一下通过【NightModeHelper】的方式去更改日夜间与【AppCompatDelegate.setDefaultNightMode()】的区别是什么，主要是为了灵活性吗？

### ISSUE THREAD

**Issue by gkj17** [zhanghai/MaterialFiles#1094]
看到代码中有提及到两种优势：
1. 我们可以在更改时重新创建所有活动，而不是只创建已启动的活动。
2. 我们可以自定义处理变更，而不是被迫重新创建或更新活动共享的资源配置。

是否意味着【NightModeHelper】的方式是更灵活的？这些方式是setDefaultNightMode所不具有的吗？

**Comment by zhanghai** [comment]
是的，至少一年前还是这样，最近我没有再去跟进新的 appcompat 实现但大概率依然是这样。

以及代码问题还是不要在这里问了，大多数人是作为使用者而不是 Android 开发学习者来订阅这个项目的通知的，而对非中文使用者就更加打扰了。有问题的话还请自己钻研。
