### ISSUE TITLE
删除大量文件时速度慢

### ISSUE THREAD

**Issue by BinTianqi** [zhanghai/MaterialFiles#1095]
删除大量的小文件时，每秒只能删除大约200个文件。
而在termux中使用rm -rf命令，不到一秒就可以全部删除。
应用版本：1.6.2
平台：vivo pd1932a arm64-v8a 安卓10
https://github.com/zhanghai/MaterialFiles/issues/349
我觉得使用rm -rf命令是解决这个问题的方法。
![IMG_20231226_233827](https://github.com/zhanghai/MaterialFiles/assets/146811279/b65117a3-368c-4d92-b36d-fe60ee15c2ec)
![IMG_20231226_233847](https://github.com/zhanghai/MaterialFiles/assets/146811279/1c94c1e7-71a2-4f03-959e-9a98782341d1)

**Comment by zhanghai** [comment]
要支持显示进度和错误重试等等就是会慢些。在意速度还是直接 rm -rf 吧。这在 Linux 上也有类似的问题。
