### ISSUE TITLE
[Question] How to copy files from Internal storage to a folder withing the "android/data/folder"?

### ISSUE THREAD

**Issue by TimyIsCool** [zhanghai/MaterialFiles#1101]
Ive tried to copy over files but I cant figure out how, Ive added the data folder in storage but cant copy

**Comment by zhanghai** [comment]
You will need to go up from within the system (DocumentsUI) app that shows Android/data, find and copy/cut you file, and then go back into Android/data to paste. It's cumbersome but an unfortunate effect after the system locked down Android/data.

**Comment by TimyIsCool** [comment]
Ive tried that but when I press copy to it sends me to my downloads and can no longer go to the data folder

**Comment by zhanghai** [comment]
You can go back to your internal storage after selecting "Copy to" by opening the drawer and selecting it.

**Comment by TimyIsCool** [comment]
I have tried that by going to the menu, picking my device but wont allow me to pick the android folder as it only shows a folder called "media"

**Comment by zhanghai** [comment]
Sorry, you are right, it seems an limitation imposed by DocumentsUI that you can't copy/move things into Android/data, only out of it. I would agree it's strange but there's nothing I can do to fix it either.

Workarounds could be doing it on PC via adb shell (not sure if MTP works), or rooting your device and giving Material Files root access.

**Comment by ManDay** [comment]
Is there a fix to this? Is it by AOSP design that you can't move things *into* `Android/data` but only out of it? It seems completely ridiculous...
