### ISSUE TITLE
[feature advice] Really nice & simple app, hope SSH file browser can be supported

### ISSUE THREAD

**Issue by wishday** [zhanghai/MaterialFiles#1105]
Hope SSH file browser can be supported

**Comment by pasnox** [comment]
Add storage > Ssh ?

**Comment by wishday** [comment]
> Add storage > Ssh ?

That's exactly what i mean, this help a lot for server maintainers

**Comment by wishday** [comment]
> Add storage > Ssh ?

my fault, SSH file broswer is exactly equal to SFTP

**Comment by wishday** [comment]
> Add storage > Ssh ?

my fault, SSH file broswer is exactly equal to SFTP, which is supported already
