### ISSUE TITLE
Request for progression bar while copying big files

### ISSUE THREAD

**Issue by vinny2474** [zhanghai/MaterialFiles#1108]
Hello,
I use Material Files on a Android video player and don't have keyboard nore mouse. I use it to move video files from one drive to another, and I would like to have a progression bar when copying files just to know when Material Files has finished the job (or at least a persistent message to say job has finished, to be clicked to be acknowledged).
Thanks,
vinny2474

**Comment by zhanghai** [comment]
There's a notification for file operations and you can see the progres bar there.

**Comment by vinny2474** [comment]
Thanks for your quick answer, I can't see where the progress bar is, can you send me a screenshot please ?

**Comment by zhanghai** [comment]
This is how it looks like on phone. I only have Android phone and tablet though.

![Screenshot_2024-01-20-12-07-46-02_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://github.com/zhanghai/MaterialFiles/assets/4469895/0b4ee4ee-80e7-43a0-9c53-39aed4ca663d)

**Comment by vinny2474** [comment]
Understood, my device has not notification like this, that is why I can't see it.
