### ISSUE TITLE
Open Terminal

### ISSUE THREAD

**Issue by black00019** [zhanghai/MaterialFiles#1114]
the old open source terminal application is no longer developed, it is possible to implement this one: TermOne (https://play.google.com/store/apps/details?id=com.termoneplus) is the clone of the previous one which is also open source.
Thank you

**Comment by Archie-2021** [comment]
Sorry, but how should i set up a terminal application? I have termux installed but dont know how make it work with this app

**Comment by zhanghai** [comment]
See also https://gitlab.com/termapps/termoneplus/-/issues/64 for what needs to happen on TermOnePlus side.
