### ISSUE TITLE
Add get it on github badge to Readme

### ISSUE THREAD

**Issue by inson1** [zhanghai/MaterialFiles#1118]

**Comment by inson1** [comment]
@zhanghai I dont think github has it somewhere, so use this link or save it to reposiory and use it
https://i.ibb.co/q0mdc4Z/get-it-on-github.png

**Comment by zhanghai** [comment]
What is the license of this image?

Meanwhile, the image has a whitish background so that it won't work well for people using dark mode. The image has to be something with a transparent background.

**Comment by inson1** [comment]
@zhanghai this guy is saying its from him and that is under Creative Commons license v4

https://github.com/Kunzisoft/Github-badge

you may use the svg, but your other badges seem to have same problem

**Comment by zhanghai** [comment]
I don't think my other badges have the same issue though because obviously Google Play and F-Droid is okay with people using their badges.

**Comment by inson1** [comment]
@zhanghai I meant with "Meanwhile, the image has a whitish background so that it won't work well for people using dark mode. The image has to be something with a transparent background."

**Comment by zhanghai** [comment]
> @zhanghai I meant with "Meanwhile, the image has a whitish background so that it won't work well for people using dark mode. The image has to be something with a transparent background." Both other badges have it too.

The other badges have transparent background at least on my end. I'm using dark mode so it's obvious to me.
