### ISSUE TITLE
[Enhancement] Support AVIF image with odd width/weight

### ISSUE THREAD

**Issue by Vinfall** [zhanghai/MaterialFiles#1120]
I know that Material Files supports AVIF already, but some images are not working well.

For example, many images with odd width or height in [avif-sample-images](https://github.com/link-u/avif-sample-images) would throw the following error:

```java
java.lang.IllegalStateException: BitmapFactory returned a null bitmap.
Often this means BitmapFactpry could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as valid image format
```

However, I can browse the same file in either desktop Firefox or mobile Chromium. Not sure if it's a library issue from upstream (I don't know _which_ library, anyway) so I just reported here.

Some information:
- App version: 1.6.2 (34) via F-Droid
- Android version: 12
- OS: vivo iQOO originOS

**Comment by zhanghai** [comment]
Material Files just uses the system image decoder for loading AVIF, so if there's a bug you'll need to update your system. Browsers probably ship their own image decoders but that's not feasible for this app.
