### ISSUE TITLE
Can't recognize ts file as video format

### ISSUE THREAD

**Issue by SempakRangerGG** [zhanghai/MaterialFiles#1122]
Tapping them doesn't show any video player app

**Comment by mayhair** [comment]
This is because Transport Stream video files and Typescript code files have the same file extension, `.ts`. Material Files just decides to interpret all files with the `.ts` extension as Typescript files.

**Comment by zhanghai** [comment]
Material Files uses Android's official extension and MIME mapping and unfortunately there's no good solution to resolve such a conflict. You can still use "Open with" then "Open as" to manually open it as video.
