### ISSUE TITLE
Allow SRT files to be opened directly

### ISSUE THREAD

**Issue by mayhair** [zhanghai/MaterialFiles#1123]
Material Files will only show text editors upon tapping on a file, if it sends a MIME type that starts with `text/`.

Currently, opening SRT subtitle files sends the MIME type `application/x-subrip`. This is despite the fact that SRT files are essentially plain text, and thus can be viewed and edited with a text editor. To open it with a text editor, one either needs to change the file extension from SRT to TXT, or to use the Material Files "open as Text" function. Both will change the MIME type to `text/plain` (as evidenced by my use of [Intent Intercept](https://github.com/intrications/intent-intercept)).

**Comment by mayhair** [comment]
Another issue with MIME types that I noticed is #1122.

**Comment by zhanghai** [comment]
Yes, but if Material Files change the MIME type to `text/plain` that would break any subtitle editor app that actually relies on the correct MIME type. So I think in terms of this conflict Material Files should keep using the correct MIME type and you may use open-as as the workaround.
