### ISSUE TITLE
Trackers

### ISSUE THREAD

**Issue by Ugau943** [zhanghai/MaterialFiles#1127]
Hi,

Could we get rid of the [two trackers](https://reports.exodus-privacy.eu.org/en/reports/403818/#trackers), at least in the apk version, because well, you know ...

It's a bit disturbing not to have the same experience as with the F-droid version, which [don't have any tracker](https://reports.exodus-privacy.eu.org/en/reports/391787/).

Thank you for your work !

https://reports.exodus-privacy.eu.org/en/reports/403818/

https://reports.exodus-privacy.eu.org/en/reports/391787/

**Comment by zhanghai** [comment]
See https://github.com/zhanghai/MaterialFiles/issues/1000#issuecomment-1695318194

**Comment by Ugau943** [comment]
Yes, I'm sorry for the duplicate. I really don't know why I didn't find the (already) 3 issues that deal with this subject.

I understand your motivation, thank you for taking the time to reply.
