### ISSUE TITLE
FTP客户端命令LIST -a中的参数-a符合协议标准吗？

### ISSUE THREAD

**Issue by lbp0** [zhanghai/MaterialFiles#1133]
我最近正在编写一个FTP服务器，并用这个项目进行了访问测试。但是我发现这个项目并没法读取到服务器里的数据。从谷歌play下载的最新版(1.6.2)app中，我注意到这个项目里FTP客户端LIST命令后有参数-a，这符合协议标准吗？

我找到的最新有关FTP的协议标准是[RFC 5797](https://www.rfc-editor.org/rfc/rfc5797.html)，其中提到了[RFC 1123](https://www.rfc-editor.org/rfc/rfc1123#page-31)对LIST命令的更新，但我并没有发现在RFC 1123的命令更新中，有对命令的用法做出了什么改变。随后RFC 1123便是引用了经典的RFC 959，我相信这个参数在RFC 959里应该是不合法的。

还请大家帮忙确认一下是否真的是这样，如果真是这样的话这个-a参数可能并不是一个标准的协议参数。使用一些更现代的命令取代LIST或者干脆移除-a参数是不是更为恰当？

**Comment by zhanghai** [comment]
> 我注意到这个项目里FTP客户端LIST命令后有参数-a，这符合协议标准吗？

大概确实是非标准的，但 Commons Net [`FTPClient.setListHiddenFiles()`](https://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPClient.html#setListHiddenFiles(boolean)) 提供了它，并且确实有些服务器在没有它时不会返回所有文件。

> 使用一些更现代的命令取代LIST或者干脆移除-a参数是不是更为恰当？

所以本项目默认使用的是 `MLST` 和 `MLSD`。

**Comment by lbp0** [comment]
好的好的，谢谢大佬解答🎉
