### ISSUE TITLE
[Feature Request] Opening archives in external applications

### ISSUE THREAD

**Issue by caretooker** [zhanghai/MaterialFiles#1137]
Hi.
First of all, I would like to thank the developer for this wonderful app. I consider it the best one so far - being FOSS, beautiful, minimalistic and at the same time multi-functional, for me it put an end to all the old xplore/total commander and miserable "99999999 in 1" es file explorer and other file manager knockoffs.

I would like to propose a feature that would allow opening archives in external applications - for example, my ebook reader opens books without unzipping them, which saves me space, or, for example, opening archives quickly in external archivers that can unzip larger archives faster. This would also, for example, solve the problem of the user who described it in #1134.
I think this small feature would improve usability a lot, at least for me.
Thanks.

**Comment by zhanghai** [comment]
I think "Open with..." in the menu should work?

**Comment by wishday** [comment]
"Open with..." meight help for this issue.  
Issue #1134 can't be solved by  "Open with..."
