### ISSUE TITLE
[Feature Request] In-app public/private key pair generation for SFTP

### ISSUE THREAD

**Issue by mamekoro** [zhanghai/MaterialFiles#1138]
Currently, we must generate an SSH public/private key pair somewhere outside of MaterialFiles to use the SFTP functionality.

That means that the private key will be temporarily exposed through the Android system's clipboard or file system. This is because the current implementation requires that the private key be entered into MaterialFiles via the clipboard or a file.

My idea is to allow MaterialFiles to generate SSH public/private key pairs and export public keys.

In this way, private keys stay in the private data directory of MaterialFiles and are not exposed. The user then appends an exported public key to the `authorized_keys` file on the SFTP server and the key setup is complete.

The Android apps ConnectBot and Keepass2Android have the ability to generate SSH key pairs and export public keys, which may be helpful as references.

**Comment by zhanghai** [comment]
I think you can generate key in apps like Termux and let Material Files read the key from there. I don't have immediate plan to add this right now.
