### ISSUE TITLE
Material files Api cannot open SD card filepaths and Termux home file paths

### ISSUE THREAD

**Issue by minnesjay** [zhanghai/MaterialFiles#1148]
This [command](https://github.com/zhanghai/MaterialFiles/issues/785#issuecomment-1125623513) can always open the folder in internal storage correctly. 

```
adb shell am start -n 'me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity' -a android.intent.action.VIEW -t 'vnd.android.document/directory' -e 'org.openintents.extra.ABSOLUTE_PATH' '/storage/emulated/0/Music'
```

**However this api does causes Material files to crash when used on SD card file paths and Termux Home Filepaths.**

Sd card file path:
```
document:///content://com.android.externalstorage.documents/tree/0000-0000%253A?/
```

Termux home file path:
```
document:///content://com.termux.documents/tree/%252Fdata%252Fdata%252Fcom.termux%252Ffiles%252Fhome?/
```

If I use this api on to open material files with the SD card file path it causes material files to crash:

```
adb shell am start -n 'me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity' -a android.intent.action.VIEW -t 'vnd.android.document/directory' -e 'org.openintents.extra.ABSOLUTE_PATH' 'document:///content://com.android.externalstorage.documents/tree/0000-0000%253A?/'
```

Meanwhile inside the app the "Go to" path function works when using it on termux and sd card file paths. **So is the "Go to" function different from the absolute path api?** Since that works with both termux and sd card file paths, but the api I am currently using does not work with those 2 filesystems.

**Comment by zhanghai** [comment]
`org.openintents.extra.ABSOLUTE_PATH` is supposed to be a Linux file system path so it was interpreted as `document:/content:/com.android.externalstorage.documents/tree/0000-0000%253A?/` with the redundant slashes dropped, where `document:/` is interpreted as a Windows drive letter by Java's `Path`.

I don't think there's a `document://` scheme on Android either, document provider URIs are still content URIs.

You should be able to pass the content URI as `DocumentsContractCompat.EXTRA_INITIAL_URI`.

**Comment by minnesjay** [comment]
Thank you for your clarification on this.

I tried passing the content uri but this does not open termux's home directory in material files for me, is there something I'm missing?.

```shell
adb shell am start \
  -n 'me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity' \
  -a android.intent.action.VIEW \
  -t 'vnd.android.document/directory' \
  --es 'android.provider.extra.INITIAL_URI' 'content://com.termux.documents/tree/%252Fdata%252Fdata%252Fcom.termux%252Ffiles%252Fhome?/'
```

**Comment by zhanghai** [comment]
If you are passing a URI it needs to be an instance of the `android.net.Uri` class, so `--es` which is for `String` arguments won't work. Maybe you can pass the URI as intent data instead.

**Comment by minnesjay** [comment]
Thank you I tried passing the URI as intent data instead, this opens the path `content://com.termux.documents/tree/%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fhome%3F/`

No files are shown and it causes the error: `java.lang.UnsupportedOperationException`

But the path copied from finding Termux home manually in material files is `document:///content://com.termux.documents/tree/%252Fdata%252Fdata%252Fcom.termux%252Ffiles%252Fhome?/`


```shell
adb shell am start \
  -n 'me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity' \
  -a android.intent.action.VIEW \
  -t 'vnd.android.document/directory' \
  -d 'content://com.termux.documents/tree/%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fhome%3F/'
```

**Comment by zhanghai** [comment]
Try this:

```bash
adb shell am start \
  -a android.intent.action.VIEW \
  -t vnd.android.document/directory \
  -e me.zhanghai.android.files.extra.PATH_URI 'document:///content://com.termux.documents/tree/%252Fdata%252Fdata%252Fcom.termux%252Ffiles%252Fhome?/' \
  me.zhanghai.android.files
```

**Comment by minnesjay** [comment]
Thank you! That works for both termux paths and for sd card paths!
