### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by Krishna-G-OP** [zhanghai/MaterialFiles#1149]
Hey,

I am a web developer, I'd be happy to contribute to your project and its continued development. I've reviewed the project (Material Files) and believe my skills in web development could be valuable. I see that the project (Material files) currently don't have a website, I think i can contribute to the process of web development as I'm interested in exploring contribution opportunities.

Please let me know how I can best get involved based on the project's current needs.

**Comment by zhanghai** [comment]
Thanks but I don't need a website right now.
