### ISSUE TITLE
Crashes when tapping to zip files

### ISSUE THREAD

**Issue by popogomo** [zhanghai/MaterialFiles#1150]
The latest version of the app crashes when tapping to zip files in order to open /extract them. I am using the latest version of GrapheneOS.

Here is the log:

type: crash
osVersion: google/cheetah/cheetah:14/AP1A.240305.019.A1/2024030900:user/release-keys
package: me.zhanghai.android.files:34
process: me.zhanghai.android.files
processUptime: 0 + 0 ms
installer: dev.imranr.obtainium

signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000008

backtrace:
      #00 pc 0000000000081230  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/lib/arm64/libarchive-jni.so (Java_me_zhanghai_android_libarchive_Archive_free+68) (BuildId: 5aac375a93b05300900d02c95f753f1f160904ba)
      #01 pc 0000000000916120  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (art_jni_trampoline+112)
      #02 pc 00000000011b38a0  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (yl.k.o+1504)
      #03 pc 0000000000c8bd00  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (bd.f.l+160)
      #04 pc 0000000000c8f364  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (bd.g.s+276)
      #05 pc 000000000152d698  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (androidx.lifecycle.d1.j+472)
      #06 pc 0000000000dd2ce0  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (h9.c.k+592)
      #07 pc 0000000000e9fbf0  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (me.zhanghai.android.files.provider.root.u.s+304)
      #08 pc 000000000087e530  /data/app/~~NX4pBWig3NWHqQAPBc-jOA==/me.zhanghai.android.files-WmsFRsCGTLQ_r9XaTDlmuw==/oat/arm64/base.odex (k5.l.call+1104)
      #09 pc 00000000002291d4  /system/framework/arm64/boot.oat (java.util.concurrent.FutureTask.run+164) (BuildId: 115665d46c23f11ae2b45208989adc7de47f6b73)
      #10 pc 000000000027ad98  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+680) (BuildId: 115665d46c23f11ae2b45208989adc7de47f6b73)
      #11 pc 0000000000278868  /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+56) (BuildId: 115665d46c23f11ae2b45208989adc7de47f6b73)
      #12 pc 000000000014b310  /system/framework/arm64/boot.oat (java.lang.Thread.run+64) (BuildId: 115665d46c23f11ae2b45208989adc7de47f6b73)
      #13 pc 00000000003e1d74  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: e2d4c7ae9fa225f36a825be113720b47)
      #14 pc 00000000003c60ec  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+220) (BuildId: e2d4c7ae9fa225f36a825be113720b47)
      #15 pc 00000000004d2cb8  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1656) (BuildId: e2d4c7ae9fa225f36a825be113720b47)
      #16 pc 00000000004d2628  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8) (BuildId: e2d4c7ae9fa225f36a825be113720b47)
      #17 pc 00000000000cf93c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: a8cd74908de1830f20f574f8d622db82)
      #18 pc 0000000000066730  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a8cd74908de1830f20f574f8d622db82)

**Comment by zhanghai** [comment]
Are you a custom ROM user? If so please try the APK in https://github.com/zhanghai/MaterialFiles/issues/1065#issuecomment-1863818336 . Please re-open if that didn't work for you.
