### ISSUE TITLE
Can't authenticate over Tailscale

### ISSUE THREAD

**Issue by glibg10b** [zhanghai/MaterialFiles#1152]
[Tailscale](https://tailscale.com/) is a VPN that allows users to connect to their devices remotely, even when they're behind complicated NAT and firewall setups.

One of its features is [Tailscale SSH](https://tailscale.com/tailscale-ssh), which overrides the authentication method so users can authenticate by logging into tailscale in a browser from the same IP. This is more secure for reasons they explain (passwords are insecure; private keys can be stolen and nobody rotates them).

As far as I'm aware, Tailscale SSH isn't optional.

The system SSH binary automatically figures out that it should use Tailscale's authentication method.

Markdown Files, however, only offers two authentication options when connecting to an SFTP server:
- Password 
- Public key

It throws "UserAuthException: Exhausted available authentication methods", regardless of which I choose or whether I supply a password.

**Comment by zhanghai** [comment]
I don't use tailscale and I don't have knowledge in how `The system SSH binary automatically figures out that it should use Tailscale's authentication method`. If you can offer more details I can look into whether it's feasible for this app.

**Comment by glibg10b** [comment]
Found one: https://github.com/nickdurante/Spider

It apparently uses [JSch](https://mvnrepository.com/artifact/com.jcraft/jsch) for SSH

**Comment by zhanghai** [comment]
OK, I'll track this in #1156 instead.
