### ISSUE TITLE
Update 1.7.0 Broke true black and Black night mode toggle

### ISSUE THREAD

**Issue by mateomautone** [zhanghai/MaterialFiles#1163]
App just updated today on fdroid, and black night mode is no longer working, turning it on disables material design 3 for some reason also.
![1](https://github.com/zhanghai/MaterialFiles/assets/30269678/362dc23f-ff2e-4030-a36e-835dfb3449ce)
![2](https://github.com/zhanghai/MaterialFiles/assets/30269678/284ebc79-ca47-4dea-8abe-d3b893787eeb)

**Comment by mateomautone** [comment]
Oh, didn't see that 1.7.1 fixed this issue sorry, will wait for the update on fdroid

**Comment by gili-gili** [comment]
Same problem. Waiting for F-Droid builds
