### ISSUE TITLE
访问date无法使用质感文件

### ISSUE THREAD

**Issue by TTDNS** [zhanghai/MaterialFiles#1169]
在质感文件添加存储选择date会跳转到安卓原生文件，发现系统自带的文件管理竟可以直接访问date目录，可这让我无法使用质感文件访问date添加书签的功能
![Screenshot_20240319_223726](https://github.com/zhanghai/MaterialFiles/assets/159039886/a6233c39-0c39-4dc8-a996-2721a675bb70)

**Comment by zhanghai** [comment]
高版本 Android 系统中除原生文件管理器以外无法访问 Android/data，因此跳转是有意实现的。

**Comment by TTDNS** [comment]
我的安卓12原生管理器可以直接访问date，跳转没有质感文件的书签功能
