### ISSUE TITLE
Material 3 is _bloated_ 

### ISSUE THREAD

**Issue by goyalyashpal** [zhanghai/MaterialFiles#1170]
i just read via release notes of f-droid this:

https://github.com/zhanghai/MaterialFiles/blob/9dfb35b9f9f7fb9d7da05c8dfe5b60d94437bd2e/fastlane/metadata/android/en-US/changelogs/35.txt#L7

and while dumping material 2 its inevitable, i just came here to say how important its existence is for me.

... they really messed up the material 3 or whatever is its name. i havent updated even the pdf reader i use (mj pdf) after it "downgraded" to this new big button bloat ui.

ofc in the worst case, i would have to eventually stettle at it too. the only change would be the feeling that yeah, i just have to put up with this yet another crap google threw at me.

feel free to close this as not planned.

**Comment by goyalyashpal** [comment]
look at this horrible mess from current versions of [mj]

<img src="https://gitlab.com/mudlej_android/mj_pdf_reader/-/raw/36830da1ee3957d52c560df5c0b1cbf8c4732461/fastlane/metadata/android/en-US/images/phoneScreenshots/light_full_screen_buttons_no_frame.png" width=300px />

now look at this sleek ui from pre-mat3 migration:

<img src="" width= />



[mj]: https://gitlab.com/mudlej_android/mj_pdf_reader/-/blob/36830da1ee3957d52c560df5c0b1cbf8c4732461/fastlane/metadata/android/en-US/images/phoneScreenshots/light_full_screen_buttons_no_frame.png
[mj_m3]: https://gitlab.com/mudlej_android/mj_pdf_reader/-/blob/36830da1ee3957d52c560df5c0b1cbf8c4732461/fastlane/metadata/android/en-US/images/phoneScreenshots/light_full_screen_buttons_no_frame.png

**Comment by zhanghai** [comment]
It

**Comment by zhanghai** [comment]
It's more about maintenance, though I don't see a huge difference between Material 2 and 3 either, unlike the difference between Material 1 and 2.

I feel the screenshot you shared isn't adhering to standard Material 3 design guidelines either. Not to say I can do better though.

**Comment by goyalyashpal** [comment]
> though I don't see a huge difference between Material 2 and 3 eithe

yeah, there isn't mostly. it's just that those giant big blobs of toggles ruin the whole consistency of it all.

**Comment by zhanghai** [comment]
Well that is exactly the size in the design spec. While I understand you personally don't like it, breaking design spec will almost certainly upset more people because it breaks consistency with all other Material 3 apps. I don't see a good solution to your UX preference unless Material 3 spec is changed so that everyone will move to a different direction.
