### ISSUE TITLE
SFTP file copying fails on 1.7.0

### ISSUE THREAD

**Issue by BenMcLean** [zhanghai/MaterialFiles#1174]
I have a Samsung Galaxy Note10.

On 1.6.2, I copy a folder from my STTP server to my phone's micro sd card without issue.

On 1.7.0, the same operation will create the outermost folder but won't copy the files inside and there's no error message.

My workaround for now is to stay on 1.6.2.

**Comment by zhanghai** [comment]
Duplicate of #1154.
