### ISSUE TITLE
Can't see the option in "open with"  to use material files

### ISSUE THREAD

**Issue by 5thdesert** [zhanghai/MaterialFiles#1176]
![Screenshot_2024-03-22-18-12-47-730_android](https://github.com/zhanghai/MaterialFiles/assets/164491840/a6bf45d1-42bd-430e-aa5d-003d56bf0057)

 
While this guy in YouTube can use material files to open it 
![Screenshot_2024-03-22-18-19-23-734_com google android youtube](https://github.com/zhanghai/MaterialFiles/assets/164491840/91be93e1-9fb2-49a7-aafb-6df454137a7b).
I would appreciate  any clarification guys,I'm noob

**Comment by zhanghai** [comment]
The first one "Text editor" in your first screenshot is Material Files. Some systems show the activity title, some systems show the overall app title.

**Comment by 5thdesert** [comment]
Thanks for clarifying. I gave your app 5 stars btw. You material files is
the best. Now we don't need PC any long just to open up fastboot files tgz
