### ISSUE TITLE
SMB/SFTP to Local storage - not working copy files

### ISSUE THREAD

**Issue by KapriQ** [zhanghai/MaterialFiles#1179]
Hello dev,

After upgrade from Android 13 to 14 (Vanilla) i can add my smb / sftp storage but i can't copy anything from external storage to internal.

Ot start copying and rhen the file disappear. 

Thanks

**Comment by 9Lukas5** [comment]
I have this problem on Amdroid 11, but it came as a regression with Material Files 1.7.0

Going back to 1.6.2 fixed it for me

**Comment by KapriQ** [comment]
You are right. Thanks. 1.6.2 works

**Comment by zhanghai** [comment]
1.7.1 should work.
