### ISSUE TITLE
WebDav 无法删除文件

### ISSUE THREAD

**Issue by Mooling0602** [zhanghai/MaterialFiles#1180]
如截图所示，已确认服务端权限配置没有问题
![Screenshot_20240325-173514_质感文件](https://github.com/zhanghai/MaterialFiles/assets/147964268/6d6ee56a-fdbc-4619-a300-b35fad0b1b08)

**Comment by zhanghai** [comment]
我也不太知道……服务器给出的就是 HTTP 405，然后我本地测试 WebDAV 删除没问题。

**Comment by Mooling0602** [comment]
玄学
