### ISSUE TITLE
Two SFTP servers can't transfer files between eachother if they have the same username

### ISSUE THREAD

**Issue by pinckpockett** [zhanghai/MaterialFiles#1204]
I have two remote machines that I want to transfer files to/from eachother. They have the same user name. For example porpuses the username will be user1. The two machines have different hostnames though. The first machine will be water and the  second, fire.

This problem arises when I want to send a file from one machine to another. Say I have a file file called afile.txt. There is a copy of afile.txt on the fire machine and the water machine. But when I try to send an updated version of the file from water to fire or vice versa, I get the ![error](https://github.com/zhanghai/MaterialFiles/assets/102638333/900c2476-e6f9-48f7-9e0a-e9bb1d115bbe) "cannot copy a file over itself." Then it prevents me from sending the updated file. I thought it was a limitation of sftp at first, but other apps such as the ooen source ghost commander app can send files which are copies of eachother. 

I also sent a file from water to an external hard drive which was connected to fire. The path of fire is /home/user1 and the path of water is /home/user1 the hostnames are different though. The path of the external hard drive connected to fire is for examples sake /mnt/hard_drive/folder1. I was able to transfer a files from water to the external hard drive which was already there and it just asked me if I wanted to overwrite the file. ![picture 2](https://github.com/zhanghai/MaterialFiles/assets/102638333/2e99150b-5f57-4fc7-b049-6fbe36c9e34a)

I believe this is a bug within the app and wanted to bring awareness to it.

**Comment by zhanghai** [comment]
Yes, definitely a bug in the path implementation.

**Comment by pinckpockett** [comment]
> Yes, definitely a bug in the path implementation.

Thank you for getting back to me on this.

**Comment by zhanghai** [comment]
Which version of Material Files are you using? This sounds highly similar to #810 but that has already been fixed more than one year ago, and I found that only because I checked the code which I thought would be missing the check for SFTP host but the check is there.

**Comment by zhanghai** [comment]
I also tried FTP servers on two different hosts with same authentication and path, because it's much easier for me to set up two FTP servers, and I didn't see the cannot-copy-over-itself error. The FTP path implementation is highly similar to that of SFTP so I assume the result should be the same as SFTP. I'm using the tip-of-tree debug build but I believe any released version in this year should have the fix in #810.

**Comment by zhanghai** [comment]
Closing for no response - I assume it's a duplicate of the already fixed issue.

**Comment by pinckpockett** [comment]
> Closing for no response - I assume it's a duplicate of the already fixed issue.

Sorry about that. I had an older version from github but updated it recently and it fixed the issue.

**Comment by pinckpockett** [comment]
If you could, please delete my issue so it won't clutter up your project.

**Comment by zhanghai** [comment]
> If you could, please delete my issue so it won't clutter up your project.

Don't worry about it, people file duplicate issues all the time, and I just mark them as duplicate.
