### ISSUE TITLE
添加teracloud的webdav服务器提示无效主机名

### ISSUE THREAD

**Issue by wha4up** [zhanghai/MaterialFiles#1209]
应用版本：1.7.1(36)
系统版本：安卓11
![IMG_20240423_095320](https://github.com/zhanghai/MaterialFiles/assets/30365126/4d42aa44-312b-4448-a4eb-7c3d99e44069)

**Comment by zhanghai** [comment]
拆开来填，主机名是 aki.teracloud.jp，路径是 /dav。
