### ISSUE TITLE
Allow accessing Bug Reports.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [zhanghai/MaterialFiles#1215]
As https://www.reddit.com/r/android_beta/comments/cq7fm1/comment/ewulta6/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button explains, this doesn't appear to be possible except via `com.android.documentsui` yet.

**Comment by zhanghai** [comment]
Yes, it's not possible in Material Files and you have to use DocumentsUI.

**Comment by zhanghai** [comment]
> > [#1215 (comment)](https://github.com/zhanghai/MaterialFiles/issues/1215#issuecomment-2083081915)
> 
> @zhanghai, I'm aware. That's why I request it. Do you mean that it's a limitation of AOSP? If so, do you know of a relevant issue at https://issuetracker.google.com/u/1/issues?q=status:open%20componentid:190923, or would be willing to file one?

Yes, it is limited by AOSP and likely intentional because bugreports may contain sensitive private information. I don't know a relevant issue and I'm personally fine with the current situation so I'm not going to file one myself.

**Comment by RokeJulianLockhart** [comment]
Seems like it might be worth following https://android.stackexchange.com/questions/249083/accessing-bug-reports-and-termux-storage-in-file-explorer#comment335117_249083 for a solution.

**Comment by zhanghai** [comment]
I'm not seeing a solution there. Apps can't open DocumentsUI to be granted access to that directory, and Files by Google also just opens DocumentsUI.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/zhanghai/MaterialFiles/issues/1215#issuecomment-2083215190

@zhanghai, yeah, that's why I said that it would be worth following - because when there's an answer, we'll be notified.
