### ISSUE TITLE
[libsyscall.so] Java_me_zhanghai_android_files_provider_linux_syscall_Syscall_readdir

### ISSUE THREAD

**Issue by axmediaplayer** [zhanghai/MaterialFiles#1232]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 1435 >>> ax.filemanager.android.files.fileexplorer.folder <<<

backtrace:
  #00  pc 0x0000000000021afc  /system/lib64/libc.so (abort+124)
  #01  pc 0x00000000000237b8  /system/lib64/libc.so (__fortify_fatal(char const*, ...)+120)
  #02  pc 0x00000000000239b0  /system/lib64/libc.so (readdir+208)
  #03  pc 0x00000000000074a8  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/lib/arm64/libsyscall.so (Java_me_zhanghai_android_files_provider_linux_syscall_Syscall_readdir+48) (BuildId: 7d116168fa8ca5a7f2a4b2b13c53ee90653ad9f3)
  #04  pc 0x0000000000051c94  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.odex (me.zhanghai.android.files.provider.linux.syscall.Syscall.getmntent [DEDUPED]+132)
  #05  pc 0x000000000055e788  /system/lib64/libart.so (art_quick_invoke_stub+584)
  #06  pc 0x00000000000cf940  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #07  pc 0x0000000000283e90  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
  #08  pc 0x000000000027de4c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+948)
  #09  pc 0x0000000000530fc8  /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
  #10  pc 0x0000000000554c14  /system/lib64/libart.so (ExecuteMterpImpl+29972)
  #11  pc 0x0000000000a4c580  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.vdex (fn.b.a+24)
  #12  pc 0x0000000000257948  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.4193613386)+496)
  #13  pc 0x000000000025d4c8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #14  pc 0x000000000027de30  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #15  pc 0x0000000000530fc8  /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
  #16  pc 0x0000000000554c14  /system/lib64/libart.so (ExecuteMterpImpl+29972)
  #17  pc 0x0000000000a4c49e  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.vdex (fn.b.hasNext+38)
  #18  pc 0x0000000000257948  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.4193613386)+496)
  #19  pc 0x000000000025d4c8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #20  pc 0x000000000027de30  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #21  pc 0x000000000052eef0  /system/lib64/libart.so (MterpInvokeInterface+1392)
  #22  pc 0x0000000000551094  /system/lib64/libart.so (ExecuteMterpImpl+14740)
  #23  pc 0x0000000000abc8e0  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.vdex (me.zhanghai.android.files.filelist.z1.o+44)
  #24  pc 0x0000000000257948  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.4193613386)+496)
  #25  pc 0x000000000025d4c8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #26  pc 0x000000000027de30  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #27  pc 0x0000000000530fc8  /system/lib64/libart.so (MterpInvokeVirtualQuick+584)
  #28  pc 0x0000000000554c14  /system/lib64/libart.so (ExecuteMterpImpl+29972)
  #29  pc 0x00000000006cd834  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.vdex (tk.a.i+16)
  #30  pc 0x0000000000257948  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.4193613386)+496)
  #31  pc 0x000000000025d4c8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #32  pc 0x000000000027de30  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #33  pc 0x000000000052eef0  /system/lib64/libart.so (MterpInvokeInterface+1392)
  #34  pc 0x0000000000551094  /system/lib64/libart.so (ExecuteMterpImpl+14740)
  #35  pc 0x0000000000585eae  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.vdex (jl.j0.run+214)
  #36  pc 0x0000000000257948  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.4193613386)+496)
  #37  pc 0x000000000025d4c8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
  #38  pc 0x000000000027de30  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
  #39  pc 0x000000000052eef0  /system/lib64/libart.so (MterpInvokeInterface+1392)
  #40  pc 0x0000000000551094  /system/lib64/libart.so (ExecuteMterpImpl+14740)
  #41  pc 0x0000000000675fce  /data/app/ax.filemanager.android.files.fileexplorer.folder-0uYKKGELEVUHCBmVU8PuWg==/oat/arm64/base.vdex (pl.a.run+186)
  #42  pc 0x0000000000257948  /system/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool) (.llvm.4193613386)+496)
  #43  pc 0x000000000051e6b8  /system/lib64/libart.so (artQuickToInterpreterBridge+1032)
  #44  pc 0x00000000005678fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
  #45  pc 0x000000000055e788  /system/lib64/libart.so (art_quick_invoke_stub+584)
  #46  pc 0x00000000000cf940  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #47  pc 0x0000000000464f20  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
  #48  pc 0x0000000000465fe8  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
  #49  pc 0x0000000000491360  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
  #50  pc 0x0000000000083824  /system/lib64/libc.so (__pthread_start(void*)+36)
  #51  pc 0x000000000002340c  /system/lib64/libc.so (__start_thread+68)

**Comment by zhanghai** [comment]
This `ax.filemanager.android.files.fileexplorer.folder` - is it open sourced under GPLv3 as required?

**Comment by axmediaplayer** [comment]
Solved it, thanks for the reply @zhanghai

**Comment by zhanghai** [comment]
@axmediaplayer Are you the developer of `ax.filemanager.android.files.fileexplorer.folder`? I couldn't find any open source information on either the [Play listing page](https://play.google.com/store/apps/details?id=ax.filemanager.android.files.fileexplorer.folder) or in the `About` page of the app, so it is clearly violating the GPLv3 license of this project. It is only okay to fork this project if you abide by GPLv3, so please do provide the source code of the app to your users..

**Comment by axmediaplayer** [comment]
Thank you
Hai Zhang I will update about this source code next Build
