### ISSUE TITLE
Rotating to landscape crashes the app while the app selection screen is open

### ISSUE THREAD

**Issue by Undearius** [zhanghai/MaterialFiles#1247]
After tapping on an image, a dialog will come up to select an app to open the image in (eg. Open with Photos, Material Files Image Viewer, Material Files Save As, etc.)
Switching to landscape by turning the device on its side while this dialog is open will cause the app to crash. This doesn't happen when going from landscape to portrait.

After crashing a few times, a popup says "Android System keeps stopping"

It seems to happen with pictures, videos, and PDFs.
.jpg
.png
.mp4
.webp
.pdf

Rotating while trying to open any other filetype works.

Google Pixel 6a
Android 14
Material Files 1.7.2 (37)

**Comment by zhanghai** [comment]
Since it says "Android System keeps stopping", it is the system app picker that is crashing and the app can fix a bug in the system.
