### ISSUE TITLE
Cannot add CalDAV (NextCloud)

### ISSUE THREAD

**Issue by McBaumwolle** [zhanghai/MaterialFiles#1250]
Hi there, 
I'm trying to set up my NextCloud files in the app and it seems like the path is breaking something. 

When I use the server URL (without `https://`) it simply says the following. 

![Screenshot_20240612-224702](https://github.com/zhanghai/MaterialFiles/assets/67203883/82d10cf3-79af-4bb8-93ad-d6ce362397c0)

And when I use the [recommended](https://docs.nextcloud.com/server/latest/user_manual/ro/files/access_webdav.html) NextCloud path for 3rd party apps it says this. 

![Screenshot_20240612-224746](https://github.com/zhanghai/MaterialFiles/assets/67203883/2011b110-5d64-481d-b2da-9d08b0723b54)

My (managed) NextCloud path looks like this `randomstring0123.nextcloud.hosting.zone` or  `https://randomstring0123.nextcloud.hosting.zone/remote.php/dav/files/username/`

Thanks!

**Comment by zhanghai** [comment]
Host should be `randomstring0123.nextcloud.hosting.zone`, path should be `/remote.php/dav/files/username/`, whereas protocol should be HTTPS but that's already the default.

**Comment by McBaumwolle** [comment]
Well thank you, now it worked!
