### ISSUE TITLE
Cannot access FTP Server on Local Network (530 Error)

### ISSUE THREAD

**Issue by Humorist2601** [zhanghai/MaterialFiles#1260]
Hello

Recently updated to version 1.7.3 but cannot use the FTP Server. When I try to connect it to my second profile it shows Authentication Error 530 while it works in version 1.7.2

Operating system is Graphene OS, Android 14

**Comment by zhanghai** [comment]
I was able to use my current debug build of 1.7.3 to start the FTP server in main user and connect to it via 127.0.0.1:2121 in work profile. I'm using OnePlus 12 OxygenOS Android 14. I can try the same thing with release build if necessary but I guess it will be the same 

In fact, there's no FTP server/client change between 1.7.2 and 1.7.3 - the tile fix is limited to tile related code, so I don't have a good idea why this is happening. 

Are you sure that this is related to the app update? Is it fixed if you downgrade to 1.7.2 and reproduced again if you upgrade to 1.7.3 again?

**Comment by Valdnet** [comment]
I confirm the problem with connecting via FTP version 1.7.3.

Unable to connect to the application client.

After reinstalling to version 1.7.2 it works fine.

App:
Android 12
Material Files 1.7.3

**Comment by zhanghai** [comment]
Someone I can reproduce this with release build. Looking into it and halting Play release. Thanks for reporting this issue.

**Comment by zhanghai** [comment]
Confirmed that this is a R8 issue because turning off R8 full mode fixed it. I've reported this at https://issuetracker.google.com/issues/349872492 and I'll have to wait for a fix there.

**Comment by zhanghai** [comment]
Thank you for your report. I ended up downgrading R8 so that I'm sure there's no other regressions, and I've released v1.7.4 just now.
