### ISSUE TITLE
【求助】编译无法通过，请求帮助

### ISSUE THREAD

**Issue by simon2077** [zhanghai/MaterialFiles#127]
大佬，你好。本人是一个Android新人，最近想自己练手做一个文件管理器，在网上搜索到您的开源软件，感觉很不错，于是下载下来想研究学习一下，但编译时报如下错误，请大佬支招，万分感谢。
	错误信息：Gradle sync failed: D:\BaiduNetdiskDownload\MaterialFiles-master\signing.properties (系统找不到指定的文件。) (2 m 56 s 105 ms)

**Comment by zhanghai** [comment]
See https://github.com/zhanghai/MaterialFiles/blob/master/signing.properties.example
