### ISSUE TITLE
打开iso时提示无文件

### ISSUE THREAD

**Issue by aslnfl** [zhanghai/MaterialFiles#1279]
打开iso时提示无文件
Archive.readNextHeader = 0

**Comment by aslnfl** [comment]
该iso存放的是蓝光电影.   我尝试压缩一个iso文件,可以浏览
如何支持浏览存储蓝光电影的iso文件

**Comment by aslnfl** [comment]
是UDF格式的iso不支持打开

**Comment by aslnfl** [comment]
[libarchive](https://github.com/libarchive/libarchive) 确实不支持UDF格式

**Comment by zhanghai** [comment]
是的，或许你可以尝试给 libarchive 贡献 UDF 格式支持。
