### ISSUE TITLE
[Critical] in-app open_cache leak

### ISSUE THREAD

**Issue by Feuerswut** [zhanghai/MaterialFiles#1299]
1. make a zip.
2. make a zip of a zip.
3. open zip and zip inside zip
4. press back
5. you can see the entire open_cache of this app, including password-unprotected files and files extracted from these encrypted archives, if they have been clicked

If you press back on a zip within a zip, you have to be taken back where the {file}.zip.zip was stored, you have to never ever be able to see all the contents of the open_cache, throw an error if you have to.

**Comment by zhanghai** [comment]
This is working as intended. You can always view `open_cache` by `Go to` with `/storage/emulated/0/Android/data/me.zhanghai.android.files/cache/open_cache` anyway. If you want to remove those files you should `Clear cache` for this app in system settings for this app.
