### ISSUE TITLE
当目录中有视频或音频文件在抓取媒体封面的时候会导致页面不停的刷新

### ISSUE THREAD

**Issue by cctomato03** [zhanghai/MaterialFiles#1301]
直到封面展示出来，当视频文件过大分析耗时较长的时候则可能卡死。

https://github.com/user-attachments/assets/63b13b4e-cd3c-47e1-a417-0c37fb58a215

下载源码调试发现是FileListLiveData对象会在这个过程中不断的调用onChangeObserved这个方法，该方法会使页面不断刷新，就导致了上图中所示的现场。

将onChangeObserved方法注释后页面就正常了，暂不清楚中该方法里面是做什么用的。

**Comment by zhanghai** [comment]
你这是什么远程文件系统吗？这个问题是远程文件系统一直在通知说目录内容有更新。

**Comment by cctomato03** [comment]
> 你这是什么远程文件系统吗？这个问题是远程文件系统一直在通知说目录内容有更新。

在Ubuntu上搭建的webdav，只有目录中有音视频文件会出现这个问题。onChangeObserved方法注释后好像也不影响使用。
