### ISSUE TITLE
incorrect sorting by size 

### ISSUE THREAD

**Issue by pyviw** [zhanghai/MaterialFiles#1305]
Folders that have been created by apps is showed as big size folders even when this folders is totally empty.

For example I have torrent manager app, when I instal the app , that app create a folder in Downloads directory.
But when sorting Downloads directory by size it show the folder that have been created by the app on The top even when this folder is empty.

**Comment by zhanghai** [comment]
Do you have a screenshot?

**Comment by pyviw** [comment]
All this Folders have been created automatically by the Apps in **Download** folder.

And I check if this problem in system files, and yes its also effect other parts.
for example gallery folders.

**App version:** _v1.7.4_
**Android version:** _12_
**App source:** _F-Droid_

![retouch_2024091320261742](https://github.com/user-attachments/assets/f49f7dd0-bed1-489a-ac19-48dfa2409017)
![Screenshot_20240913-202638_Material Files](https://github.com/user-attachments/assets/47992bef-00b9-491a-972d-642f1d27b3ea).

**Comment by zhanghai** [comment]
I see. The folders are not sorted by their contents, because it may take minutes to calculate the sizes of their contents. All folders themselves actually have the same size of 4KiB.

**Comment by pyviw** [comment]
I try to sort the Downloads directory by size for some cleanup.
But now two days the same state.

I was expecting :
Sort by size -> Folders first -> folders by size also

Thanks ❤️
