### ISSUE TITLE
Broken Material UI on pop-up windows

### ISSUE THREAD

**Issue by peternmuller** [zhanghai/MaterialFiles#1309]
When the pure black theme is enabled, Material UI design gets removed from pop-up windows. Everything can be seen in this screen record:
https://github.com/user-attachments/assets/39c52c7b-c51b-4f39-8cb3-8fba1fd33fa2

**Comment by zhanghai** [comment]
Thanks for reporting this, it is indeed a bug and it will be fixed in a future release. (Or you may get a CI buld now.)
