### ISSUE TITLE
LTO/IPO

### ISSUE THREAD

**Issue by peternmuller** [zhanghai/MaterialFiles#1314]
Any plans on adding LTO/IPO optimizations to further improve MaterialFiles smoothness and performance?

**Comment by zhanghai** [comment]
libarchive-android is already using LTO, whereas the syscall wrapper this app is using is simple enough so that I don't think there can be much optimizations.

**Comment by peternmuller** [comment]
I tried to add `-flto` flags in CMakeLists.txt and `-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON` argument in build.gradle but build failed. Maybe this would work for someone more experienced than you who would know how to fix errors, and optimize the whole MaterialFiles APK instead of just libarchive-android as you said.

**Comment by zhanghai** [comment]
See https://github.com/zhanghai/libarchive-android/blob/master/library/CMakeLists.txt for an example. But I'm assuming it won't help much with the small amount of native code in Material Files itself.
