### ISSUE TITLE
[Bug] Root check fails after changed su path in APatch

### ISSUE THREAD

**Issue by DerGoogler** [zhanghai/MaterialFiles#1315]
In APatch you can change the `su` path to something like `/system/bin/kp` bla bla..

But I think that this feature is really breaking and also cool for not being root detected. MMRL also fails the root check because it uses the same way Material Files does.

The `su` path is stored in `/data/adb/ap/su_path` but how to access this file without root?

Some references to speed up the issue:

- https://github.com/bmax121/APatch/blob/96c19b61efc20f5f8c4894d6d0663aa38d8c99c9/app/src/main/cpp/supercall.h#L213-L227
- https://github.com/bmax121/APatch/blob/96c19b61efc20f5f8c4894d6d0663aa38d8c99c9/app/src/main/cpp/apjni.cpp#L310-L324

**Comment by zhanghai** [comment]
Material Files uses `libsu` and I think you need to request [libsu](https://github.com/topjohnwu/libsu/) to support this.

**Comment by DerGoogler** [comment]
For root checks you use the su binary

https://github.com/zhanghai/MaterialFiles/blob/fdc6974e845d1af280a7503a111e611480687676/app/src/main/java/me/zhanghai/android/files/provider/root/LibSuFileServiceLauncher.kt#L47

@zhanghai
