### ISSUE TITLE
Fast scroll on large text in Text Editor

### ISSUE THREAD

**Issue by acroreiser** [zhanghai/MaterialFiles#132]
When user open large text file and (for example) want to move to end of file, he must rapidly and frequently swipe on the touchscreen. This is taints user experience.

![Screenshot_20190715-161919_Material_Files](https://user-images.githubusercontent.com/10716792/61219181-534d2b80-a71c-11e9-9028-c80438e3fc2e.png)

**Comment by zhanghai** [comment]
I agree it would be nice to have : ) Maybe also monospace fonts - just that I need more time as there are still so many other things to be implemented.

**Comment by zhanghai** [comment]
Done.
