### ISSUE TITLE
能否增加一下标签功能，方便文件的复制粘贴

### ISSUE THREAD

**Issue by vimbackground** [zhanghai/MaterialFiles#1335]
经常需要在不同的目录里复制移动文件，希望能方便的在两个目录间切换，目录标签页会是一个比较合适的方式。

现在需要在一个目录中复制文件后，再转到另一个目录下操作，再转到其它目录中，比较不方便。

**Comment by HereComesAKing** [comment]
该功能已实现，可以通过在右上角省略号中添加书签选项。然后可在左侧菜单中找到。
我使用的MaterialFiles版本为1.7.4(39)

**Comment by vimbackground** [comment]
> 该功能已实现，可以通过在右上角省略号中添加书签选项。然后可在左侧菜单中找到。 我使用的MaterialFiles版本为1.7.4(39)

这样也行，如果能像ES、RS那样，直接在上端或者左边的一次性点击标签切换更好，现在要点击至少两次鼠标、满屏找才能切换，稍微有些不方便。

不是什么很重要的需求，不忙的时候可以考虑一下：）
