### ISSUE TITLE
无法访问/Android/data目录

### ISSUE THREAD

**Issue by weizihao30** [zhanghai/MaterialFiles#1340]
应用无法访问/Android/data目录，希望可以获取/Android/data目录的访问权限，由于大多数app的数据现在都被强制放在/Android/data/com.xxx.xxx路径下面，所以能够访问/Android/data目录对于文件管理应用非常重要

**Comment by zhanghai** [comment]
最近版本的 Android 系统下普通应用已经不可能获得直接访问 Android/data 的权限了。
