### ISSUE TITLE
Shizuku intergation for Android/* folder access

### ISSUE THREAD

**Issue by MasterCraft6969** [zhanghai/MaterialFiles#1352]
I've seen that it's recommended to use Android/whatever as a mount and access it that way, but all it does is show the folders and not the files in them. AFAIK in Android 14, you can access Android/* with ADB. I used another file explorer (X-plore) that has shizuku permission integration, and it can access Android/* just fine with the files inside included.

**Comment by MasterCraft6969** [comment]
@zhanghai apologies for the notification this may give you. I'm going through my open issues and closing whatever I can. Any update to this, even if a no, would be appreciated so I can close the issue.

Happy holidays! :)

**Comment by zhanghai** [comment]
Not planned in the near future - anyone can create an app with a `DocumentsProvider` that exposes the directory while using Shizuku though.

**Comment by MasterCraft6969** [comment]
> Not planned in the near future - anyone can create an app with a `DocumentsProvider` that exposes the directory while using Shizuku though.

Alrighty, thank you for the response. I'll be closing this issue since it was answered.

Happy holidays! :)
