### ISSUE TITLE
Feature Request: Provide folder selection dialog with MaterialFiles

### ISSUE THREAD

**Issue by rainman74** [zhanghai/MaterialFiles#1360]
With the DocumentsUI you can also open a folder selection dialog that only shows folders that you can select.

Unfortunately, this indent cannot be opened with the current MaterialFiles app: ACTION_OPEN_DOCUMENT_TREE

Since many Android TV manufacturers no longer install the stock app, this addition would make sense.

**Comment by za006** [comment]
大佬好真好用当前版本

**Comment by zhanghai** [comment]
That's because Material Files itself isn't a `DocumentsProvider` yet - see #680.
