### ISSUE TITLE
Allow custom name for WebDav server

### ISSUE THREAD

**Issue by rhaschke** [zhanghai/MaterialFiles#1361]
The name of the WebDav-Server is auto-assembled as `<user name>@<host>/<path>`.
It would be nice if one could change that default name. For me, the user name is my (rather long) email address and I don't see the hostname in the overview anymore.

**Comment by zhanghai** [comment]
I think that's the fourth line in the settings of a WebDAV server.

**Comment by rhaschke** [comment]
Yes, there is a line, but I can't edit it!

**Comment by zhanghai** [comment]
The grey text is just placeholder, it will be replaced once you enter something.

**Comment by rhaschke** [comment]
I see. Unfortunately, for me, the text wasn't grey but black. Thus, I always tried to remove the "existing text" first.
Sorry for bothering you.
