### ISSUE TITLE
Material Files for WearOS

### ISSUE THREAD

**Issue by PH03N1X1000** [zhanghai/MaterialFiles#1362]
You guys have a wonderful app but you got one of the apps like yours removed from playstore which was File Explorer FTP Server by corproxy. This app was also same as yours but it was available on wearos which was simply awesome to work with so now since this is gone i am requesting you guys to make one like this for wearos i would be very thankful.

**Comment by zhanghai** [comment]
I didn't remove that, and I personally don't have time for Wear development right now.

**Comment by PH03N1X1000** [comment]
ok well thanks for your reply
