### ISSUE TITLE
Add SMB support

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#148]

**Comment by zhanghai** [comment]
https://github.com/google/samba-documents-provider

**Comment by linsui** [comment]
Would you please also consider adding SFTP, FTP, FTPS, NFS support? Thanks!

**Comment by ildar** [comment]
Why all these burdens? Do you really need that?
I suggest that cloud sync is much more useful these days. And it works with
separate apps, e.g. Nextcloud etc.

**Comment by zhanghai** [comment]
To people subscribed: Do you need SMB1 support? (SMB1 is deprecated and insecure)

**Comment by maverick74** [comment]
Not me. 
SMB1 is trash and should die sooner rather than later.

**Comment by anonimno1** [comment]
Up 1 for SMB support. SMB1 ist not needed.
I am using Amaze File Manager now because of SMB support. Want to switch to MF (Amaze got kicked out from F-Droid), but need SMB!

**Comment by 5t0rmr1d3r** [comment]
Smb/nfs would be nice.
Imho, no one should need Smb1 in an modern architecture...

**Comment by leopku** [comment]
Need samba too.
SMB v4 protocol was my current version.

**Comment by sergioad** [comment]
I also wish it had FTP and SMB support, I have an OG 2DS and I use FTP to transfer files

**Comment by zhanghai** [comment]
Seems done.

**Comment by tian2992** [comment]
Sorry, i cannot access SMB support from the fdroid repo
