### ISSUE TITLE
Add grid view

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#152]

**Comment by nicoursi** [comment]
Very important feature. If possible you could add more views.  Something like this (screenshot taken from ES File Explorer) 
![IMG_20191201_190010](https://user-images.githubusercontent.com/16888339/69918003-14223b80-146d-11ea-9e6d-a345c2a0ea78.jpg)

**Comment by opusforlife2** [comment]
If this is implemented, could the grid column size be made configurable? I mean being able to choose between 3, 4 or 5 columns, for example.

**Comment by dikasetyaprayogi** [comment]
thank you very much.

now im certain material files is the best foss android file manager.
