### ISSUE TITLE
Handle intent for creating file

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#153]

**Comment by J-Jamet** [comment]
I can help develop this functionality on my side when I have time and make a pull request unless you are already on it.

At the UI level, does it suit you if we add a fixed view at the bottom of the screen (as in the "File" application) with the same behavior as your "New file" dialog?

**Comment by zhanghai** [comment]
Please leave it to me - I'll figure out the UX. Currently there's an exsiting bottom bar for picking files, so I'm thinking of bending it to show a text field in the case of file creation.

By the way regarding the WebDAV support we once talked about, actually you can try to implement a `DocumentsProvider` for it, in a separate app, and it can be used by any file manager (even the system one). [google/samba-documents-provider](https://github.com/google/samba-documents-provider) is an example for this.

**Comment by zhanghai** [comment]
Note: This should also handle `Intent.ACTION_SEND`.
