### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#174]
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by esmoak** [comment]
Looks like this is now on F-Droid.
https://f-droid.org/app/me.zhanghai.android.files

Thanks for the great app.

**Comment by zhanghai** [comment]
Still blocked by https://gitlab.com/fdroid/fdroiddata/issues/1865

**Comment by zhanghai** [comment]
Opened #186 to track the wrong title.
