### ISSUE TITLE
Add bookmark from SAF

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#182]
I'm using Shelter. If I want to add bookmark for work profile I need to
1. Add external storage... 
2. Select Shelter directory from stock file manager. There will be a `10` directory on the sidebar.
2. Open it from this app.
3. Add it to bookmarke.
4. Rename it as `Shelter`

Is there any way to simplify this process? Thanks!

Though I can add bookmark but I can't access it again.

**Comment by zhanghai** [comment]
Introducing new UI flow complicates things for new users and might confuse them, so if this only needs to be done once I think it's better to just let Shelter users do it manually.

**Comment by linsui** [comment]
Thanks for your reply. The Shelter directory is shown as `10` in `Add external storage...` . Though I can add a bookmark for Shelter directory, I can't access it if I remove the `10` directory in `Add external storage...` . So could you support renaming an external storage item? Thanks!

**Comment by zhanghai** [comment]
Tracking in #195.
