### ISSUE TITLE
Endless scrolling in text editor

### ISSUE THREAD

**Issue by bezobid** [zhanghai/MaterialFiles#188]
### Way to reproduce
- open a text file in text editor
- scroll all the way to the bottom
- keep scrolling

### Existing behaviour
User is able to keep scrolling, even though the scrolling position indicator has reached the bottom.

### Expected bahaviour
Scrolling will stop at the end of the text file.

**Comment by zhanghai** [comment]
I cannot reproduce this locally with Beta 11. Could you please provide:

- Device name and Android version on which you encountered this issue
- App version you are using
- A text file that can help reproduce this?

**Comment by bezobid** [comment]
- Xiaomi Redmi Note 5 with LineageOS 16.0
- Beta 11 from F-droid
- The issue appears regardless of the size, format or contents of the file. Take this one for example: https://www.w3.org/TR/PNG/iso_8859-1.txt

By scrolling i mean swiping up and down. When i try scrolling by dragging the scroll bar, scrolling stops at the bottom (end of the text file) as expected.

The issue appears no matter if the virtual keyboard is shown or hidden. Tested with two different keyboards. And I have virtual navigation bar.

**Comment by zhanghai** [comment]
This seems to be only reproducible in release build, but not in debug build... I'll take a closer look.

**Comment by zhanghai** [comment]
Fixed, it's a ProGuard issue (see [zhanghai/AndroidFastScroll:v1.1.0](https://github.com/zhanghai/AndroidFastScroll/releases/tag/v1.1.0))

**Comment by bezobid** [comment]
Awesome, thanks @zhanghai !
