### ISSUE TITLE
Add WebDAV support

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#191]
- [Apache Jackrabbit WebDAV library](https://jackrabbit.apache.org/jcr/components/jackrabbit-webdav-library.html)
- [lookfirst/sardine](https://github.com/lookfirst/sardine)
- [bitfireAT/dav4jvm](https://github.com/bitfireAT/dav4jvm): [bitfireAT/davx5-ose](https://github.com/bitfireAT/davx5-ose)

- https://github.com/bitfireAT/davx5-ose/blob/dev-ose/app/src/main/kotlin/at/bitfire/davdroid/webdav/DavDocumentsProvider.kt
- https://github.com/miquels/webdavfs/blob/master/fuse.go
- https://web.archive.org/web/20220630195627/https://blog.sphere.chronosempire.org.uk/2012/11/21/webdav-and-the-http-patch-nightmare

**Comment by mister-monster** [comment]
This is the only feature for which I still use a proprietary file manager. Mounting remote filesystems is a must. Is there an ETA on this issue being implemented?

**Comment by zhanghai** [comment]
Will be the next bigger thing after SMB because more people are asking for it.

**Comment by MisterY** [comment]
Does this also include providing access to files through Storage Access Framework? Meaning, one could use SAF to access WebDAV through Material Files?

**Comment by zhanghai** [comment]
If SMB is implemented, other apps can use the file picker from this app to pick files on SMB (i.e., FileProvider). There isn't a plan for this app to provide a fully-featured DocumentsProvider though.

**Comment by MisterY** [comment]
Thanks for the clarification.

**Comment by alexanderadam** [comment]
> If SMB is implemented, other apps can use the file picker from this app to pick files on SMB (i.e., FileProvider). There isn't a plan for this app to provide a fully-featured DocumentsProvider though.

I'm not quite sure what exactly this means.
Will it be possible to explore a storage and to open a document (i.e. a PDF) work in MaterialFiles? :thinking:

**Comment by zhanghai** [comment]
Yes.

**Comment by qianyigengwu** [comment]
If Material Files can add webDAV support, I can continue to use KeePassDX happily.

**Comment by alexanderadam** [comment]
> If Material Files can add webDAV support, I can continue to use KeePassDX happily.

Can't you use [RCX (RClone)](https://f-droid.org/packages/io.github.x0b.rcx/)?

**Comment by crayqyxw** [comment]
> > If Material Files can add webDAV support, I can continue to use KeePassDX happily.
> 
> Can't you use [RCX (RClone)](https://f-droid.org/packages/io.github.x0b.rcx/)?

I haven't heard about this app before and thanks a lot about your advice.

**Comment by juxuanu** [comment]
Is there any progress on this?

**Comment by prg318** [comment]
Would love to see WebDAV support in MaterialFiles.  I mostly completely switched from FX to MaterialFiles, but I still use FX for its WebDAV support.

**Comment by prg318** [comment]
I wonder if Material Files could utilize DavX's WebDAV support?

When a WebDAV mount is configured in DavX, the share is available in the LineageOS default file browser ("Files" - `com.android.documentsui`).  I'm not sure what API is being used here, but it would be great if Material Files could integrate with that API and use WebDAV shares exposed by other applications like DavX.

Here's an older but still relevant demonstration of how DavX can provide a WebDAV share to the standard android file browser - https://www.youtube.com/watch?v=FwfwNXFtvYE

**Comment by TaivasJumala** [comment]
> Would love to see WebDAV support in MaterialFiles. I mostly completely switched from FX to MaterialFiles, but I still use FX for its WebDAV support.
> 
> EDIT: FYI: I just recently learned that you can access WebDAV mounts in Material Files by using DavX: https://www.youtube.com/watch?v=FwfwNXFtvYE

Thanks.

使用 DAVx⁵ 确实可以

**Comment by aguaviva** [comment]
> Is there any progress on this?

@juxuanu messages like this, unless you are contributing economically, get the opposite effect they get at work. A better approach is "how can I help to get XYZ happen?".

**Comment by zhanghai** [comment]
Please feel free to try out the latest master code, e.g. an APK from [here](https://github.com/zhanghai/MaterialFiles/actions/runs/8058108066).

**Comment by mysll** [comment]
> I've added WebDAV support and tested with one public test server.
> 
> Please feel free to try out the latest master code, e.g. an APK from [here](https://github.com/zhanghai/MaterialFiles/actions/runs/8058108066). Note that since it's mostly untested right now, please beware when using it for data not backed up.

webdav打开根目录正常,点击任何一个目录都提示:
![微信图片_20240306114750](https://github.com/zhanghai/MaterialFiles/assets/3783323/a428ca3e-e534-4fd8-85e6-11ec9bca2905)
我的环境是nginx proxy manager做的转发,使用其它几个支持webdav的都可以正常访问

**Comment by zhanghai** [comment]
@mysll 可以检查下 https://github.com/bitfireAT/davx5-ose/ 可以用吗？

这个 HTTPS 重定向到 HTTP 确实不太安全，可能被攻击者利用之类的

**Comment by mysll** [comment]
> @mysll 可以检查下 https://github.com/bitfireAT/davx5-ose/ 可以用吗？
> 
> 这个 HTTPS 重定向到 HTTP 确实不太安全，可能被攻击者利用之类的

davx5点开看不见文件夹里的内容,我这个环境是外部访问都是https->nginx->webdav nginx到webdav是走内网http
也就是说webdav返回的是http内部地址,但是http的连接是通不过我https->nginx那一步,访问还是要走外部https的链接,是不是应该文件夹的地址应该是用我设置的https://url+文件夹

**Comment by mysll** [comment]
> > @mysll 可以检查下 https://github.com/bitfireAT/davx5-ose/ 可以用吗？
> > 这个 HTTPS 重定向到 HTTP 确实不太安全，可能被攻击者利用之类的
> 
> davx5点开看不见文件夹里的内容,我这个环境是外部访问都是https->nginx->webdav nginx到webdav是走内网http 也就是说webdav返回的是http内部地址,但是http的连接是通不过我https->nginx那一步,访问还是要走外部https的链接,是不是应该文件夹的地址应该是用我设置的[https://url+文件夹](https://url+%E6%96%87%E4%BB%B6%E5%A4%B9)

不用处理了,我nginx里把地址重定向到https就解决了

**Comment by mysll** [comment]
> > > @mysll 可以检查下 https://github.com/bitfireAT/davx5-ose/ 可以用吗？
> > > 这个 HTTPS 重定向到 HTTP 确实不太安全，可能被攻击者利用之类的
> > 
> > 
> > davx5点开看不见文件夹里的内容,我这个环境是外部访问都是https->nginx->webdav nginx到webdav是走内网http 也就是说webdav返回的是http内部地址,但是http的连接是通不过我https->nginx那一步,访问还是要走外部https的链接,是不是应该文件夹的地址应该是用我设置的[https://url+文件夹](https://url+%E6%96%87%E4%BB%B6%E5%A4%B9)
> 
> 不用处理了,我nginx里把地址重定向到https就解决了

顺便说一句,这个子文件的访问地址是不是应该拼接起来呢,而不是用webdav返回的地址,应该用配置的协议+主机名+端口+文件夹的路径,其它几个能访问感觉是拼接的,所以不存在https和http的问题,因为http是不能通过我的nginx进行转发的

**Comment by aguaviva** [comment]
What servers is this webdav client known to work with?

**Comment by mysll** [comment]
> 按照 WebDAV 标准的话，服务器既然返回了地址就应该相信服务器。

写了个测试webdav客户端,看协议返回的目录都是相对路径,所以问题也不是地址拼接导致的,如果还有人一样的环境有同样的问题,那就改下nginx配置吧

**Comment by zhanghai** [comment]
> What servers is this webdav client known to work with?

I think any server that adheres to the WebDAV standard without bugs should work.

I personally tested `chezdav` and it has a server side bug when retrieving files. I also tested `rclone serve webdav` and it mostly worked.

I would be interested to know if Apache HTTP Server mod_dav and SabreDAV (IIRC NextCloud etc is using it) is working as well.

**Comment by morty303** [comment]
@zhanghai : can't connect to webdav. i copy webdav adress from hoster to filenanager and i get lways error.
