### ISSUE TITLE
[Feature Request] adding advanced settings for files compression

### ISSUE THREAD

**Issue by nicoursi** [zhanghai/MaterialFiles#193]
Adding the ability to password protect your archives with 7zip

Something like that:
![IMG_20191201_191648](https://user-images.githubusercontent.com/16888339/69918205-88f67500-146f-11ea-8a81-c723c0b8665f.jpg)

**Comment by zhanghai** [comment]
This app is just a file manager which uses Apache Commons Compress for basic archive operations, and adding advanced archive support like this will complicate the code and make it much harder to maintain. Power users might want to use a dedicated archive app.

**Comment by EchedeyLR** [comment]
Would be possible, at least, adding split capabilities?

Many online transferences as made spliting archives in small parts due to limits put in many online services and metered data. 

The general Cubans are examples of that.

**Comment by zhanghai** [comment]
Please get an archiver app for that - this is just a file manager.

**Comment by EchedeyLR** [comment]
As set in other answer, there is no FLOSS archiver for Android ^^;.

It is good you set that you have nothing to do with it and that you don't accept that kind of suggestions but, I would be preferable if you don't point people for that given the situation expressed in the sentence before.

**Comment by EchedeyLR** [comment]
If my message was not understood, I say that I understand "your app, your rules" as well as terms expressed in the own license about warranty, etc. 

I was only expressing my opinion about the way to set it and what you do additionally.
