### ISSUE TITLE
Add storage manager

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#195]

**Comment by riveravaldez** [comment]
Not sure if this goes here:

**Can't delete files on SD card**

Material Files 1.0.0
Android 6.0
kernel 3.10.49
LG-H735AR

Message on screen:

> **Error while deleting**
> There was an error deleting "file.extension".
> Cannot launch su shell, exit code: -3

Something similar happens trying to rename a file (always on an added SD card, in my case a SanDisk one).

Let me know if I should put this info in other place or add some other data.

Thanks a lot.

**Comment by zhanghai** [comment]
@riveravaldez Please file a separate bug for this. Meanwhile, do you have an internal emulated SD card? And how did you add the external SD card, by clicking "Add external storage...", or it is just there automatically? In the latter case, does adding it via the former approach work? (You can answer these questions in the new bug.)

**Comment by zhanghai** [comment]
Done.
