### ISSUE TITLE
Providing contents from external media (SAF) does not seem working

### ISSUE THREAD

**Issue by hurlebouc** [zhanghai/MaterialFiles#199]
Hello !
First great job for this program! I find it very simple and well designed.

I use it with Google Samba Document Provider, and it seems impossible to open media with external application. For instance, I can't open mp3 files with VLC from samba share.

**Comment by zhanghai** [comment]
Will take a look later.

**Comment by zhanghai** [comment]
What is your Android version? Does opening the file in VLC via system Files app (DocumentsUI) work? Does copying the file to sdcard within this app work?

**Comment by hurlebouc** [comment]
Hello,

I have android 9 on a Samsung A8. 

Yes i can open the file from normal file manager. And I can copy file locally. It is when i want to open the file in streaming from the app that there is a bug.

**Comment by zhanghai** [comment]
This should have been fixed by 365dd29.
