### ISSUE TITLE
Can't change package name

### ISSUE THREAD

**Issue by monikamishra-54** [zhanghai/MaterialFiles#206]
No implementation found for long filemanager.advance.best.provider.linux.syscall.Syscalls.opendir(filemanager.advance.best.provider.common.ByteString) (tried Java_filemanager_advance_.best_provider_linux_syscall_Syscalls_opendir and Java_filemanager_advance_.best_provider_linux_syscall_Syscalls_opendir__Lfilemanager_advancefilemanager_bestfilemanger_filemanagerapp_provider_common_ByteString_2)
2019-12-10 18:20:54.603 21215-21340/filemanager.advance.best.provider E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
Process: filemanager.advance.best.provider, PID: 21215

**Comment by zhanghai** [comment]
You are on your own if you try to change the code to do something weird (`filemanager.advance.best.provider`) 😅
