### ISSUE TITLE
Added storage volumes are read-only

### ISSUE THREAD

**Issue by akashpal-21** [zhanghai/MaterialFiles#208]
Added SD card via the add external storage option, the disk is only read only.

Surprisingly if i add a folder from the sd card, everything is accessible inside the folder.

Gives me an error code 
"Cannot launch su shell, error code -3"

**Comment by zhanghai** [comment]
"Cannot launch su shell, error code -3" is raised when the app gets a permission denial (EPERM) for file operations, and falls back to use root privileges.

Could you share:

- the Android version and app version you are using?
- the SD card configuration of your devcie, e.g. do you have an internal/emulated SD card? And is the SD card you added a removable one?

**Comment by zhanghai** [comment]
Never mind, found the issue. I'll try to fix it tonight.

**Comment by zhanghai** [comment]
Fixed in c81f380.
