### ISSUE TITLE
Use reproducible build on F-Droid to share the same signature with Play

### ISSUE THREAD

**Issue by proninyaroslav** [zhanghai/MaterialFiles#212]
Hi. It would be nice if all APKs were signed with the same key. This will allow install APK from third-party sources without uninstalling the previous version. For example, F-Droid uses its own key. F-Droid allows set your own key https://f-droid.org/en/docs/Reproducible_Builds/. For example, it can be placed in `metadata/me.zhanghai.android.files/signatures` directory in F-Droid Data repo.

**Comment by joshcangit** [comment]
Well, both can be installed or updated either way.

I've checked their policy which states they won't accept _proprietary trackers_ like Crashlytics and Firebase.
So that's why that one has trackers removed.
F-Droid won't accept it otherwise.

**Comment by zhanghai** [comment]
See also https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14163#note_1686405675 for when I tried reproducible build for Untracker.

**Comment by joshcangit** [comment]
In that case, will there still be anymore updates for the F-Droid version?
