### ISSUE TITLE
Add FTP client support

### ISSUE THREAD

**Issue by takase1121** [zhanghai/MaterialFiles#213]
It'll be cool if I am able to add a FTP server as an external location. It'll be even better if SFTP and optionally FTPS is supported (I don't really think people still use FTPS anymore so it may be fine to not support that)

**Comment by kineita** [comment]
Hope FTP is coming soon, thank you @zhanghai

**Comment by anedroid** [comment]
I also need this feature. There's a FTP server in MF. If you add a FTP client, it could be much easier to transfer files between two devices using MF.

**Comment by Valdnet** [comment]
I am also in favor of adding an FTP client for the Material Files application. This will allow a direct connection between the client and server through a single Material Files application.

Is there a problem to implement FTP for the client in the Material Files application?

**Comment by zhanghai** [comment]
Well, I didn't realize Chrome has remove FTP client support. I agree the feature can get more prioritization in this case.

**Comment by zhanghai** [comment]
Most of the functionality has been implemented in the master branch and remaining tasks are:

- [x] Investigate why FTP server in this app disconnects/crashes if switching between directories too fast: https://github.com/apache/mina-ftpserver/pull/11
- [ ] Investigate why `python -m pyftpdlib` connection may hang if switching between directories too fast - is it a client bug or a server bug?
- [ ] Add FTPS/FTPES support

**Comment by Valdnet** [comment]
@zhanghai Be sure to add new text strings to Transifex so that translators can translate them 😉.

**Comment by zhanghai** [comment]
I'm planning to upload them when I finish the feature - otherwise a lot of people will get notifications from me a bit too frequently.

**Comment by zhanghai** [comment]
FTP basically works now - you can even play video files (and jumping around different timestamps) on FTP without downloading the full file in advance.

**Comment by Valdnet** [comment]
> you can even play video files (and jump around different timestamps) on FTP without downloading the full file in advance.

Cool 👍. Very good job 😉.

I cannot wait for the new version of Material Files from FTP.

**Comment by zhanghai** [comment]
Feature completed. New strings have also been uploaded to Transifex.

**Comment by Valdnet** [comment]
I'm already doing the translation 😉.
