### ISSUE TITLE
FTP on tiles

### ISSUE THREAD

**Issue by Strikerlulu** [zhanghai/MaterialFiles#218]
The app is crashing when tried to turn on ftp server using the tile (without opening the app) if it can't run on background let it open the app and start it or atleast give a toast message....

**Comment by zhanghai** [comment]
What device and Android version are you using? Because I tested the tile before release on my OnePlus Android P and Emulator Q, both worked fine.

**Comment by Strikerlulu** [comment]
Android Q

**Comment by Strikerlulu** [comment]
The problem was with my os...got fixed on new update...

**Comment by zhanghai** [comment]
Fixed in c2b8fe2.
