### ISSUE TITLE
Readme and description to include the GNU GPL emblem

### ISSUE THREAD

**Issue by Wilker-a** [zhanghai/MaterialFiles#220]
hi :3

i've been thinking: as this program is not just open source but also [free software](https://www.gnu.org/philosophy/free-sw.html), and this is also licensed under the GNU GPL, i believe it would be nice to highlight that on the readme file and the store description \^\^

the license have an emblem under the public domain (png and svg), which you can find [here](https://www.gnu.org/graphics/license-logos.html).

![an example of the logo/emblem](https://www.gnu.org/graphics/gplv3-with-text-136x68.png)

what do you think? :3

**Comment by zhanghai** [comment]
Thanks for the suggestion, but the README already have a license badge.

![License](https://img.shields.io/github/license/zhanghai/MaterialFiles?color=blue)

**Comment by Wilker-a** [comment]
oh, thank you for remembering \^\^

###### (i am bad at seeing stuff sometimes lol)
