### ISSUE TITLE
SD Card Path & Videoplayback Lag

### ISSUE THREAD

**Issue by akashpal-21** [zhanghai/MaterialFiles#222]
Hi.
1. So, the file path to my SD card is
"document:content://com.android.externalstorage.documents/tree/C60F-FE0B%253A#/"
This causes some issues in some apps.

And 2. Media playbacks lags heavily if i play them from my SD card from this app.

Thanks, please look into it in your time.

**Comment by zhanghai** [comment]
Duplicate of #199.
