### ISSUE TITLE
Not all SAF providers displayed (eg. Termux is not)

### ISSUE THREAD

**Issue by chrysn** [zhanghai/MaterialFiles#223]
MaterialFiles (in version 1.0.1 as built by f-droid) fails to display some SAF media, in particular the data provided by termux.

For comparison, install termux and make any SAF provider known to work available (I've tried with nextcloud, but the easiest one is often an SD card).

In the native file manager, the storage options on the left panel side below "Documents" are the internal storage (indicated as the device model), the SD card (indicated as its file system name), and Termux.

MaterialFiles, in its side bar, shows Root, the internal storage (named "Internal shared storage), the SD card (by its file system name), but then only "Add external storage". The side bar of the folder picker opened by "Add external storage" only offers "Documents", the internal storage (indicated as the device model) and the SD card (by its file system name) but not Termux.

Is it possible that a certain flag (that indicates support for SAF) needs to be set on the "Add external storage" dialog? (I'm not really familiar with Android development, but I've seen similar behavior in development with Gtk where the "open" dialog needed an additional flag to allow selecting files accessible only through Gtk's "gvfs", which is that ecosystem's equivalent to SAF).

I've tested this on LineageOS 14.1 (Android version 7.1.2) on different devices.

**Comment by zhanghai** [comment]
IIRC `DocumentsProvider`s need to implement extra methods for them to appear in the picker, in addition to the minimal implementation to show it in system DocumentsUI. So if the other third-party file managers cannot show Termux in picker as well, it's probably something with the Termux `DocumentsProvider` implementation.

**Comment by chrysn** [comment]
Thanks for the feedback, and sorry for picking the wrong package here. [Re-reported at termux](https://github.com/termux/termux-app/issues/1424).
