### ISSUE TITLE
Request to make search case Insensitive

### ISSUE THREAD

**Issue by shashankholla** [zhanghai/MaterialFiles#224]
The search currently implemented is case sensitive which doesn't serve the purpose. Please make the searching case insensitive.

**Comment by Wilker-a** [comment]
case insensitive by default and case sensitive as an option should be good.

in addition to that, maybe including RegExp could serve for some purposes too? :3

**Comment by zhanghai** [comment]
Search will be case-insensitive in the next release - this is also what Nautilus implemented, and I missed that during initial implementation.

Advaced seach is tracked in #120.
