### ISSUE TITLE
Copy file to SAF error

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#225]
I'm using Shelter to manage work profile. It provide access to file system through SAF. When I try to copy file to work profile, e.g. `a.jpg` I get `a.jpg.null` . However there is no problem to copy file from work profile.

**Comment by zhanghai** [comment]
This is probably due to Shelter DocumentsProvider not correctly supporting creating file without a MIME type, which system DocumentsProvider has no issue with. You may want to open an issue there.

**Comment by linsui** [comment]
I get the same error when creating a new file. I guess you are right. Thanks!
