### ISSUE TITLE
Limited zip operation on external sdcard.

### ISSUE THREAD

**Issue by MikuDroid** [zhanghai/MaterialFiles#227]
I saw something related to external storage thingy at #195 . But I just wanna open new issue for this one. On internal storage, I can directly open zip and see what's inside the archive. Meanwhile on external sdcard I need to select extract (using another file manager, in this case my built in one, miui file manager). Also there's no extract button after pressing 3 dot menu.
![Screenshot_2020-01-29-01-24-50-595_android](https://user-images.githubusercontent.com/22476406/73293289-2da9ee80-4236-11ea-8fc2-05f1f0858797.jpg)

**Comment by zhanghai** [comment]
Unfortunately files on external SD card are served via system `DocumentsProvider`, but the archive reading libraries this app is using requires passing in a `java.io.File` in a lot of places, which isn't possible with `DocumentsProvider`. You may need a dedicated archiver app to support this.
