### ISSUE TITLE
First slow loading of folders with many photos, then no loading at all

### ISSUE THREAD

**Issue by EmilVogt** [zhanghai/MaterialFiles#228]
First, great app. I only accidentally found it and didn't know what I was missing.

I have one problem:
When opening the DCIM>Camera folder on my external sd-card with more than 1500 photos in the folder, I see a spinning wheel for more than 12 seconds. Then all photos are correctly shown. 
When returning with the back button to the previous folder and reentering the folder with the many photos for the second time, the spinning wheel spins for more than a minute and the photos are never shown. Only after opening the app again, I'm able to repeat the first step and load the pictures (with a delay of several seconds).

**Comment by zhanghai** [comment]
The loading time for 30000 files has been reduced from 32s to 7s.
