### ISSUE TITLE
[Feature request] Show more metadata

### ISSUE THREAD

**Issue by EmilVogt** [zhanghai/MaterialFiles#231]
Is it possible to show more metadata for .jpg, .pdf, .mp4, ...?
Like [exiftool](https://github.com/exiftool/exiftool)

What I found:
[https://github.com/drewnoakes/metadata-extractor](https://github.com/drewnoakes/metadata-extractor)
[https://github.com/adobe/XMP-Toolkit-SDK/](https://github.com/adobe/XMP-Toolkit-SDK/)
[https://github.com/apache/pdfbox](https://github.com/apache/pdfbox)

**Comment by zhanghai** [comment]
Duplicate of #47
