### ISSUE TITLE
Add theme color setting for Material Design 2

### ISSUE THREAD

**Issue by dedavlade** [zhanghai/MaterialFiles#237]
![Screenshot_20200219-003259](https://user-images.githubusercontent.com/17710777/74787594-d8e71a00-52af-11ea-9320-3fe04fafdec0.jpg)
![Screenshot_20200219-003303](https://user-images.githubusercontent.com/17710777/74787598-d97fb080-52af-11ea-919e-97e9843e25d4.jpg)

As of now we can only change the accent color for the original Material Design, I prefer using the MD2 layout, but I'd like to change the accent color to something other than "Google Blue".

**Comment by zhanghai** [comment]
Added in 859c49f.
