### ISSUE TITLE
[BUG] Inconsistenct App name

### ISSUE THREAD

**Issue by 0xlne** [zhanghai/MaterialFiles#239]
There seems to be an inconsistency in the file names.
In some launchers - the standard ones with icons, the app name is indeed "Material Files", but in others (like T-UI), the app name is "Zhanghai Files".

**Comment by zhanghai** [comment]
The app name is "Material Files", and the launcher activity name is simply "Files" ("Material Files" is too long and unnecessary).

I have no idea why anything would call my app "Zhanghai Files" though :/ It must be their own bug/"feature".
