### ISSUE TITLE
Help wanted: more testing before 1.0.2 release

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#241]
Hi all,

I'm planning to release version 1.0.2 this weekend, but couldn't test several things locally so your help would be appreciated. Specifically, I'm still not 100% confident with the following use cases:

- Using root access on Android 10.
- Playing video on an external SD card.
- Starting FTP from quick settings tile while the app wasn't in foreground for a long period of time.

Could anyone install [the APK file inside this ZIP](https://github.com/zhanghai/MaterialFiles/files/4239022/app-release.zip) and test for these use cases? The APK is Play signed so you can install over a Play version to confirm its authenticity. (I can't manually sign with F-Droid signature, sorry.) You can also find its changelog [here](https://github.com/zhanghai/MaterialFiles/blob/master/fastlane/metadata/android/en-US/changelogs/17.txt).

**Comment by ildar** [comment]
sorry just seen this request. Do you still need it?

**Comment by zhanghai** [comment]
Never mind, I released it on Play and so far everthing seems fine :)
