### ISSUE TITLE
Can't add External SD if no other file manager installed

### ISSUE THREAD

**Issue by jetta20162** [zhanghai/MaterialFiles#248]
The file manager requests a file search dialog from another (default) file manager to add an external SD card, if there is no other file manager present then i can't add an external SD card (tested on LineageOS 16, with default file manager disabled). It returns an error message that there is no app found for this action

**Comment by zhanghai** [comment]
External SD card access needs to be granted to this app via a system files app (DocumentsUI), so the app cannot add an external SD card if the system app isn't present or is disabled.

If you really can't enable DocumentsUI and have root access, you may be able to manually navigate to where the external SD card is mounted and add a bookmark for it.

**Comment by jetta20162** [comment]
Thanks for the clarification
