### ISSUE TITLE
Name field for new files not visible

### ISSUE THREAD

**Issue by draxaris1010** [zhanghai/MaterialFiles#250]
# steps to reproduce issue
1. Use a phone with a small screen
2. Use a keyboard that fills up almost all of the screen.
3. Create a new file.

When creating a new file on small screens the name field is not visible.
![screenshot](https://user-images.githubusercontent.com/4469895/76153433-cf67fb00-6080-11ea-9520-aee834db508c.png)

**Comment by draxaris1010** [comment]
Sorry about the long data url.

**Comment by Go-rom** [comment]
Hello, 

same issue when i want to rename a file.

Thanks for this great app btw

**Comment by linsui** [comment]
I can reproduce it on my Android 10 lineageOS 17.1.
![IMG_20200609_003918](https://user-images.githubusercontent.com/36977733/84057567-6cbd2d00-a9ea-11ea-89c4-7700f7a9e360.jpg)

**Comment by zhanghai** [comment]
Duplicate of #214.
