### ISSUE TITLE
[FR] open bookmark in a new window

### ISSUE THREAD

**Issue by ildar** [zhanghai/MaterialFiles#255]
either through a long-tap on a bookmark or add three-dot menu. Thanks!
Reason: getting a new window with desired location takes too many actions.

**Comment by zhanghai** [comment]
Long-clicking bookmark is opening the edit bookmark dialog now. Alternatively, you can open a new window and tap the bookmark, just one action away.

**Comment by ildar** [comment]
2 taps versus 4 taps: not a big deal.
Thanks again!
