### ISSUE TITLE
Add marquee option for file names

### ISSUE THREAD

**Issue by magiskliving** [zhanghai/MaterialFiles#261]
还有就是文件的大小计算好像有问题，不怎么准确啊

**Comment by zhanghai** [comment]
文件名分两行显示会导致列表中文件条目的高度不固定，难以实现快速滚动。相应地，你可以在文件属性中查看完整的文件名。

文件大小计算使用的是 Android 系统的 [Formatter.formatFileSize()](https://developer.android.com/reference/android/text/format/Formatter#formatFileSize(android.content.Context,%20long))，在 Android O 之前使用 1024 进位（KiB），在 Android O 之后使用 1000 进位（KB）。

**Comment by magiskliving** [comment]
可是，这个名称真的太短啦，字体又大，很多都被省略了，中间那些版本号什么之类的，最重要的都被省略了，真的没有什么折中的办法嘛。对于我们这种经常处理文件的真的非常不方便啊



---原始邮件---
发件人: "Hai Zhang"<notifications@github.com&gt;
发送时间: 2020年4月14日(周二) 下午4:19
收件人: "zhanghai/MaterialFiles"<MaterialFiles@noreply.github.com&gt;;
抄送: "mask"<1315749479@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhanghai/MaterialFiles] 建议文件名称过长时可以分两行显示 (#261)




 
文件名分两行显示会导致列表中文件条目的高度不固定，难以实现快速滚动。相应地，你可以在文件属性中查看完整的文件名。
 
文件大小计算使用的是 Android 系统的 Formatter.formatFileSize()，在 Android O 之前使用 1024 进位（KiB），在 Android O 之后使用 1000 进位（KB）。

**Comment by magiskliving** [comment]
啊啊 啊啊啊啊 作者大大,我有一个想法，您看可不可以让文件名过长的文件滚动起来这样可不可以。就是这样横着滚动过去,这样就可以看到后面的文件名称了。作者大大请务必解决这个问题啊，我真是太喜欢您这个软件了。拜托了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"神乐"<1315749479@qq.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上11:50
收件人:&nbsp;"zhanghai/MaterialFiles"<reply@reply.github.com&gt;;

主题:&nbsp;回复：[zhanghai/MaterialFiles] 建议文件名称过长时可以分两行显示 (#261)



可是，这个名称真的太短啦，字体又大，很多都被省略了，中间那些版本号什么之类的，最重要的都被省略了，真的没有什么折中的办法嘛。对于我们这种经常处理文件的真的非常不方便啊



---原始邮件---
发件人: "Hai Zhang"<notifications@github.com&gt;
发送时间: 2020年4月14日(周二) 下午4:19
收件人: "zhanghai/MaterialFiles"<MaterialFiles@noreply.github.com&gt;;
抄送: "mask"<1315749479@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zhanghai/MaterialFiles] 建议文件名称过长时可以分两行显示 (#261)




 
文件名分两行显示会导致列表中文件条目的高度不固定，难以实现快速滚动。相应地，你可以在文件属性中查看完整的文件名。
 
文件大小计算使用的是 Android 系统的 Formatter.formatFileSize()，在 Android O 之前使用 1024 进位（KiB），在 Android O 之后使用 1000 进位（KB）。

**Comment by zhanghai** [comment]
Sorry this has missed v1.1.0 i18n. Will be in the next next version.

**Comment by zhanghai** [comment]
Implemented in 3306753.
