### ISSUE TITLE
[FEATURE REQUEST] File Picker/DocumentUI

### ISSUE THREAD

**Issue by 0xlne** [zhanghai/MaterialFiles#264]
Material Files does not provide a DocumentsUI interface, meaning that for file picking activities from other apps, the Android-native DocumentsUI still needs to exist in parallel.
Some other file managers have this sought ability: example - MiXplorer

**Comment by zhanghai** [comment]
The app already handles `android.intent.action.OPEN_DOCUMENT` and `android.intent.action.GET_CONTENT`, and I've been using it to pick files for a while.
