### ISSUE TITLE
Use procfs to open content URIs for archive file

### ISSUE THREAD

**Issue by wb9688** [zhanghai/MaterialFiles#274]
I want to be able to open .zip files from other apps, i.e. an `Intent` with `VIEW` as action, `application/zip` as MIME type, and an URI starting with `content://`.

**Comment by zhanghai** [comment]
`ZipFile` requires a real `java.io.File`, however a content URI may not provide a physical file at all, so unless the underlying ZIP implementation is changed this can't be easily supported.

**Comment by wb9688** [comment]
Can't you do something like the following?

```java
ParcelFileDescriptor parcelFileDescriptor = context.getContentResolver().openFileDescriptor(uri, "r");
ZipFile zipFile = new ZipFile("/proc/self/fd/" + parcelFileDescriptor.detachFd())
```

You need to add null checks and catch exceptions obviously, but I think that should work, though that's still kind of an ugly hack imho.

**Comment by zhanghai** [comment]
Ah, yes, procfs might worth investigating.

**Comment by zhanghai** [comment]
Another way could be using linkat(), which is said to be able to create a path for an FD.

**Comment by zhanghai** [comment]
Solved with libarchive which doesn't require an FD.
