### ISSUE TITLE
File picker is broken - returns malformed URI

### ISSUE THREAD

**Issue by tguen** [zhanghai/MaterialFiles#281]
I have 2 file managers installed - this and Amaze. I use the following code to open a file picker in my app:
```
Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
intent.setType("*/*");
intent.addCategory(Intent.CATEGORY_OPENABLE);

try {
	startActivityForResult(Intent.createChooser(intent, "Select a file"), 1);
}
catch (android.content.ActivityNotFoundException e) {
	Toast.makeText(this, "No file picker available", Toast.LENGTH_LONG).show();
}
```

In `onActivityResult` I print the URI returned by the Intent with:
```
Uri uri = data.getData();
Log.d(TAG, "URI: " + uri.toString());
```

If I use Amaze to pick a file, it returns the correct URI: `file:///storage/emulated/0/Download/filename`

If I use this app, it returns a broken URI: `content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDownload%252Ffilename`

**Comment by zhanghai** [comment]
The only reason Amaze returned a file URI is that [the device is below Android N](https://github.com/TeamAmaze/AmazeFileManager/blob/72faf621d4cabb825f93e9b32f92422715b3250b/app/src/main/java/com/amaze/filemanager/utils/Utils.java#L222). On N and above, file URI is banned by the system and Amaze will also return a content URI.

The content URI returned by this app is a valid URI and not broken. The returned URI is opaque to the receiver and as long as they can read/write a file with it nothing is wrong. Whatever is put inside the URI only need to make sense to this app, which it does.
