### ISSUE TITLE
Allow to change the file size calculation

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [zhanghai/MaterialFiles#292]
Currently 1 Kilobyte = 1000 Bytes is taken.

Add an option where the file size calculation can be changed to: 1 Kilobyte = 1024 Bytes

### App Version

Material Files 1.1.1
https://github.com/zhanghai/MaterialFiles/releases/tag/v1.1.1

### Android Version

Android 9

**Comment by zhanghai** [comment]
Duplicate of #284.
