### ISSUE TITLE
New app name

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [zhanghai/MaterialFiles#294]
Is it possible that you could use a uniform app name?

Currently, it is called "Files" in English or "Fichiers" in French on Android home screen.

Can't you just use "Material Files"?

I find this name very beautiful and something unique.

**Comment by zhanghai** [comment]
I considered that during early developement as well. Although it's unique, it becomes too long and will be ellipsized on most people's phones, which will look bad :disappointed:

**Comment by ndnddkoeo3dkej9** [comment]
I have some solutions, what do you think? 🙂

You could do this:

- Material File 
 
- MaterialFiles

- MaterialFile

- add the second word as a second line

**Comment by zhanghai** [comment]
No, I think making the app name slightly incorrect is worse than just putting "Files" there. The in-app title also says "Files" so I think it's consistent to an extent.

**Comment by zhanghai** [comment]
The name in launcher has been renamed to "Material Files" due to the app being shipped as preinstalled in custom ROMs and confusing users.

**Comment by victorbnl** [comment]
In many launchers (Lawnchair v2 is one but I think in most of them) you can customise the application’s name so you could rename it “Files”.

**Comment by Wallby** [comment]
I actually completely agreed with keeping the app name as just Files. As now it is unreadable: Material ...
Another app (ReFra, previously called Gallery) added an option to configure the app name inside of the app in settings. Can this be added to this as well?
