### ISSUE TITLE
Sometimes it connect to external server

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [zhanghai/MaterialFiles#295]
Hello,

I just used the local file view and looked at the options and then the app just connected to that server without asking.

What is this?

`[2a00:1450:4001:815::2003]:443`

Can you change that or should it not be a local file manager app?

### App Version

Material Files 1.1.1
https://github.com/zhanghai/MaterialFiles/releases/tag/v1.1.1

### Android Version

Android 9

**Comment by zhanghai** [comment]
This is probably Firebase Anaylytics or Crashlytics, which is needed for me to understand how the app is doing, and get crash logs to fix bugs. For instance, it was critical for me to quickly release v1.1.1 which fixed several usability issues in v1.1.0 that I couldn't have discovered on my own.

The app is completely open source and I have nothing to hide, just that I need information to improve it, so I hope you could understand it. If you are still concerned about analytics and want to opt out of it, you can install the F-Droid version of this app, linked in README, which I configured to exclude all the analytics code and is built and signed by F-Droid from the source code here.

**Comment by ndnddkoeo3dkej9** [comment]
I know that the app needs to be restarted when this option is used. Can you add an option to disable Firebase Anaylytics (on/off)?

I don't like apps from F-Droid because updates are generally very slow and I think it's better if the original developer adds it.

**Comment by zhanghai** [comment]
Even if I turn it off, I cannot guarantee the closed-source binary I bundled from third-parties won't do anything unexpected, so I don't think it makes sense for people who are really concerned about privacy - in fact they shouldn't trust binary built by me as well, and should go to F-Droid for the version containing only open source code built and signed independently by F-Droid.
