### ISSUE TITLE
Multiple selection for Bookmark folders

### ISSUE THREAD

**Issue by ndnddkoeo3dkej9** [zhanghai/MaterialFiles#296]
There is no quick way to remove more than 50 folders from the bookmarks. The multiple selection function is generally missing.

The overview for the Bookmark folders in sidebar should also be improved. Maybe limit the entries or other solutions.

### App Version

Material Files 1.1.1
https://github.com/zhanghai/MaterialFiles/releases/tag/v1.1.1

### Android Version

Android 9

**Comment by ndnddkoeo3dkej9** [comment]
You could limit the sidebar to 10 entries and add an additional button where it automatically switches to: Settings -> Bookmark folders

**Comment by zhanghai** [comment]
You can clear app data if you really want to remove 50 bookmark directories quickly. I believe UI should be optimized for most users instead of a rare use case, and I need to prioritize my time for development.
