### ISSUE TITLE
[Feature Request] Manage ACTION_CREATE_DOCUMENT intent

### ISSUE THREAD

**Issue by J-Jamet** [zhanghai/MaterialFiles#299]
As main file manager, it would be nice to be able to create documents from an intention through the [SAF](https://developer.android.com/guide/topics/providers/document-provider) with [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT).

It would also be good to manage [ACTION_OPEN_DOCUMENT_TREE](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT_TREE). (Maybe in another issue)

[ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT) is OK!

Good refactoring job in Kotlin in any case. ;)

**Comment by zhanghai** [comment]
Duplicate of #153.

**Comment by J-Jamet** [comment]
Indeed, I had not seen, excuse me.
