### ISSUE TITLE
Renaming file in root error: Read-only file system

### ISSUE THREAD

**Issue by humblelion13** [zhanghai/MaterialFiles#300]
I set Root Access Mode to Prefer Root Access but still gives me error when renaming files in /etc:
![Screenshot_20200528-154227](https://user-images.githubusercontent.com/66051136/83115322-c6754b80-a0fc-11ea-9b14-b7c49c2a00eb.png)

**Comment by zhanghai** [comment]
Yes I think this is a bug because the rename operation isn't handling remounting file system. As a workaround for current version, you can try creating a file there and a dialog will appear where you can remount the file system into r/w.

**Comment by zhanghai** [comment]
Fixed in 3a8ca05 and will be released in the next version.
