### ISSUE TITLE
Bug：覆盖子文件夹中文件失败

### ISSUE THREAD

**Issue by ivysrono** [zhanghai/MaterialFiles#304]
Related：#207 
v1.1.1 from F-Droid

从甲文件夹复制全部到乙文件夹。
甲文件夹中包含文件和子文件夹如A，子文件夹中包含更多文件。
询问时选择合并已存在的文件夹，覆盖已存在的文件。
提示：
```
复制“A”时发生错误
将文件复制到“乙”时发生错误。
java8.nio.file.DirectoryNotEmptyException: 路径乙/A
```
如果单独复制A文件夹并选择覆盖内含文件，则不会有此报错。

**Comment by zhanghai** [comment]
无法重现这个错误。我用来测试的目录结构：

```
- 甲/
    - A/
        - 1
    - 2
- 乙/
    - A/
        - 1
    - 2
```
我将甲下的 A 和 2 选中后前往乙并粘贴，应用正确地提示了合并/覆盖文件，没有报告错误。

**Comment by zhanghai** [comment]
Reopening for another report.

**Comment by zhanghai** [comment]
Fixed in 6a2ce33.
