### ISSUE TITLE
Goes back to default directory

### ISSUE THREAD

**Issue by contrapunctus-1** [zhanghai/MaterialFiles#306]
If I switch away to another application, or open a file from Material Files and then tap Back to come back to it, Material Files opens with the default directory instead of the last directory open.

v1.1.1 from F-Droid, Android v9, Nokia 6.1, TA-1089

**Comment by zhanghai** [comment]
That usually means your system is over-aggressively killing apps that's not in the foreground. I cannot personally reproduce this and in fact never saw it during my daily usage.

**Comment by contrapunctus-1** [comment]
It is quite likely (see https://dontkillmyapp.com/nokia ) Can Material Files try to work around it (maybe warning the user, too), for situations like mine where the user cannot even disable these power savers?

**Comment by zhanghai** [comment]
I don't want to get involved into the endless battle of system killing apps and apps avoiding getting killed, especially when it's only done by certain misbehaving OEMs, because the code will be hacky and a burden for maintenance.
