### ISSUE TITLE
android.os.BadObjectException error

### ISSUE THREAD

**Issue by UltraBlackLinux** [zhanghai/MaterialFiles#308]
So when entering a specific folder, Im getting this error:

me.zhangha.android.files.provider.remote.RemoteFileSystemException: android.os.DeadObjectException: Transaction failed on small parcel; remote process propably died

What does this mean? How can I fix it?
Thank you for help!

**Comment by UltraBlackLinux** [comment]
hm - works now. seems like I had to many files in this folder.

**Comment by zhanghai** [comment]
It usually means the root process crashed somehow, and the relevant stacktrace in logcat will be helpful.
