### ISSUE TITLE
Text Viewer: Scroll position is reset to cursor position when (un)hiding the keyboard

### ISSUE THREAD

**Issue by SebiderSushi** [zhanghai/MaterialFiles#309]
This might be intentional but to me it came as a surprise. I expected my scroll position to stay whre i've manually put it instead of it scrolling to where i left (and maybe forgot) my cursor or where the app initialized it while opening a text file.

Is that intentional?
If yes, what was the intention behind it?

**Comment by zhanghai** [comment]
I believe this is Android framework behavior because I don't have such special handling in this app. The intention might be to show you the cursor so that you know where the letters/words you type will appear.

**Comment by SebiderSushi** [comment]
If it is android framework behavior, i think there might be a way to stop it by adding the correct option to the `android:configChanges=""` tag to the Manifest entry for the Text Editor activity.
(Of course, if that "correct option" exists.)

Do you want to keep the behavior?
I don't think it is beneficial, because it gets in the way if i hide the keyboard after scrolling my cursor out of the viewport, but if i pop up the keyboard again, i usually have to do this by pressing the text field. As a consequence, my cursor will be placed just where i tapped so there is no more need to navigate me to it...

**Comment by zhanghai** [comment]
`android:configChanges`

**Comment by zhanghai** [comment]
Made `EditText` preserve scroll location after re-measure (i.e. window size change).

**Comment by SebiderSushi** [comment]
Awesom thank you.
