### ISSUE TITLE
[Bug] When selecting and renaming a folder

### ISSUE THREAD

**Issue by vishalnandagopal** [zhanghai/MaterialFiles#310]
This is an extremely tiny/specific bug that probably won't affect anybody else. Its completely your wish whether you want to look into it.

1. Select a folder.

2. Click the 3 vertical dots beside the selected folder.

3. Rename the folder via the menu that pops out when you click the 3 vertical dots. Rename to something else.

4. The folder name changes. Now there is the text ' 1 selected' at the top. Even though the folder doesn't exist now.

5. Select any other folder or the renamed folder and it will show '2 selected' , when actually only one is.

6. Continue and select any number of folders by renaming it again and again.

Thanks for making such a neat, simple app.

**Comment by zhanghai** [comment]
Thanks! This bug is a kinda funny one. Fixed in 695ec10
.
