### ISSUE TITLE
[Bug] Alphabetical sorting is incorrect in some cases

### ISSUE THREAD

**Issue by theFireProjet** [zhanghai/MaterialFiles#313]
Files are sorted by name, ascending, in both cases. There is a discrepancy between the two cases that shouldn't be there. The file names are exactly the same by their letters from the alphabet. Only the capitalization is different. The first one is correct, the second isn't.

<img src="https://user-images.githubusercontent.com/61639215/85188019-4e85e580-b2a4-11ea-880a-fec06a27e939.jpg" var="Screenshot_20200620-030654_Material Files" width="240"> <img src="https://user-images.githubusercontent.com/61639215/85188021-504fa900-b2a4-11ea-8e56-555b12fc4fd1.jpg" var="Screenshot_20200620-030651_Material Files" width="240">

**Comment by zhanghai** [comment]
This is a known side effect in the sorting algorithm from GNOME Nautilus, which needs to support Unicode Collation Algorithm. I don't have a fix for this, but if one day you found that GNOME Nautilus has fixed it somehow please let me know.
