### ISSUE TITLE
Archive Add-on/plugin:

### ISSUE THREAD

**Issue by 1923-u** [zhanghai/MaterialFiles#315]
Hello, 
An open-source clone of https://play.google.com/store/apps/details?id=com.mixplorer.addon.archive is highly Essential, but please do not implement it natively, instead as an add-on.

**Comment by zhanghai** [comment]
This app already includes archive reading/creating ability with Apache CommonsCompress and JUnrar. Unlike MixPlorer, I don't have the plan/time to make this app a feature-rich archiver. But if I ever had the time, I'll do it in the app itself unless it adds a huge amount of binaries into the APK.

See also #107.
