### ISSUE TITLE
Establish a new orgnization and move this project into it

### ISSUE THREAD

**Issue by stevenleeS0ht** [zhanghai/MaterialFiles#316]
MaterialFiles is a very successful project. It is powerful, full-featured, modern-look.

But currently it is still a personal project.

There is a set of tools named [Simple Mobile Tools](https://www.simplemobiletools.com/), They are free and open source. But its drawback is as their name -- too simple.

The style of MaterialFiles is just fit some advanced user's demand. It can provide much more control and flexibility of device for user. 

It would be a good idea to firstly establish a ecosystem. All other (1. Material Design, 2. Full Featured Options and Functions) app can join in to this organization in the future.

And a project under a organization is much easier for new user to adopt then a personal project.

**Comment by zhanghai** [comment]
Glad to hear that you liked my app, but I don't have the time and energy to establish an entire ecosystem around it.
