### ISSUE TITLE
Cannot start app in new package name

### ISSUE THREAD

**Issue by giangmd** [zhanghai/MaterialFiles#319]
Hello guys,
I cloned from Github then rename to new package.
But start app in phone that app will be cracked with the error below:
`java.lang.RuntimeException: Unable to get provider com.abc.app.AppProvider: me.zhanghai.java.reflected.ReflectedException: java.lang.reflect.InvocationTargetException`
Could you help me on that issue?
Thank you so much!

**Comment by zhanghai** [comment]
Sorry but I don't provide support for forking this app.
