### ISSUE TITLE
Add SFTP support

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#325]
- [hierynomus/sshj](https://github.com/hierynomus/sshj)
- [jsch](http://www.jcraft.com/jsch/)

**Comment by orogenic** [comment]
this is to implement sftp server or client? i want to login to external sftp server and download files. is there an issue for sftp client?

**Comment by zhanghai** [comment]
This is the issue for the client. I don't have a plan for SFTP server (yet).

**Comment by Beanow** [comment]
Hopefully it's also feasible to implement more advanced ssh options, such as ProxyCommand and per-host port/user/identities.
Obviously it's less common, but that's also why I haven't found an open source android client I used without a VPN.

On my desktop I typically have a lot of this stored in `~/.ssh/config`
For inspiration a typical setup you could hide behind `sftp://dest`:

```
Host dest
  HostName 10.26.0.5
  User fileshare
  Port 4321
  ProxyCommand ssh bastion -s proxy:%h:%p@leaf-cluster
  IdentitiesOnly yes
  IdentityFile /keez/fileshare

Host bastion
  HostName bastion.example.com
  Port 5432
  User bastion-nologin
  IdentitiesOnly yes
  IdentityFile /keez/bastion
```

Ideally these could use both public keys and certificates! (Passwords are so 2020)

**Comment by zhanghai** [comment]
The `ProxyCommand` might be possible with https://github.com/hierynomus/sshj/pull/511 , but I'm not seeing how this app can run your SSH command `ssh bastion -s proxy:%h:%p@leaf-cluster` - this app doesn't provide a native SSH binary and doesn't have the environement to execute such a binary. On the otherhand, somehow parsing the SSH config file is also way too complex.

**Comment by zhanghai** [comment]
Tested with a local SSH server and file operation worked fine, so closing as fixed.

**Comment by Fellhahn** [comment]
Sorry I'm confused, I can't see a way to add an SFTP external storage in the app. I'm running 1.2.1 installed from F-Droid.

Is this implemented or still coming in a future release?

**Comment by Fellhahn** [comment]
Ah, sorry I just noticed that the issue closure is only 11 hours old :hand_over_mouth:  :grin:

**Comment by Beanow** [comment]
@zhanghai thanks for investigating. I do realize the app model here really hamstrings configurations like this. And of course not expecting command line shells to be a thing. If only userland virtual filesystem mounts were available right? I'm afraid the golden app I'm looking for (open source, solid UI, supporting modern security practices) still doesn't exist and I'm simply not comfortable using public SSH servers with gimped security for the convenience.

Anyhow, as a sidenote. I noticed you've linked pure-java implementations, possibly targeting the NDK would make for more options.

**Comment by MountainX** [comment]
> Sorry I'm confused, I can't see a way to add an SFTP external storage in the app. I'm running 1.2.1 installed from F-Droid.
> 
> Is this implemented or still coming in a future release?

It is working for me in the current app from F-Droid. The option is under the hamburger menu.

**Comment by andretiagogr** [comment]
You have to click "Add Storage"

Oct 12, 2021 4:38:12 AM sergio ***@***.***>:

**Comment by 532910** [comment]
Indeed. `FTP server` confuses.
