### ISSUE TITLE
Recover album images from more audio file formats

### ISSUE THREAD

**Issue by Wilker-a** [zhanghai/MaterialFiles#329]
![A screenshot of a folder with a couple of Vorbis audio files](https://user-images.githubusercontent.com/10854855/87881951-57292300-c9ec-11ea-8d7c-ce7bacf16291.png)

the file manager currently only gathers the album image files from .mp3 files, but it would be nice to have it also gather images from other formats such as .ogg to visualize in the file lists. :3

**Comment by zhanghai** [comment]
The album art for media files is coming from Android framework's `MediaMetadataRetriever`, backed by stagefright. Extracting images unsupported by the framework will require bundling one's own media decoder with the app, which will significantly increase APK size, and a lot of coding as well, so I don't have a plan for supporting this.

**Comment by Wilker-a** [comment]
understandable. thanks for explaining \^\^
