### ISSUE TITLE
Multi window support for Material Files

### ISSUE THREAD

**Issue by SGNight** [zhanghai/MaterialFiles#342]
Hi ! thank you for the wonderful app.
if you can add multiwindow support it'd be great.

![image](https://user-images.githubusercontent.com/62793442/88452085-6d663180-ce79-11ea-9166-2474e6e4edcd.png)

**Comment by zhanghai** [comment]
This is already provided by Android itself. Please update your system if it's too old.

![Screenshot_20200725-122329](https://user-images.githubusercontent.com/4469895/88464710-c29e4500-ce71-11ea-98c8-d1d3f7b39481.jpg)
