### ISSUE TITLE
Extracting files from archives discards their mtime

### ISSUE THREAD

**Issue by SebiderSushi** [zhanghai/MaterialFiles#346]
android version: LineageOS 15.1 (android 8.1.0)
device: Xiaomi Redmi 4X
Material Files version: 1.1.2 (20) from F-Droid

## Expected behavior
When extracting files from a supported archive which is storing the modification times of files, Material Files should ensure that this modification time will be applied to the extracted file

## Observed behavior
When extracting files from an archive (tested `zip` & `tar`) using Material Files, the modification time of the extracted files is set to the time of extraction.

**Comment by zhanghai** [comment]
Thanks for finding this bug! I also noticed this one recently and it has been fixed in f84d644. I tested locally that extracting from a ZIP file indeed preserves its modified time now, and the fix will be available in the next release.

**Comment by SebiderSushi** [comment]
Thank you, very cool!
I'll make sure to test this a lot once the update reaches F-Droid :D
