### ISSUE TITLE
The app doesn't provide a full filepath (according to Markor)?

### ISSUE THREAD

**Issue by 07416** [zhanghai/MaterialFiles#350]
[Markor](https://github.com/gsantner/markor) can't open text files via Material Files, states that the document is either not stored locally or from a file manager which doesn't support full paths.

Is this an issue with Markor or something which can be improved in ML to increase compatibility?

**Comment by zhanghai** [comment]
MaterialFiles implements the `FileProvider` properly, and no app should require a full file path. After all, the file could be a file on network storage (e.g. SMB), which won't have a path that makes sense to Markor because there is no standard on how one should represent such a path.
