### ISSUE TITLE
[Feature request]Customize floating "create folder/file icon"

### ISSUE THREAD

**Issue by Mitia99** [zhanghai/MaterialFiles#351]
Could you add the option to customize the floating "create file/folder" please.Thanks
Customization requirements:
_Hide(integrate "create file/folder" in top 3 dots)
_Change action(e.g Replace it with search and remove the search icon on top bar)
![AddText_08-05-04.41.56.jpg](https://user-images.githubusercontent.com/56766778/89419859-396cf500-d732-11ea-80a4-62104fb07474.jpg)![AddText_08-06-08.00.45.jpg](https://user-images.githubusercontent.com/56766778/89492819-c9eb1a00-d7b2-11ea-8cd2-27b593821b36.jpg)

**Comment by zhanghai** [comment]
No, I personally don't like the proposed new design here.
