### ISSUE TITLE
[Feature request) Dual Sidepane view

### ISSUE THREAD

**Issue by dhammel** [zhanghai/MaterialFiles#352]
Hello,

I was hoping to see a dual sidepane view, in other words being able to swipe from right to left and vice versa to go between 2 different area of directories, which really makes multi tasking much easier. Feature is what proprietary app Solid Explorer has, and its hard to get used to a new file manager without it. 

Would this feature be considered?

Thank you :)

**Comment by zhanghai** [comment]
Duplicate of #181
