### ISSUE TITLE
允许用户自定义标准文件夹的路径

### ISSUE THREAD

**Issue by abrahamxf** [zhanghai/MaterialFiles#353]
能否允许用户自行设定“相片”、“下载”、“电影”等“标准文件夹”的路径，因为部分中国手机厂家会对他们rom中的照片等的默认储存路径进行修改。

**Comment by zhanghai** [comment]
标准文件夹的路径来自系统 API [`Environment.DIRECTORY_DOWNLOADS`](https://developer.android.com/reference/android/os/Environment#DIRECTORY_DOWNLOADS) 等等，如果厂商真的修改了路径，他们很应该同时更正这个 API 的实现；否则这个魔改就过于离谱了，也不值得专门支持（大量的魔改支持会让项目难以维护）。作为用户，你依然可以隐藏标准文件夹，然后给相应的文件夹加上书签；或者更换一个实现合理的手机。
