### ISSUE TITLE
Add icon for .torrent files and .iso files

### ISSUE THREAD

**Issue by blackCauldron7** [zhanghai/MaterialFiles#360]

**Comment by zhanghai** [comment]
This app only have vector icons from AOSP source code for things like documents, audio, video, etc, but not torrent or ISO files. New icons requires design effort and consistency with the existing Material Design standards. If we take new file icons, it is also hard to mandate a standard for inclusion, and coordinate the priority for creating/fixing them, so I'd rather just leave them as is and give more focus to other features.
