### ISSUE TITLE
FTP not working properly

### ISSUE THREAD

**Issue by materialfilesquestion** [zhanghai/MaterialFiles#362]
Hello, I have an issue with FTP transfers.
I set up everything correctly, start the FTP server, login properly but then I'm locked out of every action.
If I try to for example open a folder, I double click and nothing happens.
I have the writings enabled, set all the permissions (I'm on MIUI 12) but no luck.
I can transfer everything correctly with the app FTP Server (free) always on F-Droid, so I'm baffled.
Any help is appreciated as I would like to have FTP on Material Files since I like the app more

**Comment by zhanghai** [comment]
I re-downloaded the Play version of this app on Android 10, and started its FTP server with either anonymous mode, or password mode (all digits). Both was accessible using Chrome on my desktop with the FTP URL shown in app UI, and I was able to enter directories or download files.

Could you try exactly these steps, and if it doesn't work, upload the logcat output here?

**Comment by materialfilesquestion** [comment]
on further analysis, this seems to be an issue with FileZilla. On Chrome I can access the FTP and download files, but can I upload them? 
Why does this happen though? With the other app, FileZilla can access and down/upload everything, while with Files I can only manage to download
Is this intended?
Thank you for your answer Hai, I am using the F-Droid version by the way

**Comment by Yird1** [comment]
I have the same problem too, I use WinSCP and it either won't let me into any folders, or will just bring me to a broken folder. (Using the F-Droid Version)

![Error](https://user-images.githubusercontent.com/67247581/91226595-1b176b00-e6da-11ea-823e-b906242286ee.gif)

**Comment by PrSunflower** [comment]
In my case both Firefox/Microsoft Edge and FileZilla Client were able to download files from the FTP server.

However only the root directory can be accessed and if I try to open a child directory the FTP server responds `550 No such directory.`. Same question, is this intended?

**Comment by KryptonicDragon** [comment]
I'm having the same issue when using Filezilla to connect to the server. 
I cannot cwd into a directory. Uploading and downloading files works fine.
Android 10
Filezilla v3.50.0
Material Files v1.1.2 (20)

**Comment by zhanghai** [comment]
Tested with FileZilla on Linux and will be fixed in the next release.

**Comment by PrSunflower** [comment]
Thank you @zhanghai ! Keep it up!
