### ISSUE TITLE
Add: Show creation time for folders and files

### ISSUE THREAD

**Issue by lo9-u** [zhanghai/MaterialFiles#364]
**Description**
In Material Files, Last Modified is currently only displayed for folders and files under "Properties".

Creation time is not displayed. Support is missing.

**Steps to reproduce**
1. Open Material Files
2. Select a folder or file
3. Tap on "Properties"
4. It only shows "Last modified"

**Android version**
Android 9 and Android 10

**App version**
Material Files (1.1.2)

**root**
No

**Aditional information**
Here is the Android documentation to add it to Material Files.
https://developer.android.com/reference/java/nio/file/attribute/BasicFileAttributes#creationTime()

**Comment by zhanghai** [comment]
See #365.
