### ISSUE TITLE
Add: Show last access time for folders and files

### ISSUE THREAD

**Issue by lo9-u** [zhanghai/MaterialFiles#365]
**Description**
In Material Files, Last Modified is currently only displayed for folders and files under "Properties".

Last access time is not displayed. Support is missing.

**Steps to reproduce**
1. Open Material Files
2. Select a folder or file
3. Tap on "Properties"
4. It only shows "Last modified"

**Android version**
Android 9 and Android 10

**App version**
Material Files (1.1.2)

**root**
No

**Aditional information**
Here is the Android documentation to add it to Material Files.
https://developer.android.com/reference/java/nio/file/attribute/BasicFileAttributes#lastAccessTime()

**Comment by zhanghai** [comment]
I believe most if not all users only needs to see the last modified time, which is what most other apps are doing (e.g. AOSP DocumentsUI, Solid explorer, Mixplorer, Amaze, etc). The UI space on phones is a limited resource and showing another two datetimes will consume more of it while unnecessarily confusing users. Futhermore, not all file systems on Android supports atime and ctime, and even if it's "supported" it might be inaccurate.

If you really want to view the other two times, you can always launch a shell and view them with `ls` or `stat`.

**Comment by lo9-u** [comment]
How is this to be understood exactly? Closing this github report is too fast and without considering the future development in the Android world.

The main reason not to add it is because of the UI space on phones.

But the reason is obsolete, because there are already very large Android phones or add in "Properties" scroll function.

And what about Android tablet users or Android desktop mode, there is plenty of UI space here. Not to forget Android foldable phones in the future. 

In the future, most Android devices will use current file systems and Android version (probably next year or in the next 2 or 3 years), because there is big change in Android 11.

If it's inaccurate, why do you recommend a command solution? Is a command solution more accurate? Also a command solution is not a user-friendly solution and requires an additional terminal app on the Android device.
