### ISSUE TITLE
Returns false path

### ISSUE THREAD

**Issue by mrghosti3** [zhanghai/MaterialFiles#368]
When you choosing a file/folder it returns the path with "/" replaced with %252F.

Ex:
```
/storage/emulated/0/Download

content://me.zhanghai.android.files.file_provider/file%253A%252F%252F%252Fstorage%252Femulated%252F0%252FDownload%252F
```

**Comment by zhanghai** [comment]
This is not a path, but a content URI, and it can be anything (e.g. just numbers) as long as opening it gives the file content.
