### ISSUE TITLE
Zip files labeled wrong - magisk wont flash

### ISSUE THREAD

**Issue by UltraBlackLinux** [zhanghai/MaterialFiles#375]
Hey there,
I created an issue at magisk a little while back, where I asked, why all the zips I tried to flash with this apps file selector were grayed out, just as every other file - they told me:

> That likely comes from your default file explorer not correctly labeling those files as zips (even though they have the correct extension). Try a different explorer, and you can also try moving the files to a different location before opening in the Manager (that's worked for others).

Please fix this,
Thanks!

**Comment by zhanghai** [comment]
What do you mean? Could you attach a screenshot?

**Comment by ildar** [comment]
sounds weird. Could you please give the issue reference?

**Comment by UltraBlackLinux** [comment]
@ildar https://github.com/topjohnwu/Magisk/issues/3125
@zhanghai ![Screenshot_20200930-113457_Material_Files](https://user-images.githubusercontent.com/62404294/94669041-0a799680-0311-11eb-909b-24b82a7d2c9f.png)

**Comment by zhanghai** [comment]
Thanks for reporting this issue! It has been fixed and tested locally with MagiskManager - the fix will be available in the next release.
