### ISSUE TITLE
Bug: Don't allow space characters (" ") at the end of a filename

### ISSUE THREAD

**Issue by PrSunflower** [zhanghai/MaterialFiles#377]
### Problem

Hi, I have just discovered that when creating a folder with Material Files it let me write `User screenshots `  (notice the space at the end). I was syncing this folder with Syncthing on Windows and because the last character was a space (` `) Windows would refuse to sync it saying "Invalid filename".

### Solution

When creating a new folder/file, automatically remove space characters at the end of the name. <br>
Example: In my case autocorrect `User screenshots ` to `User screenshots`

**Comment by zhanghai** [comment]
It would be strange if space is only removed at the end of the name, but not the beginning. Meanwhile, it's perfectly fine for a space character to be anywhere in a file name, including the beginning and the end, so I'm not planning to add a restriction to this.

**Comment by PrSunflower** [comment]
@zhanghai Thanks for replying. I had a problem because of a space at the end, but if you decide to implement an autocorrect feature also deleting spaces at the beginning would be logic.

Ok, as you want. I only know that this is what caused the problem when syncing from Android/Linux to Windows. Deleting the space character at the end solved the "Invalid filename" error on Windows.

**Comment by PrSunflower** [comment]
Hi @zhanghai , are you sure you don't want to add this fix? 😅

It seems that Windows doesn't accept "trailing spaces" as they are called and it was a pain in the neck for me to remove the faulty folder:

```
rd /s "D:\Documents\Syncthing\screenshots "
D:\Documents\Syncthing\screenshots , Are you sure (Y/N)? y
The system cannot find the file specified.
```

Same error when using the GUI, this caused strange errors in Windows Explorer... 

Fortunately [I was not the only one to have this problem](https://stackoverflow.com/a/4123173). I had to input a special command in the Windows Command Prompt to correctly delete the faulty folder:

```
rd /s "\\?\D:\Documents\Syncthing\screenshots "
\\?\D:\Documents\Syncthing\screenshots , Are you sure (Y/N)? y
```

In case I create another folder with a trailing space in **Material Files**, it would be REALLY nice if it removed the trailing space automatically.

**Comment by zhanghai** [comment]
Well, while Windows may not handle spaces properly, the stock Android Files app (DocumentsUI) do allow you to create folders with spaces around the name. Files Go automatically trims on creation but allows it in rename, a discrepancy in behavior. Amaze allows while Solid silently trims. On desktop, Nautilus silently trims. So yes, maybe we can reopen this for consideration.

**Comment by PrSunflower** [comment]
@zhanghai Thanks a lot for considering this issue. 

Like you I am also in love with free software and I've heard that GNU/Linux systems are much more robust than Windows, so if I was to choose a computer for everyone in the world it would be a Linux 😆   <br>
But most computers in the world, either home or work PCs, run on Windows so in my opinion it is a good thing to consider seamless cross-platform workflows.
