### ISSUE TITLE
Missing Thumbnails in EDS lite Volumes

### ISSUE THREAD

**Issue by locuturus** [zhanghai/MaterialFiles#378]
The SAF-based add external storage function allows me to add EDS lite encrypted volumes (that app creates a content provider).  Your built in file viewer opens these encrypted images just fine and I can do file operations on the volume.  But no thumbnails are generated.  I tried turning on the option for remote thumbnails but that didn't help.

The app "File Manager" on F-Droid by axet can create thumbnails so there may be some insight there.

**Comment by zhanghai** [comment]
This should share the same underlying issue with #545. Plesae try turning on the option for remote thumbnails in the next version.
