### ISSUE TITLE
Are shourcut icons adaptive?

### ISSUE THREAD

**Issue by 532910** [zhanghai/MaterialFiles#379]
It doesn't look like adaptive:
![image](https://user-images.githubusercontent.com/14617699/96518648-012a7c80-1274-11eb-812c-1c9fbbe049fd.png)

Known apps with adaptive shortcut icons:
[Element](https://github.com/vector-im/element-android), [Orgzly](https://github.com/orgzly/orgzly-android), [Calendar](https://github.com/LineageOS/android_packages_apps_Etar), [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger), SoundCloud
![image](https://user-images.githubusercontent.com/14617699/96517260-4ef1b580-1271-11eb-8723-448ca6413dc2.png)

All of these shortcuts are created the same way, via long press from the main icon and dragging it to the desktop.

**Comment by zhanghai** [comment]
Being able to take the same shape clearly shows that it's adaptive.

**Comment by 532910** [comment]
Comparing with the main MaterialFiles icon, it has a bigger gaps and a different style.

![image](https://user-images.githubusercontent.com/14617699/96575583-9875eb00-12d9-11eb-8025-cbd90c42272d.png)

**Comment by zhanghai** [comment]
Yes, because it's a shortcut icon, not an app icon. I tried to match the size of Google apps' (e.g. Maps') shortcut icon size.
