### ISSUE TITLE
Ability to move files and folders to other folders

### ISSUE THREAD

**Issue by nekohayo** [zhanghai/MaterialFiles#380]
Material Files looked really promising, but it's missing one critical feature I need it to do: the ability to select a bunch of files and move them somewhere else. For example, to get all the images files from the Downloads folder and put them into the Pictures folder, to put all PDF files into the Documents folder, etc.

Bonus point if it could batch-select "all the files matching this string" (i.e. be able to say everything that contains jpg, or everything that contains pdf, or Alice, or banana, etc.)

**Comment by zhanghai** [comment]
You can already select multiple files, even under different directories, and move them to one location together.

Your "bonus point" can be achieved by performing a search and select all.

**Comment by nekohayo** [comment]
Oh! Well that's interesting, because I couldn't find the feature, so I simply assumed it didn't exist. How do you move files? I selected multiple files and hit the hamburger (three dots) menu in the top-right corner, but there was no "Move" action available. There didn't seem to be a toolbar button for it either, nor the ability to drag multi-selected items elsewhere.

**Comment by zhanghai** [comment]
Glad you found it. It's called "cut" in order to pair with the later "paste", and Android design guidelines said one shouldn't show toolbar icon label on phone, although they may do so on tablet.
