### ISSUE TITLE
Support for opening paths in other apps - worst title

### ISSUE THREAD

**Issue by UltraBlackLinux** [zhanghai/MaterialFiles#383]
Hey there,
It would be cool, if this app would open the folder, it should open, when pressing on an app and pressing on open folder - https://github.com/MuntashirAkon/AppManager 

My description sucks, but I hope you ubderstand, what I mean...

**Comment by zhanghai** [comment]
This app isn't an app manager. If you want that app manager to open folder with this app, you should open an issue there.
