### ISSUE TITLE
Unable to open encrypted 7z/zip archives

### ISSUE THREAD

**Issue by soredake** [zhanghai/MaterialFiles#385]
![Screenshot_20201109-133141374_resized](https://user-images.githubusercontent.com/5204968/98536671-d2ab2a80-2290-11eb-878a-9ab801ec2b6b.jpg)
![Screenshot_20201109-133151590_resized](https://user-images.githubusercontent.com/5204968/98536685-d8087500-2290-11eb-9ffd-5824c6112cbc.jpg)

**Comment by zhanghai** [comment]
Duplicate of #193.
