### ISSUE TITLE
Scrolling lags and jerks when thumbnails are being loaded

### ISSUE THREAD

**Issue by opusforlife2** [zhanghai/MaterialFiles#400]
Is the thumbnail loading process in the same thread as scrolling? When you rapidly scroll past unloaded thumbnails, it causes major lag. If you scroll past them slowly, ensuring they're all loaded properly once, then scrolling becomes perfectly smooth, no matter how fast you scroll.

**Comment by zhanghai** [comment]
Of course no developer should be loading images on main thread. See https://github.com/coil-kt/coil/issues/409 .

**Comment by opusforlife2** [comment]
Oh. Upstream bug. Thanks!
