### ISSUE TITLE
Transparent background of options in android 6

### ISSUE THREAD

**Issue by prateekmedia** [zhanghai/MaterialFiles#403]
I can provide images if you want, the text becomes unreadable as the background of options is transparent.

Happens in Night color option.

Also after few seconds it retains its background color. Happens only in android 6 tablet, on my other phone it works fine

Image:
![Screenshot_Android6_Tablet.png](https://user-images.githubusercontent.com/41370460/100618307-ab9cc180-3341-11eb-945e-22a35ff6e4f0.png)

**Comment by zhanghai** [comment]
Yes, please provide a screenshot.

**Comment by prateekmedia** [comment]
@zhanghai 

Please check it, It happens only when selecting options like the night color one.

**Comment by prateekmedia** [comment]
It restores it background after 2 - 3 secs , Image attached below for reference

Before
![20201130_193014.png](https://user-images.githubusercontent.com/41370460/100619101-aee47d00-3342-11eb-818d-1132bf4e55ac.png)

After 2 secs
![20201130_193035.png](https://user-images.githubusercontent.com/41370460/100619132-b7d54e80-3342-11eb-8d48-6255b72ce8ad.png)

**Comment by zhanghai** [comment]
This is weird. Could you share more device info about your Tablet? e.g. What brand and model is it?

**Comment by zhanghai** [comment]
And to clarify, do you mean it happens for the night mode option, regardless of whether the app is in night mode; or it only happens when the app is set to be in night mode?

**Comment by prateekmedia** [comment]
It happens on any mode whether it is night or day.

Tablet model number is Lenovo - TB3850F

It doesnt happen in other material apps but on this.

**Comment by zhanghai** [comment]
Well, that menu is provided by a third party app, but if it works on all other devices except for your specific device, it may be your specific device having some weird bug with rendering etc... I tried to reproduce this on emulators but it worked fine for me.

**Comment by prateekmedia** [comment]
Ok also it's not a major bug and other things work great , I should close this Issue , Thanks btw
