### ISSUE TITLE
Why needed full network access?

### ISSUE THREAD

**Issue by r00t34** [zhanghai/MaterialFiles#409]
Hi all,

Hope you are well. I am bit paranoid and i wonder why internet access needed for File Manager app? And i couldn't see Privacy Policy or something like that about this issue.

Any help appreciated.

Kind Regards.

**Comment by zhanghai** [comment]
The FTP server feature needs Internet access, obviously.

The Privacy Policy is available via Play store link, in-app About link, and in this repo at https://github.com/zhanghai/MaterialFiles/blob/master/PRIVACY.md .

The Play version of this app uses Firebase Analytics for crash reporting and analytics. If you don't want analytics, you can get the F-Droid version, available on F-Droid or in the README of this repo. The F-Droid version is built by F-Droid (not me) from 100% open-source code (by dropping Firebase Analytics).
