### ISSUE TITLE
Edit Audio Tagger

### ISSUE THREAD

**Issue by Github-com-foss** [zhanghai/MaterialFiles#410]
![1842](https://user-images.githubusercontent.com/75672019/101604170-93eec880-3a26-11eb-8bc0-3ff3e7d0b10c.jpg)
![1840](https://user-images.githubusercontent.com/75672019/101604200-9c470380-3a26-11eb-8a43-430a1bf100ee.jpg)

1. Edit Tagger in Audio files
Audio file> properties > audio > Edit Tagger

2. Pls show and edit tag copyright label of audio.

SAMPLES IMAGES ADDED ONE IS MATERIAL FILES AND OTHER ONE IS MIXPLORER.

**Comment by zhanghai** [comment]
Duplicated into #411 - it's not fundamentally different

**Comment by Github-com-foss** [comment]
Pls show Copyright label and edit option in properties.
