### ISSUE TITLE
Metadata (Show/Edit/Delete)

### ISSUE THREAD

**Issue by Github-com-foss** [zhanghai/MaterialFiles#411]
Delete /Edit Metadata of Images and Videos

**Comment by zhanghai** [comment]
And audio

**Comment by Github-com-foss** [comment]
![101604200-9c470380-3a26-11eb-8a43-430a1bf100ee](https://user-images.githubusercontent.com/75672019/101608420-b0413400-3a2b-11eb-82c7-2e8d4d52a824.jpg)
Pls add Copyright label and edit option in properties.

IMAGE SAMPLE ADDED

**Comment by zhanghai** [comment]
Upon retrospection, none of these features are supported by Android API ([MediaMetadataRetriever](https://developer.android.com/reference/android/media/MediaMetadataRetriever)), so implementing them will require bundling external media libraries and significantly increase the size/complexity of this app. Thus these features won't be implemented in this app, and please find another dedicated app for this.

**Comment by Github-com-foss** [comment]
Pls reconsider it, For Eg Mixplorer silver only 9MB they can offer Archiver, SMB2, Image, Tagger, Metadata and PDF in Single app.
