### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by Github-com-foss** [zhanghai/MaterialFiles#414]
Pls reconsider it, For Eg Mixplorer silver only 9MB they can offer Archiver, SMB2, Image, Tagger, Metadata and PDF in Single app.

There is no Full-featured file manager in opensource project. So, pls make it material file manager to become full-featured.

_Originally posted by @Github-com-foss in https://github.com/zhanghai/MaterialFiles/issues/411#issuecomment-741900292_

**Comment by zhanghai** [comment]
I don't have the time to implement and maintain everything - this is just a personal project and I hope you can understand.
