### ISSUE TITLE
inbuilt PDF Viewer

### ISSUE THREAD

**Issue by Github-com-foss** [zhanghai/MaterialFiles#415]
There is several document format is there for eg PDF, EPUB, EPUB3, MOBI, DjVu, FB2, TXT, RTF, AZW, AZW3, HTML, CBZ, CBR, DOC, DOCX, and OPDS Catalogs.
But PDF is the most used document format in android. Recently Google also implemented in files by Google app. So, pls add Simple PDF viewer in material files pls.

**Comment by zhanghai** [comment]
I'm not seeing a PDF viewer in Files by Google (I only saw the Google Drive one). PDF viewer is of enough complexity and everyone can just get a dedicated app that does it better, so I won't be implementing it.

BTW, PDF thumbnail preview will indeed be in the next version though.

**Comment by teemue** [comment]
I hope you would reconsider this :) Some other FOSS file managers have implemented this as well - for example [Simple File Manager](https://github.com/SimpleMobileTools/Simple-File-Manager/releases/tag/6.12.3).
