### ISSUE TITLE
App's "Open with" broken when destination in root

### ISSUE THREAD

**Issue by UltraBlackLinux** [zhanghai/MaterialFiles#416]
Hello there,
I ran into this problem multiple times already: When opening a root directory via any other app, MF (oh no) just gets opened at the user's home directory.
An obvious example is https://muntashirakon.github.io/AppManager/ Just click on an app and press the Open directory symbol for the /data/data entry and see, that MF only opens the home directory.
This is super annoying, please fix it!
Thanks!

**Comment by zhanghai** [comment]
Manually tested that opening directory in AppManager now works wth Material Files. Will be fixed in the next release.
