### ISSUE TITLE
Show indication of delete,move & copy

### ISSUE THREAD

**Issue by Github-com-foss** [zhanghai/MaterialFiles#418]
Pls Show indication while delete, move and copy.

![IMG_20201218_082823_347_1_1](https://user-images.githubusercontent.com/75672019/102570514-8532a080-410d-11eb-90d4-73771035b4ea.jpg)
![IMG_20201218_083201_408_1_1_1](https://user-images.githubusercontent.com/75672019/102570518-86fc6400-410d-11eb-929f-36e64e2d69d3.jpg)

**Comment by zhanghai** [comment]
Please look at the notifications.
