### ISSUE TITLE
Show hidden folders feature

### ISSUE THREAD

**Issue by devlocalhost** [zhanghai/MaterialFiles#422]
It would be great idea, if we could see hidden folders too, just like other apps that allow you to see hidden folders (folders that start with a dot). Btw, I'm using the latest 1.1.4 version if it's needed, from playstore.
![Screenshot_20201229-223908](https://user-images.githubusercontent.com/56504654/103312808-d6546580-4a26-11eb-9dc5-535e8c23a31b.png)
![Screenshot_20201229-223918](https://user-images.githubusercontent.com/56504654/103312811-d81e2900-4a26-11eb-91ce-49e53a684b88.png)

**Comment by zhanghai** [comment]
You can see hidden folders if you check the "Show hidden files" option in menu. Note that this app shows dot files/folders after the regular ones, similar to GNOME Nautilus.

**Comment by devlocalhost** [comment]
I have the "show hidden files" option enabled, but I still don't see the hidden folders that start with a dot (for example .test)
![Screenshot_20201230-041055](https://user-images.githubusercontent.com/56504654/103325588-061a6200-4a55-11eb-81c6-f36c6e9418bf.png)

**Comment by zhanghai** [comment]
Can you double check if they are behind the non-dot folders? Because mine have always been there.

**Comment by devlocalhost** [comment]
Hmm, weird. I can now see the folders, but they were at the bottom of the list... Like, i didnt saw them yesterday, and i didnt enabled or disabled any option...
![Screenshot_20201230-171730](https://user-images.githubusercontent.com/56504654/103363068-eb7ed200-4ac2-11eb-829d-f046b22bf079.png)
