### ISSUE TITLE
Chooser intent missing ClipData and flags from wrapped ACTION_SEND intent

### ISSUE THREAD

**Issue by rejhgadellaa** [zhanghai/MaterialFiles#423]
Hi,

I'm the developer of Sharedr, a share menu replacement app.

One of my users pointed out that Sharedr doesn't work when trying to share a file from your app.

While I can't be sure, I suspect that your app is relying on the legacy EXTRA_STREAM to supply a content:// uri to the destination app. I'll try to give more details below but I can imagine your time is valuable so here's the quick fix:

Instead of only setting Intent.EXTRA_STREAM...

```
Intent intent = new Intent();
intent.putExtra(Intent.EXTRA_STREAM, uri);
Intent chooserIntent = Intent.createChooser(intent, null);
startActivity(chooserIntent);
```

..please also use setClipData() and - optionally, Android should do this for you as long as you use setClipData() - then call addFlags(FLAG_GRANT_READ_URI_PERMISSION):

```
Intent intent = new Intent();
intent.setClipData(ClipData.newRawUri(null, uri));
intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
intent.putExtra(Intent.EXTRA_STREAM, uri); // keep this for compatibility with old applications
Intent chooserIntent = Intent.createChooser(intent, null);
startActivity(chooserIntent);
```

Please also see the issue I filed on the AOSP bug tracker regarding this (little known) problem:https://issuetracker.google.com/issues/176280829

If you want to test if it works, you could download and install Sharedr (https://sharedr.rejh.nl/).

Now, for some background information and why this change is needed to support 3rd party share menu apps.

With Android Jelly Bean (API 16) Intent.setClipData(android.content.ClipData) was introduced:

> As of Build.VERSION_CODES.JELLY_BEAN, the data being sent can be supplied through setClipData(android.content.ClipData). This allows you to use FLAG_GRANT_READ_URI_PERMISSION when sharing content: URIs and other advanced features of ClipData. If using this approach, you still must supply the same data through the EXTRA_TEXT or EXTRA_STREAM fields described below for compatibility with old applications. If you don't set a ClipData, it will be copied there for you when calling Context#startActivity(Intent).

Source: https://developer.android.com/reference/android/content/Intent#ACTION_SEND

As stated in the docs, Android will copy the uri to a ClipData if you don't set it. What the docs don't tell you is that Android's Intent.createChooser() will not copy the EXTRA_STREAM and the FLAG_GRAND_READ_URI_PERMISSION flag to the so called chooser intent. This makes sense, as this flag only works on ClipData: If an app doesn't use setClipData() but instead only uses the legacy EXTRA_STREAM method, that implies the flag will not work, thus is not needed, and the system should not add those flags.

In case you wonder why this is a problem for 3rd party share menu replacement apps while it's working fine with the system share menu: From what I've learned from the Android system share menu's source code, it leverages its system app privileges to add the flag and then starts the destination app on your app's behalf. That way the system share menu can grant read permission for content:// uris that actually belong to your app. As you can probably imagine, 3rd party apps are not allowed to pull these kinds of shenanigans.

Again, please also see the issue I filed on the AOSP bug tracker regarding this (little known) problem:https://issuetracker.google.com/issues/176280829

If you've read this far: Many thanks for your time, I hope you will find the time to fix the problem. If you have any further questions I'll do my best to answer them.

**Comment by zhanghai** [comment]
According to [`Intent.createChooser()`](https://developer.android.com/reference/android/content/Intent#createChooser(android.content.Intent,%20java.lang.CharSequence)) javadoc:

> If the target intent has specified `FLAG_GRANT_READ_URI_PERMISSION` or `FLAG_GRANT_WRITE_URI_PERMISSION`, then these flags will also be set in the returned chooser intent, with its `ClipData` set appropriately: either a direct reflection of `getClipData()` if that is non-null, or a new `ClipData` built from `getData()`.

I'm indeed setting the data as well as `FLAG_GRANT_READ_URI_PERMISSION` and `FLAG_GRANT_WRITE_URI_PERMISSION` flags. So do you mean the documentation is incorrect in this case?

**Comment by zhanghai** [comment]
I'm setting the data instead of the clip data so that it can work with both newer apps reading clip data as well as older apps reading intent data thanks to the automatic mgiration upon leaving process. However, since there isn't a backward automatic migration, setting the clip data instead of data would break those older apps.

**Comment by rejhgadellaa** [comment]
Thanks for taking a look.

> So do you mean the documentation is incorrect in this case?

From what I can tell, `Data` should indeed be copied by `Intent.createChooser()`. Here's its source code on a recent AOSP branch:

https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android10-release/core/java/android/content/Intent.java#997

If the intent has a `FLAG_GRANT_***_URI_PERMISSION` flag, `getClipData() == null` && getData() != null`, it should copy the `Data` to `ClipData` and add the flags to the chooser intent.

So not sure why this would cause any problems. Guess I'll have to do some debugging on my side, see what the incoming chooser intent from your app and `EXTRA_INTENT` inside it look like.

> However, since there isn't a backward automatic migration, setting the clip data instead of data would break those older apps.

I think you can set both `ClipData` and `Data` on the same intent? Not entirely sure though.

**Comment by rejhgadellaa** [comment]
Ah I think I found the problem. You do call `setDataAndType()` when you build a `ACTION_VIEW` intent, but not when you build `ACTION_SEND` intents:

```
fun CharSequence.createSendTextIntent(htmlText: String? = null): Intent =
    Intent()
        .setAction(Intent.ACTION_SEND)
        .setType(MimeType.TEXT_PLAIN.value)
        .putExtra(Intent.EXTRA_TEXT, this)
        .apply { htmlText?.let { putExtra(Intent.EXTRA_HTML_TEXT, it) } }

fun Uri.createSendStreamIntent(mimeType: MimeType): Intent =
    Intent(Intent.ACTION_SEND)
        .putExtra(Intent.EXTRA_STREAM, this)
        .setType(mimeType.intentType)

fun Collection<Uri>.createSendStreamIntent(types: Collection<MimeType>): Intent =
    if (size == 1) {
        first().createSendStreamIntent(types.single())
    } else {
        Intent(Intent.ACTION_SEND_MULTIPLE)
            .setType(types.intentType)
            .putParcelableArrayListExtra(Intent.EXTRA_STREAM, ArrayList(this))
    }
```

I had a look at the intent I receive and it has no flags, `Data`, `ClipData` and/or `EXTRA_STREAM` set.

I think these functions need a `setDataAndType()` and/or `setClipData()` call there.

**Comment by zhanghai** [comment]
`ACTION_SEND` doesn't use `setDataAndType()`, but only `EXTRA_STREAM` (required) and `setClipData()` (optional):

```
     * As of {@link android.os.Build.VERSION_CODES#JELLY_BEAN}, the data
     * being sent can be supplied through {@link #setClipData(ClipData)}.  This
     * allows you to use {@link #FLAG_GRANT_READ_URI_PERMISSION} when sharing
     * content: URIs and other advanced features of {@link ClipData}.  If
     * using this approach, you still must supply the same data through the
     * {@link #EXTRA_TEXT} or {@link #EXTRA_STREAM} fields described below
     * for compatibility with old applications.  If you don't set a ClipData,
     * it will be copied there for you when calling {@link Context#startActivity(Intent)}.
```

So I think it's pretty standard to for modern apps to set only `EXTRA_STREAM`. I'm looking into the flag issue, but I do see it in `migrateExtraStreamToClipData()`:

```
    public boolean migrateExtraStreamToClipData(Context context) {
...
        if (ACTION_CHOOSER.equals(action)) {
...
                            migrated |= intent.migrateExtraStreamToClipData(context);
...
        } else if (ACTION_SEND.equals(action)) {
...
                    setClipData(clipData);
                    addFlags(FLAG_GRANT_READ_URI_PERMISSION);
...
```

**Comment by zhanghai** [comment]
I think I know where the issue is now.

`Intent.createChooser()` do have the logic to promote child clip data to parent with flags, however since `Intent.createChooser()` is called before `Context.startActivity()`, `Intent.migrateExtraStreamToClipData()` haven't had a chance to fix the child intent yet so `Intent.createChooser()` didn't fix anything.

`Intent.migrateExtraStreamToClipData()` does migrate for `ACTION_CHOOSER`, however it explicitly said in comment:

```
            // Inspect contained intents to see if we need to migrate extras. We
            // don't promote ClipData to the parent, since ChooserActivity will
            // already start the picked item as the caller, and we can't combine
            // the flags in a safe way.
```

And won't promote the child clip data to parent as `Intent.createChooser()` would. The comment is technically correct about this, but certainly this isn't the most convenient and expected behavior.

As a workaround, I can use AndroidX `ShareCompat` which implemented a custom `migrateExtraStreamToClipData()` that is called upon intent creation to utilize `Intent.createChooser()`'s fix.

**Comment by zhanghai** [comment]
I believe 6d974d1 should fix this, but please manually test if you are interested - I merely tested that system share sheet still works, as I don't use 3p share sheets.

**Comment by rejhgadellaa** [comment]
Thanks for the fix. Any idea when this will land in the Play Store so I can test it?

And just a quick follow-up on one remark you've made;

> it's pretty standard for modern apps to set only EXTRA_STREAM

That's true but it's an incorrect use of the SDK/API (one Sharedr is running into all the time). As your own quote of javadocs states:

> [...] setClipData [...] allows you to use FLAG_GRANT_READ_URI_PERMISSION [...]

I'm glad ShareCompat made the change that should fix this (I proposed AOSP would make the same change, but they came back with the infamous "won't fix"), but I think simply adding setClipData() should have worked, too. 

Oh well, if it works, it works :)

Thanks again for the work!

**Comment by zhanghai** [comment]
> Any idea when this will land in the Play Store so I can test it?

I'm planning a release in one or two weeks - it has been almost 5 months since last release, and I do have a load of features to offer this time :)

I was asking if you want to manually test this (by building from MaterialFiles git master) because if everything goes well with the next release, the release after that would be another several months later, and I won't send all users a patch release just because this issue alone isn't actually fixed. There is a high chance that I have to do a patch release if some other more severe bugs pop up in the next release though.

> That's true but it's an incorrect use of the SDK/API (one Sharedr is running into all the time). As your own quote of javadocs states:

No, I still believe it's correct usage of the API, because the doc I quoted earlier said in the last sentence:

```
If you don't set a ClipData, it will be copied there for you when calling {@link Context#startActivity(Intent)}.
```

**Comment by rejhgadellaa** [comment]
Just confirmed sharing files works when using Sharedr. Thanks!
