### ISSUE TITLE
automatically remove storage entry from leftside pop menu, when the actual location become inaccessible

### ISSUE THREAD

**Issue by stevenleeS0ht** [zhanghai/MaterialFiles#424]
When I mount a USB flash drive to the system, in order to view the files in it, I need to touch `Add external storage` on left side pop menu.

But when I unmount the flash drive, the entry at the menu is still exist. But it is no longer valid. When I touch it, a single line of Java class name is displayed in the main screen.

This is not so beautiful.

Is it possible to let MaterialFiles automatically remove the entry when its real location is removed or no longer accessible?

@zhanghai , what is your opinion?

**Comment by zhanghai** [comment]
It is fragile to detect if the URI returned by DocumentsUI is removable and is actually removed, while the URI can actually be anything (e.g. Bug report, Termux, SMB, Google cloud, etc...), so I don't have a plan for this.
