### ISSUE TITLE
Feature request: include ftp, samba, webdev browser

### ISSUE THREAD

**Issue by ProgrammingPlanet** [zhanghai/MaterialFiles#425]
You can also include file sharing over wifi.

**Comment by devlocalhost** [comment]
Yeah, it would be a good idea if we could transfer files over WiFi, but also if we could access other FTP Servers from the app.

**Comment by zhanghai** [comment]
Please search for existing feature requests before opening a new one.

I don't have a plan for transfer files over WiFi, because that can easily be a functionality of another entire app and my spare time is limited.
