### ISSUE TITLE
我看更新了，windows文件名编码应该选哪个，测试了很多个还是不能显示中文 

### ISSUE THREAD

**Issue by huanx9** [zhanghai/MaterialFiles#427]
上传中文文件名的文件就会报错~~我看更新了 是不是支持windows了

**Comment by zhanghai** [comment]
上传到哪里？这个 Android app 怎样支持 Windows？

**Comment by huanx9** [comment]
#245  就是编码问题。。我以为 1.1.4版本支持修改文件名编码 达到适配windows的效果了。。 看来还是不行

**Comment by huanx9** [comment]
我反复测试了 "归档文件名编码“  这个设置，好像并不能友好的显示 中文。 看来我对这个设置存在误解。

**Comment by huanx9** [comment]
有没有相关的讨论。。想解决这个问题。谢谢开发者 。。 还有息屏后  FTP服务会自动关闭。。

**Comment by zhanghai** [comment]
选 UTF-8 吧；我用的就是 Apache MINA FtpServer ，没额外配置编码，Android 上的默认编码是 UTF-8。

**Comment by huanx9** [comment]
使用windows默认资源管理器 可以正确的显示中文，但是无法上传（应该属于编码报错）
使用firefox edge ie 等浏览器， 就直接中文乱码了
使用第三方FTP。。体验很好。 显示上传都正常。。  只是不够原生 

我提交这个问题是想让浏览器显示的更加优雅。。 我以为更新之后有办法了 才来问的。 

之后我还是用第三方FTP工具吧，感谢开发者。

**Comment by huanx9** [comment]
补充一下， 有同学告诉我。。 MIUI原生支持FTP 。。我测试了一下，编码GBK ，完美适配windows.... 开发者还需要努力呀。谢谢开发者，

**Comment by zhanghai** [comment]
给中文环境就用 GB2312 也就高兴了 Windows，Linux 和 MacOS 都是默认 UTF-8 的。我觉得 Windows 下的应用还需努力……
