### ISSUE TITLE
Retrieve names from SAF providers

### ISSUE THREAD

**Issue by haarp** [zhanghai/MaterialFiles#432]
Hello!

I'm realling liking this app, thanks for making it!

When adding bookmarks for SAF providers, the bookmark will show a pathname only. This can be a bit confusing. It would probably be better to show the pretty name aswell, as com.android.documentsui does. e.g. "Termux" instead of "home" or "Nextcloud" instead of "/".

Cheers!

**Comment by zhanghai** [comment]
It is impossible because the APIs to get these names are only for usage by the system DocumentsUI app, not any app. With #195 you would be able to rename them manually though.
