### ISSUE TITLE
allow users to add folders to standard folders

### ISSUE THREAD

**Issue by bydariogamer** [zhanghai/MaterialFiles#434]
It is just a sugestion, but it would be nice if users could add their own paths to standard folders (becuase maybe they doesn't have screenshots in storage/emulated/0/pictures/screenshots but in storage/emulated/0/DCIM/screenshots...) Or maybe users could add favourite folders.

**Comment by zhanghai** [comment]
That is called bookmark folders in the app.

**Comment by xanda-escuyer** [comment]
Please would this be reconsidered?

On some devices, the settings for 'Standard Folders' default to external storage but to internal on others; it seems unaffected by either settings within the app or Android system.

Perhaps it would be helpful for the standard folders to follow the setting for default folder? Or maybe even having an editable text box (especially for Downloads folder)?

We appreciate the point about the bookmarking feature but having to do this can largely negate the 'Standard Folder' function itself as well promoting visual clutter.

![StdFolders-01](https://github.com/user-attachments/assets/dc4c52c8-c1c7-461a-8759-69da14f930fc)
![StdFolders-02](https://github.com/user-attachments/assets/be7a2206-f782-4544-aef4-dd8d075f79f9)
