### ISSUE TITLE
[Feature request] Support Animated WebP

### ISSUE THREAD

**Issue by aaronhatesregex** [zhanghai/MaterialFiles#435]
Animated WebP is not supposed as of Version 1.1.4(21) on F-Droid. Plain WebP is supported.

I don't know much about the specs but some info can be found at [a web page of Google Developers](https://developers.google.com/speed/webp/docs/riff_container#animation)

I try to find relevant libraries in [LICENSES](https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/res/raw/licenses.xml), but the library used to support WebP format seems not so obvious as [AndroidSVG](https://github.com/BigBadaboom/androidsvg).

GitHub won't allow me to upload WebP file so I pack the example files into an archive...Just FYI, the WebP is converted using `convert` command of ImageMagick.
[awebpexample.zip](https://github.com/zhanghai/MaterialFiles/files/5855713/awebpexample.zip)

**Comment by zhanghai** [comment]
There isn't animated webp support in Android framework so supporting it would require bundling third-party native code, which I'd like to avoid if possible. This app uses coil-kt/coil for image loading so if they support animated webp I'd be happy to integrate. But other than that, I don't have any immediate plan for this.

**Comment by aaronhatesregex** [comment]
> There isn't animated webp support in Android framework

Sad to know that :(. WebP still has a long way to go.

Thanks for the reply anyway!
