### ISSUE TITLE
Image Viewer zoom

### ISSUE THREAD

**Issue by haarp** [zhanghai/MaterialFiles#437]
The image viewer always seems to fit large images to the viewport. Pinching to zoom doesn't work. I know it's just a simple preview, but zoom would be much appreciated. Thanks!

v1.1.4

**Comment by zhanghai** [comment]
It's actually a weird bug. If you try cycling through images, double tap, closing and re-opening the image viewer, repeatedly, you may find zooming working again. I don't know under what conditions it would be broken or what exactly to do to recover from it.

**Comment by haarp** [comment]
No luck, I don't seem to be able to make it work at all :( And I don't think it ever did for me.

**Comment by zhanghai** [comment]
For me the following steps worked:

- Open the built-in image viewer in a folder with multiple images.
- Double tap on the opened image - nothing happens.
- Swipe till the end of the list of images, then swipe back.
- Press back to close the image viewer.
- Open the image viewer again.
- Double tap on the opened image - now it zooms.
- Unless you force-stop the app (or in any other way get the app process restarted), image viewer remains zoomable.

**Comment by linsui** [comment]
I just need to open an image and close the image viewer. Then the image, the one before it and the one after it will be zoomable. Other images are still not zoomable.

**Comment by zhanghai** [comment]
https://github.com/natario1/ZoomLayout seems a viable replacement.

**Comment by haarp** [comment]
> I just need to open an image and close the image viewer. Then the image, the one before it and the one after it will be zoomable. Other images are still not zoomable.

Yes, this seems to do the trick. Although it seems limited to the one before it for me, and then stops working as you navigate to another image again.

**Comment by ManDay** [comment]
I also have this issue. I would think relying on whatever external image viewer there is might make sense. No need to bundle any file viewing capacity with the file browser, in my opinion.
