### ISSUE TITLE
Unable to send files to SD card with FTP server.

### ISSUE THREAD

**Issue by mrghosti3** [zhanghai/MaterialFiles#439]
Tried sending files from pc to phone external storage (sd card) via ftp server using WinSCP program (mainly .zip and .pdf files). Only shows that it sent 0 bytes and when file opened programs don't show anything due to file being empty.

Using version 1.1.4 (21)

![Screenshot 2021-01-31 005941](https://user-images.githubusercontent.com/44092345/106370252-1c675680-6350-11eb-81f5-e46578b2eeb0.png)
![Screenshot_20210131-005831](https://user-images.githubusercontent.com/44092345/106370253-1d988380-6350-11eb-8fa2-e924ffdd1384.png)

**Comment by MarkStuff** [comment]
I have the same problem too. 
All files on the SD card are inaccessible because they are 0 bytes in size
No problem with internal storage.
Is it a rights problem? Do we need root to make it accessible?

**Comment by mrghosti3** [comment]
@zhanghai does root directory have any affect on this issue?!
[Screenshot_20210310-010337.png](https://user-images.githubusercontent.com/44092345/110550609-e9bd3480-812b-11eb-851e-58a12cf8fb92.png)

**Comment by zhanghai** [comment]
Sound worthy of a fix, I'll investigate this before the next release.

**Comment by zhanghai** [comment]
(@mrghosti3 Meanwhile just FYI if you didn't look at changelog, the MD1 theme you are using in the screenshot has been deprecated in the last release and will be removed in the next release, in exchange for custom colors in MD2 theme and optional AMOLED black support)

**Comment by zhanghai** [comment]
I couldn't reproduce this with 1.1.4 and running FTP with the "Internal storage" added as an external storage as root, and I could successfully copy a file into the FTP server on my Linux with Nautilus.

Could you try reproducing this by each of the following setups?

1. Set root folder to the build-in internal storage
2. Add "Internal storage" as an external storage in app and set it as root folder
3. Add your SD card as an external storage and set it as root folder
4. The same as 3, but with a different FTP cilent on your computer, e.g. Filezilla? You may also try Windows explorer in addition.

**Comment by mrghosti3** [comment]
Tried with other client (FileZilla) and it did work. Interesting thing is, while doing the same with Windows File Explorer just makes every file in that root directory 0 bytes.

**Comment by zhanghai** [comment]
I tried with Windows 10 20H2 Explorer, Android 11 on Pixel 4 XL, with an internal storage folder added as external storage via DocumentsUI picker and set as FTP root. Copying over files worked as expected, and no file was zero'ed out.

What is your Android version, device model and Windows version?

**Comment by mrghosti3** [comment]
Windows 10 20h2
Xiaomi Mi A1, Android One, Android 9

I probably didn't everything correctly as you did, so that might be the cause of why files were zeroed.

**Comment by zhanghai** [comment]
Oh, I finally reproduced this one! Android 9 + DocumentsUI is the key here. It doesn't happen on Android 11 nor non-DocumentsUI. I'm still investigating this.

**Comment by zhanghai** [comment]
Fixed - the root cause here is that Windows Explorer checks whether every file is writable, and for that the FTP server has to try to open the file with write mode to check, then close it immediately. The problem is that before Android 10, Android system class `ParcelFileDescriptor.parseMode()` would take the open mode "w" (simply open fo write) to be the same as "wt" (open to write and truncate existing file), but this was fixed in Android 10. As a result, when the app tries to check for access with "w", the file gets truncated by Android as if "wt" is used instead. The workaround here is to pass "wa" (write by appending) on the older platforms to prevent truncation.

**Comment by mrghosti3** [comment]
Thank you very much. Could I ask where did you check this (curious to learn about myself. Android Developer Docs?).

**Comment by zhanghai** [comment]
Just dive into the Android source code. You may open the downloaded SDK sources, or use [cs.android.com](https://cs.android.com).
