### ISSUE TITLE
Add access to the OS's native clouds.

### ISSUE THREAD

**Issue by xunil89** [zhanghai/MaterialFiles#442]
Hello, I was wondering if it was possible to add access to the clouds that are logged into the operating system accounts. To understand how the file manager integrated into the distribution does as shown in the image.
![IMG_20210213_104052_852.jpg](https://user-images.githubusercontent.com/14961235/107846933-05147880-6de8-11eb-96b0-4b8e43552fc1.jpg)

**Comment by zhanghai** [comment]
If you click "Add external storage..." in Material Files, and can select that cloud in the OS file picker, than you can manage those files. i.e. It is supported by Material Files already. If you can't find it, that means the cloud app didn't allow third party file managers to touch those files, and I can't do anything here :/

**Comment by xunil89** [comment]
> If you click "Add external storage..." in Material Files, and can select that cloud in the OS file picker, than you can manage those files. i.e. It is supported by Material Files already. If you can't find it, that means the cloud app didn't allow third party file managers to touch those files, and I can't do anything here :/

I had already seen that function, but I don't understand if it is identical in operation to the native one or if it is a "trick". If it were then possible to name the folder it would not be bad ...

**Comment by zhanghai** [comment]
If you can see it, it will be using the same underlying Android API (`DocumentsProvider`). It's a proper API and not a trick or hack. I can't say identical becauae of course I didn't just copy code from the OS files app.

Renaming will come in the next major version - I'm still wirting the rename dialog

**Comment by xunil89** [comment]
Perfect thanks for the clarification, still great app!

**Comment by zhanghai** [comment]
Btw SMB wil be in the next release as well :P It will be experimental though, because I'm not a heavy user of SMB so my own manual testing will be limited.
