### ISSUE TITLE
Move Settings to bottom

### ISSUE THREAD

**Issue by Donkey-Doug** [zhanghai/MaterialFiles#448]
Move settings to the bottom of the hamburger menu. 

See this screenshot from a different app:
![Screenshot_20210220-011322_K-9_Mail](https://user-images.githubusercontent.com/50382414/108574966-0fb79c00-7319-11eb-85d1-4c3f37dd7b6d.png)

**Comment by zhanghai** [comment]
Well, this will be complicating the code and either way works fine. I have Google Calendar with two accounts and the Settings item is pushed out of screen, but I think it's fine.
