### ISSUE TITLE
Can't access Android/data after upgrading Android 11

### ISSUE THREAD

**Issue by dragon2024** [zhanghai/MaterialFiles#452]
Hello,

I was using Material Files on Android 10 without any problem. When upgraded to Android 11 it is not working anymore. Here the screenshot that i encountered

Hope you can fix this issue

![Screenshot_me zhanghai android files](https://user-images.githubusercontent.com/79598118/109042175-eca63700-76e0-11eb-8e39-41b79dfc4e42.jpg)

**Comment by Tiger3018** [comment]
See #384

**Comment by zhanghai** [comment]
This is a new restriction in Android 11 that disallows apps to access `Android/data`.

You can always access `Android/data` if you have root. If you don't have root, you will be able to access it **in the next release** by granting Material Files the access to external storage or the `Android` directory in DocumentsUI (By clicking Add storage -> External storage in Material Files).
