### ISSUE TITLE
Change breadcrumb to case-sensitive

### ISSUE THREAD

**Issue by factorial52** [zhanghai/MaterialFiles#455]
Linux-aware is mentioned as a feature, however the breadcrumb always shows in caps. It's a small detail. Still, the path shown is not the true path on Android (Linux), unless the path is actually all caps.

**Comment by zhanghai** [comment]
All caps was a design choice in MD1 style to make the items have the same height visually. However since we are following MD2 now and the official DocumentsUI isn't using all caps, I'll remove the all caps as well.
