### ISSUE TITLE
Does not detect external storage

### ISSUE THREAD

**Issue by Donkey-Doug** [zhanghai/MaterialFiles#457]
Material files does not detect external storage. I also cannot manually find my external storage and add it. I used a USB type C USB stick. I had to use the default file manager app of android. The USB stick was immediately shown in the default android app.

OS: LineageOS 17 (Android 10)
Device: Xiaomi Mi 9T Pro
Version: 1.1.4

**Comment by zhanghai** [comment]
You need to click "Add external storage", and select the external storage in the system Files app.

**Comment by Donkey-Doug** [comment]
@zhanghai Is it possible to automatically add the storage? Like on windows?

**Comment by zhanghai** [comment]
This has been added in #646 but the release of the next version is blocked by #669.
