### ISSUE TITLE
Unable to write using FTP

### ISSUE THREAD

**Issue by Akhilesh-T** [zhanghai/MaterialFiles#463]
Hello,

I'm not able to delete a file over FTP when I'm connecting my phone to PC even though the **Allow writing** option is enabled in **Configuration**

I'm getting the following error...

<img width="310" alt="explorer_x14ykREuS2" src="https://user-images.githubusercontent.com/80357467/110779806-ff487080-8289-11eb-80b7-0798286b05a5.png">

**Comment by zhanghai** [comment]
There's not enough information here for me to derive any meaningful conclusion. Please include the PC system version, PC FTP software, device model, Android version, app version, and steps to reproduce, so that I may analyze the issue.

**Comment by Akhilesh-T** [comment]
PC: Windows 10
FTP software: Windows Explorer
Device Model: Samsung Galaxy M51
Android version: 11

### Steps to reproduce:

- Connect Phone to PC via FTP
- Open Windows Explorer to FTP address
- Delete/Rename a file present on the phone's SD Card on Windows Explorer

**Comment by zhanghai** [comment]
Will be fixed in the next release.

**Comment by Akhilesh-T** [comment]
Thank you @zhanghai
