### ISSUE TITLE
Text Editor Performance

### ISSUE THREAD

**Issue by Pantyhose-X** [zhanghai/MaterialFiles#467]
Unable to edit 500 MB text file
The app crashes! Java.io.IOException: File is too large
[StackOverflow proposes](https://stackoverflow.com/questions/14587734/android-how-do-you-efficiently-load-a-large-amount-of-text-in-a-textview) loading into a ListView

**Comment by zhanghai** [comment]
No, I don't have a plan to support text files as big as 100MiB. The built-in text editor is just for convenience and not meant to be a powerful text editing app.
