### ISSUE TITLE
Files in external storage provided by apps is displayed as 0B

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#471]
I tested with Muzei and Pixiv for Muzei 3. All files can be opened without no problem but the size is displayed as 0B.

**Comment by zhanghai** [comment]
What do you mean by "external storage provided by apps"? For me Seafile works fine.

**Comment by linsui** [comment]
I add some directories from the sidebar of the DocumentUI. They are provided by apps using  SAF provider.

**Comment by zhanghai** [comment]
So could you share a more detailed steps to reproduce and screenshot(s)? SAF seems working fine for me so I'm not sure which use case you are running into problems with.

**Comment by linsui** [comment]
1. Add storage

![IMG_20210321_181133](https://user-images.githubusercontent.com/36977733/111901213-78845800-8a2e-11eb-8171-8c90464ca40c.jpg)

2. Select a provider

![IMG_20210321_181305](https://user-images.githubusercontent.com/36977733/111901214-79b58500-8a2e-11eb-9347-d637b07d3a40.jpg)
![IMG_20210321_181345](https://user-images.githubusercontent.com/36977733/111901215-7ae6b200-8a2e-11eb-932a-05b34621f52b.jpg)

3. See the result

![IMG_20210321_181439](https://user-images.githubusercontent.com/36977733/111901216-7c17df00-8a2e-11eb-8bba-086e4173d435.jpg)

**Comment by zhanghai** [comment]
Muzei isn't provide the size information according to its source code [MuzeiDocumentsProvider.kt](https://github.com/muzei/muzei/blob/21b7262ef911c6405e985624794df3298ad12650/android-client-common/src/main/java/com/google/android/apps/muzei/provider/MuzeiDocumentsProvider.kt#L151) and [MuzeiArtDocumentsProvider.kt](https://github.com/muzei/muzei/blob/21b7262ef911c6405e985624794df3298ad12650/muzei-api/src/main/java/com/google/android/apps/muzei/api/provider/MuzeiArtDocumentsProvider.kt#L325). Please file a bug on Muzei's repo if you think this should be fixed.

**Comment by linsui** [comment]
Thanks!
