### ISSUE TITLE
[BUG/Feature Request] 'Add SMB server' interface doesn't allow empty passwords

### ISSUE THREAD

**Issue by Redjard** [zhanghai/MaterialFiles#474]
I am using F-Droid release 1.2.0, trying to replace my year-old ES File Explorer 1.1.4 for good.
One important 'feature' I need, is to access smb shares for a specific username, but without password (as in the password for that user is emptystring).

A client I work for has an smb share on their internal network, with a user that has no password set. Windows apparantly implements passwordless users by setting the password to emptystring, any entered password will lead to an authentication failure, while anonymous or guest access gets rejected.

On all my Linux devices and in ES File Explorer, I can just leave the password field empty and everything works fine.

I assume it would be enough to remove the requirement for a password input in the 'add SMB server' interface. Maybe replace it with a popup warning instead, if you want to prevent users forgetting to enter a password? A setting to allow this would also do, it seems like a feature most would never need.

Otherwise I really like the App so far, first thing in years that has come close enough I could allmost get rid of ES. If smb servewrs with empty passwords would be supported, I would switch fully.

![Screenshot_20210323-183937](https://user-images.githubusercontent.com/47570415/112193364-1aab6800-8c08-11eb-8660-b1faaccc41c0.png)

**Comment by zhanghai** [comment]
Yes this is indeed a bug - I shouldn't have assumed username authentication requires non-empty password. I'll fix this.
