### ISSUE TITLE
Files cannot handle folders with emoji in their names

### ISSUE THREAD

**Issue by Frivolous2** [zhanghai/MaterialFiles#475]
Copying and moving fails.
Version 1.2.0, Android 10

**Comment by Redjard** [comment]
Working fine for me with "☢️2️⃣1️⃣3️⃣" and "📅🇦🇱🤤👍🏻" on Android 7.1.1
I managed to create those files, and copy/move them to the same directory, Download and /data
Worked in both normal and root mode.
got cancer now, pls donate to my gofundme

**Comment by Frivolous2** [comment]
![Screenshot_20210324-013539_Material_Files](https://user-images.githubusercontent.com/57101103/112232467-4860d300-8c41-11eb-8b1b-5ce0ebd9af4c.png)

**Comment by Redjard** [comment]
"🏖️" works for me, but from that path I assume you are copying to an sd-card? Copying to mine works, but might be a filesystem on yours, that doesn't support unicode (I believe FAT32 has caused me some problems with filenames in the past). Does something like "∂√∇" work? Have you tried different folders on different partitions?

**Comment by Frivolous2** [comment]
Yes, it works. Copying emoji folders in internal storage also works. SD card is formatted exFAT. Should I change issue title to "Support exFAT"?

**Comment by Frivolous2** [comment]
Yes, it works. Copying emoji folders in internal storage also works. SD card is formatted exFAT. Should I change issue title to "Support exFAT"?

**Comment by Frivolous2** [comment]
Actually, Lineage Files can't handle it either. I'm assuming OS doesn't actually support exFAT fully. Closing issue.

**Comment by Redjard** [comment]
If more normal alphanumeric filenames work maybe name it something like "use unicode as filename encoding format on exFAT partitions". [This](https://stackoverflow.com/a/12237468/13156380) seems to suggest exFAT can only handle 'OEM' character sets on some OSs, so filenames named with that method might very well appear messed up when viewed in other apps, or some OSs.
So this might not be fixable.
I would recommend you to just reformat your sd-card to FAT32, that seems to have unicode support in android, or to not use fancy characters and non-european language families.
Blame Microsoft, they made a filesystem standard in 2006, when unicode was the go-to in any naming schemes, and had the brilliant idea to extend programmers misery with encoding formats for just a few more years.

**Comment by Frivolous2** [comment]
I'm on a custom ROM, so I'm not sure it is actually a bug in Material Files after the troubleshooting you helped me with. I guess I'll keep the issue closed, and if anyone else gets the same problem there's some info here for them to see

**Comment by zhanghai** [comment]
Thanks for the help here!

Regarding emoji (or Unicode generally): Material Files passes the correct string contents as UTF-8 bytes to the underlying Linux syscalls directly, so I think it's unlikely this app have a bug with SD card but okay with internal storage. Probably exFAT on Android just doesn't have full Unicode support.
