### ISSUE TITLE
Hidden folders not showing up properly in Termux home.

### ISSUE THREAD

**Issue by marchingon12** [zhanghai/MaterialFiles#479]
![Screenshot_20210327_074802_com.termux.jpg](https://user-images.githubusercontent.com/41235480/112712576-e4543e00-8ed0-11eb-924f-4ea87172d8a8.jpg)
![Screenshot_20210327_074806_me.zhanghai.android.files.jpg](https://user-images.githubusercontent.com/41235480/112712577-e6b69800-8ed0-11eb-8fce-cd8d4ada5979.jpg)
![Screenshot_20210327_074809_me.zhanghai.android.files.jpg](https://user-images.githubusercontent.com/41235480/112712579-e8805b80-8ed0-11eb-9967-6eb38659622d.jpg)

As you can see, .vuepress/ exists in the src/ folder, but isn't displayed by Files.  I'm guessing Files might be using `ls` instead of `ls -a`.

**Comment by zhanghai** [comment]
I don't have a good idea - if you have checked "Show hidden files", this app would just display all the child files it got from the provider app. Maybe somehow Termux isn't returning it? And do you have the same issue with other dot directories?

**Comment by marchingon12** [comment]
It seems like it's only affected by Termux and is not a Material Files bug. The native file manager also does not show Dot files/dirs. Dot files and directories show up just fine in internal storage.

![Screenshot_20210328_170954_com.android.documentsui.jpg](https://user-images.githubusercontent.com/41235480/112757110-9cc0d580-8fe8-11eb-9dfd-c213c247f1ea.jpg)
![Screenshot_20210328_170729_me.zhanghai.android.files.jpg](https://user-images.githubusercontent.com/41235480/112757114-a0545c80-8fe8-11eb-888a-ca8940f62d5b.jpg)

**Comment by zhanghai** [comment]
Please open a bug at Termux if it's their issue.
