### ISSUE TITLE
Can't access Android/data/ using the app in Pixel 3

### ISSUE THREAD

**Issue by curche** [zhanghai/MaterialFiles#480]
## Device Info
App version : 1.2.0
Android version : 11
Model : Pixel 3

## Steps to reproduce
1. ensure system and app are uptodate
2. open the app and try to access Android/data/

## Expected Behaviour
access app data files

## Actual Behaviour
RemoteFileSystemException : Cannot launch su shell, exit code -3

## Other details
Had a look at the open issues, and although nothing was mentioned about this particular error, I think this would be related to #384

**Comment by curche** [comment]
also attaching a screenshot

![Screenshot_20210327-191738](https://user-images.githubusercontent.com/72807749/112723798-5ad75700-8f36-11eb-8c6b-f05a009d25be.png)

**Comment by zhanghai** [comment]
You need root access to read that directory directly on Android 11 and this is not a bug but an OS restriction.

Alternatively, you may use Add storage => Add external storage and choose the Android directory, then Material Files will be able to read Android/data through DocumentsProvider mechanism. Note that this workaround is not guaranteed to work forever and maybe broken again on newer Android versions.

**Comment by curche** [comment]
it is indeed sad that Android is starting to restrict this.

> Alternatively, you may use Add storage => Add external storage and choose the Android directory, then Material Files will be able to read Android/data through DocumentsProvider mechanism.

Thanks, this works for now.

I will make the switch to the granting root access in the future when I finally unlock the device. Thanks for the info!
