### ISSUE TITLE
Indication on floating button

### ISSUE THREAD

**Issue by Github-com-foss** [zhanghai/MaterialFiles#490]
show indication (percentage) of delete, move, copy instead of notification
SOLID EXPLORER FILE MANAGER

![unnamed](https://user-images.githubusercontent.com/75672019/113674973-72ea6b80-96d8-11eb-9439-52b8a1465c96.png)
![proxy-image_1](https://user-images.githubusercontent.com/75672019/113674977-754cc580-96d8-11eb-80c8-f93d6f720992.jpeg)

**Comment by zhanghai** [comment]
This is against Material Design guidelines and too ugly. You may just look at the notification for progress.
