### ISSUE TITLE
Editing Permission issues on SD-card

### ISSUE THREAD

**Issue by xerus2000** [zhanghai/MaterialFiles#495]
If I try to edit any text-files on my SD-card and then save them I get an error: "cannot launch su-shell", even though the permissions are all there :/

**Comment by factorial52** [comment]
You can't edit the permissions because you are not the file owner. I'm not sure if that's what you're getting at though.

**Comment by zhanghai** [comment]
How were you accessing your SD card? Because the "cannot launch su-shell" error is only shown when the native file system returns `EACCES` for access denial and the app tried to perform the action with root. Maybe your SD card is read-only when accessed via the native file system. Could you try accessing it with the `Add storage...` option and then `External storage`?

**Comment by xerus2000** [comment]
Yep, had to give permission via that dialog, thanks :)
Maybe the app should be a little more assistive here?

**Comment by zhanghai** [comment]
The general advice is to always use the Add storage -> External storage to access SD card. I'm actually surprised that the native FS provides RO access to SD card, and IIRC it's no longer the case on newer releases of Android.

**Comment by xerus2000** [comment]
I'm using Android 8, and the SD-card showed up in the drawer by itself.

**Comment by zhanghai** [comment]
Oh. Maybe I shouldn't have shown the SD card.

**Comment by zhanghai** [comment]
Actually I don't think the app is showing the SD card automatically in the most recent version after I doubled checked the code. Which version of this app are you using?

**Comment by xerus2000** [comment]
1.0.2 (17)

**Comment by zhanghai** [comment]
I see. Please update your app, the most recent release is 1.2.1 and doesn't have this issue - you will need to add your SD card (as RW) manually
