### ISSUE TITLE
建议：统一应用中文名

### ISSUE THREAD

**Issue by ivysrono** [zhanghai/MaterialFiles#496]
在 f-droid 显示为 「质感文件」，但在应用列表中，显示为「文件」，导致与原生文件管理器并列时需要从图标的差别中判断，太难了。
建议统一为「质感文件」。

**Comment by zhanghai** [comment]
英文名 Material Files 太长因此会无法显示完全，很可能只剩“Material…”，因此选择了在启动器里显示为“Files”，中文里则为“文件”。

**Comment by ivysrono** [comment]
> 英文名 Material Files 太长因此会无法显示完全，很可能只剩“Material…”，因此选择了在启动器里显示为“Files”，中文里则为“文件”。

这能否做成选项的？我大量使用搜索来查找应用，两个文件一起出现太痛苦了

**Comment by zhanghai** [comment]
做成选项有些复杂，并且可能只对中文有意义，所以我不太打算做……如果你实在想要的话，可以自己编译一份来满足自己的需求。

**Comment by ivysrono** [comment]
那就算了，我用别的吧。主要是你这个对工作空间支持最好。
