### ISSUE TITLE
Breadcrumb ripple glitch when app bar is collapsed

### ISSUE THREAD

**Issue by LiuJiangshan** [zhanghai/MaterialFiles#497]
https://user-images.githubusercontent.com/13770291/114345584-9576fb80-9b94-11eb-8a43-415350cbebe2.mp4

**Comment by zhanghai** [comment]
Nice observation. I knew this bug but never thought the reproduction is app bar position. The glitch seems to only happen after app bar is collapsed more than a certain height, but I don't know why.

**Comment by LiuJiangshan** [comment]
原因是点击面包屑导航导致CoordinatorLayout重新布局，ripple动画被清除，可以覆盖BreadcrumbLayout的jumpDrawablesToCurrentState为空方法解决
```
class BreadcrumbLayout : HorizontalScrollView {
    override fun jumpDrawablesToCurrentState() {
        // do nothing
    }
    ...
}
```

**Comment by zhanghai** [comment]
It is still weird if the `CoordinatorLayout` only re-layouts when the app bar is collapsed more than a certain height - and even if that case, I think we should look into preventing that re-layout first.

**Comment by LiuJiangshan** [comment]
准确来说不是重新布局导致的，是AppBarLayout的liftOnScroll导致，当AppBarLayout阴影发生变化前会清除背景。
[AppBarLayout.java#L891](https://github.com/material-components/material-components-android/blob/e2c911b9e597ab667a967eaf85792d75bf0c5bab/lib/java/com/google/android/material/appbar/AppBarLayout.java#L891)
所以以下解决方法，我觉得是可行的。
> 原因是点击面包屑导航导致CoordinatorLayout重新布局，ripple动画被清除，可以覆盖BreadcrumbLayout的jumpDrawablesToCurrentState为空方法解决
> 
> ```
> class BreadcrumbLayout : HorizontalScrollView {
>     override fun jumpDrawablesToCurrentState() {
>         // do nothing
>     }
>     ...
> }
> ```

**Comment by LiuJiangshan** [comment]
估计与系统有关，触发重新布局的堆栈来自系统，android12上是正常的。
It is estimated that it is related to the system. The stack that triggers the re-layout comes from the system. It is normal on android12.

**Comment by zhanghai** [comment]
@LiuJiangshan 感谢，我（终于想起来）看了一下这个，`jumpDrawablesToCurrentState()` 的调用栈都是来自 `AppBarLayout.BaseBehavior.onLayoutChild()` 的一个 workaround 的，所以我加了一个如果 `isInLayout` 就跳过的逻辑然后就修好了。
