### ISSUE TITLE
"Remount /system as read-write" does not work with isolated namespaces

### ISSUE THREAD

**Issue by SebiderSushi** [zhanghai/MaterialFiles#506]
Rooting methods oftentimes offer a toggle that allows isolating each root shell's namespace. If this is on the "Remount /system as read-write" functionality fails to work.

At least [Magisk](https://topjohnwu.github.io/Magisk/tools.html#su) offers to run a root shell in the global namespace on demand with the `-mm` option. But in this case running the remount in the same namespace should work i guess.

**Comment by zhanghai** [comment]
This has now been resolved by replacing librootjava with libsu which has a MOUNT_MASTER option. I confirmed with Rikka that Sui services run with global mount namespace as well.

**Comment by SebiderSushi** [comment]
I didn't have to use this for a long while but i finally got back around to test this. Thank you very much for fixing.
