### ISSUE TITLE
Integration with DiskUsage

### ISSUE THREAD

**Issue by HansCronau** [zhanghai/MaterialFiles#512]
The FOSS app [DiskUsage](https://github.com/IvanVolosyuk/diskusage) displays the folders and files on the filesystem proportional to filesize. The user can select a folder and open it in any file browser supporting integration with DiskUsage. If none are found, DiskUsage displays a dialog titled: "Missing compatible file manager". It advises users to ask their favourite file manager developer for integration with DiskUsage (which I'm doing now) or to install Solid Explorer or IO File Manager. 

I would like to note the possible opportunity of getting the DiskUsage devs to mention Material Files in return. Since it would be the only FOSS file manager listed, I can imagine they would like would even like to suggest Material Files over the alternatives. The current favourite seems to be Solid Explorer, which in the dialog is given a dedicated "Install Solid Explorer" button, that takes the user to its store page.

**Comment by zhanghai** [comment]
It seems this app should already be supporting DiskUsage looking at [its code](https://github.com/IvanVolosyuk/diskusage/blob/f7ec279f7fa25086458ac572b1ad9d10cca44a57/app/src/main/java/com/google/android/diskusage/DiskUsage.java#L332):

```java
      intent = new Intent(Intent.ACTION_VIEW);
      intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
      intent.setDataAndType(uri, "inode/directory");
```

And [Material Files code](https://github.com/zhanghai/MaterialFiles/blob/d85fc254e8cd9ad2d0cf44a9a919344c04e531ea/app/src/main/AndroidManifest.xml#L54)

```xml
            <intent-filter tools:ignore="AppLinkUrlError">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="inode/directory" />
                <data android:mimeType="resource/folder" />
                <data android:mimeType="vnd.android.document/directory" />
            </intent-filter>
```

What did you actually observe when having Material Files installed and opening a directory in DiskUsage?

**Comment by HansCronau** [comment]
Hi @zhanghai! In DiskUsage, after selecting a folder and pressing the "sʜᴏᴡ" button, the following dialog appears:
![MaterialFiles - Integration with DiskUsage - Dialog Missing compatible file manager](https://user-images.githubusercontent.com/977860/122442724-286e5080-cf9f-11eb-96c2-5bff317db4e2.png)
Do you think it could be an issue on DiskUsage's end?

**Comment by zhanghai** [comment]
Yes. Could you ask the DiskUsage to take a look at my previous comment?

**Comment by HansCronau** [comment]
@zhanghai I created [an issue on DiskUsage's Github](https://github.com/IvanVolosyuk/diskusage/issues/72). The developer, @IvanVolosyuk, has responded there. Based on his comment, would you be able to determine what changes are needed in which app to support integration?

**Comment by xeruf** [comment]
Any news? Just experienced this as well :/

**Comment by zhanghai** [comment]
@xeruf See IvanVolosyuk/diskusage#72
