### ISSUE TITLE
No SAF manager detected

### ISSUE THREAD

**Issue by dmlemos** [zhanghai/MaterialFiles#513]
Hi. I'm using [OAndBackupX](https://github.com/machiav3lli/oandbackupx) 6.0.0 on `Lineage 17.1`. Unfortunately upon launching the application it says `There's no file manager to manage SAF`.
Built-in `Files` app disabled. Any clue why is it not detecting this app?

**Comment by zhanghai** [comment]
Because DocumentsUI is the SAF manager, this app is just a client.

**Comment by finedust** [comment]
> Because DocumentsUI is the SAF manager, this app is just a client.

Any suggestion for a FOSS app which can serve as SAF manager alternative?
