### ISSUE TITLE
Question : How did you get that Material Theme?

### ISSUE THREAD

**Issue by victorbnl** [zhanghai/MaterialFiles#518]
Hello! I'm loving the style of your app, which reminds me Google's Material Theme, used on other FOSS apps like Notally, but also on GMail for example. Especially on the drawer.

How did you get it? Is it like a theme you just import and it does everything automatically? Did you have to style everything by hand to recreate the design?

Thanks!

**Comment by zhanghai** [comment]
Please ask programming questions on websites like StackOverflow. As a short answer, the Google-like style is recreated by hand but the general theming and widgets are from [Material Components for Android](https://github.com/material-components/material-components-android)
