### ISSUE TITLE
Introduce ShizukuProvider to support R/W in Android/data folder for non-root users

### ISSUE THREAD

**Issue by sky96111** [zhanghai/MaterialFiles#519]
Android/data is not read/writeable for third part apps in Android 11, while some apps like TIM and Wechat store user save file in their own folders.

Material Files supported Sui in https://github.com/zhanghai/MaterialFiles/commit/91dfe5add169d82d16b125d7817aa5304f432df0 , because Sui and Shizuku shares the same API, it can just add 
```
<provider
     android:name="rikka.shizuku.ShizukuProvider"
     android:authorities="${applicationId}.shizuku"
     android:multiprocess="false"
     android:enabled="true"
     android:exported="true"
     android:permission="android.permission.INTERACT_ACROSS_USERS_FULL" />
```
in `AndroidManifest.xml` to support Shizuku. Shell permissions are sufficient to access and write data directories, it will improve the experience of non-root users.

It may be better to open a PR not a issue... But I does not know to build Android apps and can not test by my own. So I open the issue, can it be taken into consideration?

**Comment by zhanghai** [comment]
This is unnecessary - you can just use Add storage -> External storage and select the sdcard/Android directory.

**Comment by sky96111** [comment]
> This is unnecessary - you can just use Add storage -> External storage and select the sdcard/Android directory.

Content URL seems less efficient in loading files, and Material Files does not use content url to open TIM/Wechat folder as default in sidebar.
Shell privilege can also read /data and /system , which Content URL cannot provide. So I think Shizuku support may be necessary..

**Comment by sky96111** [comment]
Thanks for your explain!

I tried to fork this repo and introduce ShizukuProvider, but except permission request, nothing works. It looks like most features are designed with isSui... I am not specialized in Android, so no further modification I can do to support it.
Thanks again for creating such an amazing app! And wish one day it can be put on the todo-list!

**Comment by IntoTheVoid-900** [comment]
> This is unnecessary - you can just use Add storage -> External storage and select the sdcard/Android directory.
@zhanghai 

This is no longer functional, at least for me in Android 13 on the Pixel 6 stock ROM.

When trying to add the Android/data directory, you cannot see any of its subfolders

**Comment by sky96111** [comment]
Yes, Google removed SAF Android/data | Android/obb access in Android 13
The method above is not available now

**Comment by IntoTheVoid-900** [comment]
Is there any other way? As an interim solution, I have been using bash commands through Termux with Shizuku, but its not very practical on a mobile keyboard

**Comment by sky96111** [comment]
System DocumentUI is a non-shizuku way to access restricted Android folders, but it is not fully featured. You cannot even copy file into those folders

**Comment by IntoTheVoid-900** [comment]
Yeah, I think that's what Amaze uses, since I wasn't able to copy files into the folders when I was using it. I have tried a lot of options today, and MiXplorer & Termux with Shizuku are the only ones that really worked.
