### ISSUE TITLE
[Feature Request] Disks properties

### ISSUE THREAD

**Issue by victorbnl** [zhanghai/MaterialFiles#524]
This would be cool to have properties, or at least more advanced properties than now, on disks. This could include things like the disk usage, the disk size, the filesystem...

**Comment by zhanghai** [comment]
This app is a file manager instead of disk manager, similar to how [GNOME Files](https://www.wikiwand.com/en/GNOME_Files) is different from [GNOME Disks](https://www.wikiwand.com/en/GNOME_Disks), so you should probably find/create another app for this.
