### ISSUE TITLE
Add shortcut to Android 11's built-in file manager

### ISSUE THREAD

**Issue by KaranKad** [zhanghai/MaterialFiles#532]
Without root access I cannot open `Android/data` folder but by using Android 11's built-in file manager it's possible. So, having a shortcut to the built-in file manager inside this app would be great.
I currently use this app to access the built-in file manager.
https://play.google.com/store/apps/details?id=com.marc.files&hl=en_US&gl=US

**Comment by zhanghai** [comment]
See https://github.com/zhanghai/MaterialFiles/issues/480#issuecomment-808802697 for how to access `Android/data` on Android 11+.

The built-in file manager is a different app from this one, so I think using another tiny app to access it on systems where it is hidden is the right approach.

**Comment by KaranKad** [comment]
Adding `Android/data` as external storage did the job. I'll close this issue then. Also, I really appreciate this file manager, it looks really neat and has good features. 😊
