### ISSUE TITLE
不支持過大的txt

### ISSUE THREAD

**Issue by Rnager** [zhanghai/MaterialFiles#534]
![20210719_112045](https://user-images.githubusercontent.com/72384286/126097992-49912fdf-faa1-4c9e-9742-49f2a4121b4a.jpg)
打開的txt如下
https://drive.google.com/file/d/19L7YAB7-gs0fkLdkdNfveiEUIJZYGAcZ/view?usp=drivesdk

**Comment by zhanghai** [comment]
是的，不支持，因为大于 1M 的文本量会导致单个 EditText 难以承载，需要别的方法来实现这个文本编辑器，并且会很麻烦。在这种情况下还是建议使用单独的文本编辑应用，因为这个应用只是一个文件管理器。
