### ISSUE TITLE
Bad file select contrast with black dark theme

### ISSUE THREAD

**Issue by cewbdex** [zhanghai/MaterialFiles#535]
![Screenshot_2021-07-19-10-48-38-568_me zhanghai android files](https://user-images.githubusercontent.com/9021297/126157256-d8cf4e76-8747-46a1-b963-06fc0696e2c9.jpg)
When I select files it's really barely visible.

**Comment by zhanghai** [comment]
Which primary color are you using? (Could you provide a screenshot of the color picker in app settings, which shows a check mark on the selected color?)

For me the default primary color seems to work fine under black theme:

![Screenshot_20210719-123332](https://user-images.githubusercontent.com/4469895/126216645-266eb42d-3ed9-43d8-8a55-ea4159825049.jpg)

**Comment by cewbdex** [comment]
![Screenshot_2021-07-20-09-05-06-550_me zhanghai android files](https://user-images.githubusercontent.com/9021297/126276822-42281b0b-2251-427d-be92-6964427f01f6.jpg)
![Screenshot_2021-07-20-09-05-48-975_me zhanghai android files](https://user-images.githubusercontent.com/9021297/126276876-385677ef-02f2-41e9-8da9-215c9b31dd34.jpg)

I thought and maybe it's MIUI what does that? Would not be the first time that it screws app theming. For the record I'm using MIUI 12.5.1.0 on UMI, files 1.2.1 from F-Droid.

**Comment by zhanghai** [comment]
Ah yes, I guess it is the MIUI's night mode issue that messed up the colors. This is how the colors look on my OnePlus device (My Pixels also show the same colors):

![Screenshot_20210720-002844](https://user-images.githubusercontent.com/4469895/126280060-454bc186-8e2c-4492-ac8b-ba53f22b37de.jpg)

I heard other users reporting that turning off something like "MIUI optimizations" for this app might fix similar issues, not sure about this one though.

**Comment by cewbdex** [comment]
I tried various settings of the system/app, but nothing really helped. Very strange.

![Screenshot_2021-07-20-15-00-49-506_com android settings](https://user-images.githubusercontent.com/9021297/126328617-f00cdfab-ca01-4ab6-8796-32dfeceffd3f.jpg)

**Comment by zhanghai** [comment]
I agree, not sure what MIUI has modified in this case. I don't have any MIUI device so unfortunately I can't test or fix this 🙁
