### ISSUE TITLE
View/Extract CBZ and CBR files similar to ZIP and RAR

### ISSUE THREAD

**Issue by curche** [zhanghai/MaterialFiles#537]
### Description of Suggestion
The app currently is able to view and extract ZIPs which is really helpful. It'd also be nice to have the same view and extract options for CBZ (Comic Book ZIP) and CBR (Comic Book RAR)
afaik CBZ are the same as ZIPs except for the separate file extension (and likewise for CBR and RAR). I was able to rename a .cbz file to .zip and the app detected it and was able to view/extract it without issues.

### Other Details
CBRs might have some issues as RAR with RAR5 but I don't use them a lot and mostly just stick to CBZ/ZIP

**Comment by zhanghai** [comment]
I've marked CBR and CBZ as ebook files so they will get a better icon. However, marking them as archives would mean that they will always be opened directly within Material Files app, similar to ZIP and RAR files, without the option to view them with another app. In fact, files like DOCX and PPTX are also actually ZIP files, but nobody would expect them to be opened as ZIP files by default, and I believe these comic book formats are in a similar situation, so I think they shouldn't be marked as archive as well.
