### ISSUE TITLE
Documents provider

### ISSUE THREAD

**Issue by UltraBlackLinux** [zhanghai/MaterialFiles#538]
Hey there,
I'd like to disable my Files app and replace it with Material Files, though apparently MF needs a document provider for that (https://github.com/MuntashirAkon/AppManager/issues/525#issuecomment-885893154)
Please implement one! ;)
Thanks!

**Comment by zhanghai** [comment]
Please don't do that, DocumentsUI is a core part of the system and Material Files never intended to replace it.
