### ISSUE TITLE
Any plans to add more network storage supports?

### ISSUE THREAD

**Issue by ElTopo** [zhanghai/MaterialFiles#541]
Hello,

Currently for network storage, MF only supports SMB.

Do you have any plans to add support for more network storages?

For examples, the other file manager I am using also supports:
1. FTP (to connect to ftp servers);
2. SFTP/SSH (to connect SFTP/SSH servers);
3. WebDAV;
4. other cloud services, like Dropbox/Google Drive/OneDrive/box (but I have to admit that I never access these cloud storages from a file manager).

btw, isn't it better to start an http server for sharing files instead of ftp server? I heard that Firefox will stop supporting ftp servers soon.

**Comment by zhanghai** [comment]
Please search for the issue list for each item you mentioned.

For HTTP server, you can file a new feature request.
