### ISSUE TITLE
The internal storage icon is incorrect

### ISSUE THREAD

**Issue by Nathan-008** [zhanghai/MaterialFiles#553]
Hello,

From the hamburger menu (side menu), the internal storage icon is an SD card icon (see image) instead of a phone icon (see icon).

Image:

![Screenshot_20210810-142257_Material Files~2](https://user-images.githubusercontent.com/88719839/128867603-473a2a22-3f01-4738-9132-26826575d937.png)

Icon:

![icons8-android-96](https://user-images.githubusercontent.com/88719839/128867711-b40c5b83-1007-4d38-a4ed-e2cd06d140d4.png)

**Comment by zhanghai** [comment]
The internal storage is also known as "emulated SD card", and you can even access it under the `/sdcard` path name (e.g. with adb shell), so I think it makes sense to use the SD card icon for it. On the other hand, the phone icon is used for the real device root directory (which requires root access though).

**Comment by Nathan-008** [comment]
> The internal storage is also known as "emulated SD card", and you can even access it under the `/sdcard` path name (e.g. with adb shell), so I think it makes sense to use the SD card icon for it. On the other hand, the phone icon is used for the real device root directory (which requires root access though).

OK thanks anyway!

**Comment by sheeepdev** [comment]
@zhanghai This makes sense, but its still wierd seeing two "sd card" icons. Maybe you could change the icon for internal storage to include a small phone icon in the corner or something like that
