### ISSUE TITLE
［Requirements］Unable to quickly find the storage path of QQ/WeChat and so on.

### ISSUE THREAD

**Issue by ODBLK** [zhanghai/MaterialFiles#554]
I remember that the previous version can open the QQ path in the standard folder option, but it has disappeared now.
![Screenshot_20210811-154432.jpg](https://user-images.githubusercontent.com/25927859/128990122-ec75d8de-d3a2-4600-afe3-9b79864b7ca3.jpg)

**Comment by zhanghai** [comment]
It is removed only when runing on Android 11+ becauase it will require root to access and caused a lot of confusion for non-root users. Please manually bookmark these folders using your preferred way to access (SAF or root).
