### ISSUE TITLE
Cannot add an SD card

### ISSUE THREAD

**Issue by benoit-sbr** [zhanghai/MaterialFiles#556]
Hi,

This is probably a stupid question but here goes: I can't browse my SD card in the app (though I can in Google Files for example). I tried to add an external storage source but it doesn't show. What should I do to add my SD card in the app?

**Comment by zhanghai** [comment]
Do you mean your physical SD card?

Adding an external storage is the right way to go - can you see it in the left drawer of the system file picker (other users reported they were able to find it)? Also maybe try clicking the three-dot menu in the system file picker and make sure something like show phone storage or similar is selected.

**Comment by benoit-sbr** [comment]
Dear zhanghai,

Thank you very much for your quick reponse. I have been able to add the physical SD card now!

Your app looks great btw, I'm glad I stumbled upon it.
