### ISSUE TITLE
black video thumbnail solution

### ISSUE THREAD

**Issue by dikasetyaprayogi** [zhanghai/MaterialFiles#557]
from what i see, im assumed the process take the beginning of a video to make a video thumbnail.

the problem arise if the video had a black opening or transtition in the beginning, this will resulted in undesirable black video thumbnail (screenshot attached).

an solution would be to increase video capture time (10 second seek or more would be a safe bet).

or better yet we can implement linux ffmpegthumbnailer standard (10% seek) so my video thumbnail in linux computer and in material files will be the same.

thanks for your consent.

![Screenshot_20210812-172748_Material_Files](https://user-images.githubusercontent.com/33314785/129184281-4a81611c-99da-4371-9c25-9f6acfa1268a.png)

**Comment by zhanghai** [comment]
Note that GNOME Nautilus uses totem-video-thumbnailer by default which is trying multiple frame locations (`1/3`, `2/3`, `0.1`, `0.9`, `0.5`) - see also https://gitlab.gnome.org/GNOME/totem/-/blob/master/src/totem-video-thumbnailer.c#L543 .

However, `coil-video` currently only supports absolute frame locations: https://github.com/coil-kt/coil/tree/main/coil-video

**Comment by dikasetyaprayogi** [comment]
for anyone interested, i think this problem can be solved by specify the time code of the frame to extract in "coil-video", maybe a 5 second or higher would do.

**Comment by zhanghai** [comment]
That will not work because we will have videos shorter than the specified time. We will need `coil-video` to support relative frame locations.

**Comment by zhanghai** [comment]
The thumbnail will be fetch at 1/3 of the total duration in the next app version.
