### ISSUE TITLE
Feature Suggestion. 

### ISSUE THREAD

**Issue by dariusity** [zhanghai/MaterialFiles#558]
Isit possible to add applications with some basic features such as uninstall or preferably back up (as .APK file)? And isit possible for me to adjust the height of the columns? The texts seem too far apart and wasting screen pixels. Cheers.

**Comment by zhanghai** [comment]
The first suggestion qualifies a entire standalone app and there are actually such apps, e.g. https://github.com/MuntashirAkon/AppManager .

The item height is coming from Material Design so adering to the design spec, I don't have the plan to change it. (I have to admit Material Design looks better on devices with a larger screen though.)
