### ISSUE TITLE
When editing SFTP server the name will be reset

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#561]

**Comment by anedroid** [comment]
I can confirm this issue on Android 11 (LineageOS 18.1.20210906 with microG), Moto g7 power (ocean), root

**Comment by linsui** [comment]
1. Long tap on a SFTP storage with name
2. Save
3. The name is reset

**Comment by Valdnet** [comment]
The same problem on Android 10. After saving the SFTB server settings and re-editing, the saved name is not read.

Apps:
Android 10
Material Files 1.3.1
