### ISSUE TITLE
Can't access SFTP server after restart network

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#562]
1. Connect to SFTP
2. Restart network
3. Try to open SFTP external storage
4. See error `java8.nio.file.FileSystemException: ... : net.schmizz.sshj.transport.TransportException: Broken transport; encountered EOF`.

It can't connect to SFTP server anymore unless I restart MaterialFiles.

**Comment by thomas2403** [comment]
I think, this can be related. 

1. Add a new SFTP server , connection is OK.
2. Close MaterialFiles, wait for some hours.
3. Open MaterialFiles and trying to connect to SFTP server results in an error.
4. Goto Setting --> Apps and force close Material Files and the connection work again

![Screenshot_20210814-195858_Material_Files](https://user-images.githubusercontent.com/17723660/129456452-dc7ab71a-8421-4b20-91f6-e605284ccc29.png)

**Comment by zhanghai** [comment]
What is the "Restart network" step? For me on a device without cellar data, simply tuning off and then turn on WiFi didn't reproduce this for me.

Meanwhile, is this reproducible with the [test.rebex.net](https://test.rebex.net/) server? I'm using this public SFTP server for quick testing and its credentials are `demo:password`.

**Comment by linsui** [comment]
I just simply tuning off and then turn on WiFi...

**Comment by linsui** [comment]
With 4G and the test server I can reproduce this error. I just turn off and on the mobile data.

**Comment by linsui** [comment]
Oh, I forgot to close my vpn before testing. Without vpn I got an error same as thomas2403.

**Comment by Thanayaby** [comment]
Pot

**Comment by zhanghai** [comment]
Should be fixed in 1842f34.

**Comment by linsui** [comment]
Just wondering why it's not fixed in https://github.com/zhanghai/MaterialFiles/commit/41a207a62dba1b2b50b1278a544fd0824a65142b but https://github.com/zhanghai/MaterialFiles/commit/1842f34a292f740a407c5b63f8e938341c3629e1.

**Comment by zhanghai** [comment]
Oh, I pasted the wrong hash. It shoud indeed be 41a207a.
