### ISSUE TITLE
I can't add the default dir of DocumentUI

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#563]
When I add external storage, I can't add the default path. I need to go to another path then go back to the first path.

**Comment by zhanghai** [comment]
Please provide your device model and system version. I cannot reproduce this on my Pixel 4 XL running Android 11.

Meanwhile, this sounds more like a bug in your DocumentsUI because the behavior in it seems inconsistent.

**Comment by linsui** [comment]
I'm running LineageOS 18.1 Android 11on Mi 6.

**Comment by zhanghai** [comment]
Could you add a screenshot showing the "can't add the default path" case and the "go back" case?

**Comment by linsui** [comment]
![IMG_20210815_084347](https://user-images.githubusercontent.com/36977733/129463594-01ae5629-3e04-4ea2-b96a-38c7fb21516d.jpg)
![IMG_20210815_084418](https://user-images.githubusercontent.com/36977733/129463599-58ac1f09-fb9c-4290-b286-f79ed124cf7d.jpg)

**Comment by zhanghai** [comment]
I see, thanks for the screenshots. I tested again on my Pixel 4 XL running Android 11 and I'm always able to select the directory upon first opening it. So this looks very likely a bug in DocumentsUI on LineageOS for your device and maybe you can try to open a bug in their issue tracker.

**Comment by linsui** [comment]
Thanks!
