### ISSUE TITLE
［功能请求］网格视图

### ISSUE THREAD

**Issue by abechief** [zhanghai/MaterialFiles#566]
虽然在手机上网格视图显得不那么重要，但是在大屏设备上，使用网格视图往往能够提供更好的效率，希望能够支持切换成网格视图这个功能
![Screenshot_20210816-170610](https://user-images.githubusercontent.com/54495639/129539213-a6a1a54c-74b0-4a69-b860-acb7cf48d37b.jpg)

**Comment by linsui** [comment]
https://github.com/zhanghai/MaterialFiles/issues/152
