### ISSUE TITLE
/data/system 目录下会高频刷新列表导致界面持续闪烁

### ISSUE THREAD

**Issue by zhaobozhen** [zhanghai/MaterialFiles#567]
如下视频
https://user-images.githubusercontent.com/25247117/129564256-df518d67-c829-4084-807d-dbbc386ac7bf.mp4

**Comment by reiuyfan** [comment]
Linegae 18.1 复现失败 猜测可能是此目录下某个文件正在被不停写入 使用 cat /dev/urandom >> /sdcard/test 后观察 /sdcard 可复现

**Comment by zhanghai** [comment]
是的，大概什么东西在不停地写那个目录。界面的“闪烁”是目录内容更新后应用重新加载了它们的提示。

Yes, probably something kept wrtiing that directory. The flashing is an indicator that contents in the folder are updated and the app went through reloading them.
