### ISSUE TITLE
Timeout while connect to root process

### ISSUE THREAD

**Issue by dostup2055** [zhanghai/MaterialFiles#571]
Problem when opening the root "/" folder.
My device:
Xiaomi Redmi Go 1/8 (Qualcomm Snapdragon 425)
Android 10/LineageOS 17.1 GSI firmware (lineage-17.1-20210321-UNOFFICIAL-treble_arm_avS)
Magisk: 20.4/app 22.1
me.zhanghai.android.files 1.3.1.25 f-droid version (14.08.2021)

Other file managers work with the root function. For example "Ghost Commander"(FOSS), "X-plore"(Proprietary)
log: [log.txt](https://github.com/zhanghai/MaterialFiles/files/7033249/log.txt)

![1](https://user-images.githubusercontent.com/56089755/130478103-bc659449-c407-4a75-ade1-84b9187dd13c.jpg)

**Comment by sheckandar** [comment]
Same issue here after upgrading Magisk to 24.1 and enabling Zygisk.

**Comment by sheckandar** [comment]
After looking around the Internet, I installed Sui module for Magisk and the file manager has root access again.

**Comment by zhanghai** [comment]
Yes Sui can be the temporary workaround. I'll implement #348 in the next release.

**Comment by Redjard** [comment]
I have that problem, but only for secondary users. I assume whatever this is got fixed with this issue too?

**Comment by zhanghai** [comment]
It's a generic failure for not able to get the root process of this app running. The root cause can be anything.

**Comment by ildar** [comment]
> It's a generic failure for not able to get the root process of this app
running. The root cause can be anything.

Unfortunately.

I see RemoteFileSystemException in adb logcat but nothing related above.
su-ed process doesn't seem to report anything over adb.
> 05-23 10:53:06.604  5156  5156 D su      : starting daemon client 10316
10316
> 05-23 10:53:06.644  5158  5158 D su      : connecting client 5154
> 05-23 10:53:06.686  5161  5161 D su      : remote pid: 5154
>  05-23 10:53:06.719  5162  5162 D su      : remote pts_slave:
> 05-23 10:53:06.748  5164  5164 D su      : remote uid: 10316
> 05-23 10:53:06.780  5165  5165 D su      : remote req pid: 23736
> 05-23 10:53:06.811  5166  5166 D su      : remote args: 2
> 05-23 10:53:06.840  5168  5168 D su      : waiting for child exit
> 05-23 10:53:06.844  5170  5170 D su      : su invoked.
> 05-23 10:53:06.874  5171  5171 D su      : sending code
> 05-23 10:53:06.906  5173  5173 D su      : client exited 0
> 05-23 10:53:06.910  5172  5172 D su      : child exited

Using AOSP 12 with Phh SU.
Worth a new issue to open?
