### ISSUE TITLE
Use SAF to access Android/data folder without root on Android 11+

### ISSUE THREAD

**Issue by Whisprin** [zhanghai/MaterialFiles#572]
On Android 11+ access to Android/data is blocked by default. However, the folder can be accessed through the Storage Access Framework without root after the user explicitly grants permission.

Please allow access to /sdcard/Android/data without root on Android 11.

Some more details and examples of other file manager with this feature can be found here:
https://forum.xda-developers.com/t/android-11-cannot-access-android-data-folder.4225293/
https://www.reddit.com/r/Android/comments/j3zgmm/managing_files_in_the_androiddata_folder_on/
https://github.com/SimpleMobileTools/Simple-File-Manager/issues/490

**Comment by zhanghai** [comment]
Isn't this already implemented as `Add storage` > `Add external storage`?

**Comment by Whisprin** [comment]
Thanks, that does work indeed :+1: 

Maybe it's a good idea to show the user a message about the "Add external storage" feature when otherwise the "permission denied" appears.
