### ISSUE TITLE
Could you please provide full path to files, if possible.

### ISSUE THREAD

**Issue by anishmittal2020** [zhanghai/MaterialFiles#573]
Could you please provide full path to files, if possible. I navigated to a markdown file in **Material files** and tried to open with markdown editor called as **Markor**.

![image](https://user-images.githubusercontent.com/42092626/130974404-8d9dc656-0538-46c7-9204-1782e4da47a1.png)

**Comment by zhanghai** [comment]
I did provide the real path and it can be queried with the standard `MediaStore.MediaColumns.DATA` column for the content URI ([source](https://github.com/zhanghai/MaterialFiles/blob/e23299998dea2b05c314137de3ad46f1e58f9373/app/src/main/java/me/zhanghai/android/files/file/FileProvider.kt#L116)). Please ask Markor to support `MediaStore.MediaColumns.DATA`.
