### ISSUE TITLE
Why folders/(folders+ files) share failing when we choose some particular services from android share menu?

### ISSUE THREAD

**Issue by shuvashish76** [zhanghai/MaterialFiles#575]
Sreps to Reproduce
1. Select some folders/(folders+ files)
2.  click on upper-right-cornor 3 dot icon
3.  Share

It shows some error while sending Folders/ (folders+files) from Material files through Nitroshare/Trebleshot (or any similar filesharing service) to another android device.
Similar error when sending Folders/ (folders+files) from KDEconnect android to pc.
Same goes for Bluetooth file transfer.

---

https://user-images.githubusercontent.com/48226312/131148383-0c3d997f-25f8-4928-be25-82dfca3db71f.mp4

Not even possible to directly send from Nitroshare itself.

![Screenshot_2021-08-27_19-48-03](https://user-images.githubusercontent.com/48226312/131149749-6891194a-0d67-4ab2-8f34-2a4fbb18b6fa.png)

screenshot of 2nd (receiving) device👇🏿
![20210827_194053](https://user-images.githubusercontent.com/48226312/131149956-a79875cc-9e37-4680-820a-0608ade53ae6.jpg)
![20210827_200838](https://user-images.githubusercontent.com/48226312/131149965-57dfa5d5-1a7d-4181-8f21-0045428404b4.jpg)

---

But if we choose Gmail, Winrar, Google Drive etc from android share menu then it picks up folders for some reason🤷🏿‍♂️

![Screenshot_2021-08-27-20-30-51](https://user-images.githubusercontent.com/48226312/131148281-bc218e48-7c77-42dc-89fc-c87ad689000a.jpeg)

I don't understand whats the issue when we pick folders/(folders+ files) for filesharing apps like Nitroshare/Trebleshot/KDEconnect/Bluetooth etc🙄

https://github.com/TeamAmaze/AmazeFileManager/issues/2753

**Comment by k3b** [comment]
@shuvashish76 android does not allow to [browse files in shared  folders when using the FileProvider](https://stackoverflow.com/questions/48062097/how-to-open-a-directoryfolder-in-android-using-file-provider)
