### ISSUE TITLE
[Bug] RAR File, whose Version is Higher than v5, Decompression Failed

### ISSUE THREAD

**Issue by entr0pia** [zhanghai/MaterialFiles#579]
Error Massage:
```
me.zhanghai.android.files.provider.archive.archiver.ArchiveException: com.github.junrar.exception.UnsupportedRarV5Exception
```

**Comment by zhanghai** [comment]
It's not a bug, just that junrar doesn't support RAR 5. If you can ask the upstream https://github.com/junrar/junrar to support RAR 5, I'll happily update my app to support RAR 5 as well.
