### ISSUE TITLE
Understandable error message information

### ISSUE THREAD

**Issue by Valdnet** [zhanghai/MaterialFiles#581]
I propose to add understandable and user-friendly error messages that will be understood by any user of the application for:

Steps:

1. Smartphone not rooted.
2. Select "Root" from the menu.

![obraz](https://user-images.githubusercontent.com/47037905/132564887-718d84a4-7910-4d36-949e-81103a1dc35a.png)

Steps:

1. Select the XAPK installation file.
2. Install from the "Material Files" application.

![obraz](https://user-images.githubusercontent.com/47037905/132564982-0fa7be47-5eb6-4681-ba6a-4b3fc6f98462.png)

Steps:

1. Create a directory.
2. Open it up.
3. Exit the directory.
4. Delete it.
5. Select this directory from the navigation path.

![obraz](https://user-images.githubusercontent.com/47037905/132726091-bacd0c63-8cc0-4fe3-9637-323c60dcc51e.png)

App:
Material Files v1.3.1

**Comment by zhanghai** [comment]
Duplciate of #150 - though it's hard to create a string for every possible error and localize it.
