### ISSUE TITLE
Multiple selection of files or folders

### ISSUE THREAD

**Issue by Valdnet** [zhanghai/MaterialFiles#583]
Steps:

1. Create several files or folders in one folder.
2. Select one file or folder.
3. Select the second file or folder.

When selecting a second file or folder, the action only appears for the selected file or folder. Multiple items cannot be selected at the same time.

Examples:

- When you try to select a second folder, the previously selected folder opens
- When you try to select a second file, the previously selected file is started
- When you try to select the second APK installation file, a message appears about selecting an action for the previously selected file

App:
Material Files v1.3.1

**Comment by zhanghai** [comment]
The standard steps multi-selection on Android is to start the multi-selection mode by long-pressing one item, and then tapping (instead of long pressing) additional items. This apps adds the ability to long press a folder to open it and further select files inside.

**Comment by Valdnet** [comment]
@zhanghai I will add, to get the described error, you should tap not on the folder or file icon, but on its **name**.

**Comment by Valdnet** [comment]
@zhanghai I still believe this is an application bug 😉.

Steps:

1. Tap and hold on the file **name** (not on the file icon).
2. Tap and hold on the **name** of the second file (not on the file icon).

# Actual behaviour:
When you tap and hold on the **name** of a second file to be selected, the application wants to run the previously selected file.

# Expected behaviour:
If you tap and hold on to the **name** of the second file (not on the file icon), then the second file should be marked.

Apps:
Android 10
Material Files 1.4.0
