### ISSUE TITLE
[Feature request] progress bar

### ISSUE THREAD

**Issue by soracqt** [zhanghai/MaterialFiles#584]
I like this app very much. thank you.
I wish there was a progress bar when copying/deleting files/folders.

**Comment by soracqt** [comment]
I found this issue later.
If this is a duplicate, please close it. sorry.

**Comment by zhanghai** [comment]
There is a progress bar in the file operation notification - you can also cancel an ongoing file operation there.

**Comment by soracqt** [comment]
thank you.
