### ISSUE TITLE
[BUG] No access to SD card possible

### ISSUE THREAD

**Issue by 3Domse3** [zhanghai/MaterialFiles#586]

**Comment by zhanghai** [comment]
Could you give more details? e.g. is there any error message, is it a physical SD card, the app version, and the system version/device model you are using.

**Comment by 3Domse3** [comment]
Galaxy S10, Android 11, physical µSD-card

I couldn't find/get access to the whole SD card directory. Only the internal storage was accessable

**Comment by zhanghai** [comment]
Can you add it with "Add storage" > "External storage" in the drawer?

**Comment by 3Domse3** [comment]
> Can you add it with "Add storage" > "External storage" in the drawer?

This worked. Thanks for the help :D
