### ISSUE TITLE
[Storage Access Framework] Handle DocumentsContract.Root.COLUMN_AVAILABLE_BYTES and COLUMN_CAPACITY_BYTES

### ISSUE THREAD

**Issue by rfc2822** [zhanghai/MaterialFiles#593]
For local storages, the available bytes and capacity is shown in the drawer:

![Screenshot_1632909776](https://user-images.githubusercontent.com/156167/135248280-81130acd-df1a-4118-a0ad-1214b819243f.png)

These information could also be taken from [DocumentsContract.Root.COLUMN_AVAILABLE_BYTES](https://developer.android.com/reference/android/provider/DocumentsContract.Root#COLUMN_AVAILABLE_BYTES) and COLUMN_CAPACITY_BYTES.

**Comment by zhanghai** [comment]
IIRC normal apps can't query roots - only the DocumentsUI app can. Please re-open if this is not the case.
