### ISSUE TITLE
Cannot launch su shell, exit code error -3

### ISSUE THREAD

**Issue by Rag3005** [zhanghai/MaterialFiles#595]
I Have this error in the obb directory, inside Android directory. Please help me
![Screenshot_2021-10-02-20-18-43-03_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://user-images.githubusercontent.com/57812697/135727691-8129bc1e-71a3-4c74-9913-fb9b5b191807.jpg)

**Comment by factorial52** [comment]
This is not a bug in this program. This is the intended behaviour of android. You can gain access by using the menu option 'add storage > external storage'.

**Comment by Rag3005** [comment]
I solved. I had to make the mount point inside the Android directory 
![Uploading Screenshot_2021-10-11-14-05-13-86_29c0a1e3aaa5223e1ffcd3f9ab52a346.jpg…]()

**Comment by Rag3005** [comment]
I solved. I had to make the mount point inside the Android directory
![Screenshot_2021-10-11-14-02-33-94_5734e8eb49b4234b62f913f831715b0f__01__01](https://user-images.githubusercontent.com/57812697/136787884-e97a32d4-cbd0-4538-97fa-76d8b38f685b.jpg)
![Screenshot_2021-10-11-14-05-13-86_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://user-images.githubusercontent.com/57812697/136787885-ad17c415-6464-4491-bab5-dca99369bf8c.jpg)
