### ISSUE TITLE
Use MaterialComponents Material3 theme

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#600]
- [x] Define palette and use `Material3` theme.
- [x] Support MD3 navigation style.
- [x] Navigation alignment on tablet.
- [x] Toolbar elevation/color on tablet
- [x] Secondary text color too close to primary.
- [x] App bar title alignment.
- [x] Menu padding.
- [x] FAB and speed dial.
- [x] Properties dialog `TabLayout`.
- [x] Preference text appearance
- [x] Switch styling.
- [x] `SimpleMenuPreference` styling

**Comment by OxygenCobalt** [comment]
[The Material3 theme in the mainline material components implementation](https://github.com/material-components/material-components-android/releases/tag/1.5.0-beta01) seems to be pretty complete. The big issues are simply regenerating the color schemes for the new color roles and adapting your app to the new typography system.
