### ISSUE TITLE
[SAF] Copy documents: queryChildren doesn't wait for final results

### ISSUE THREAD

**Issue by rfc2822** [zhanghai/MaterialFiles#603]
**Steps to reproduce:**

1. Add a [DAVx⁵ web mount](https://www.davx5.com/manual/webdav_mounts.html) and connect it to Material Files.
2. In Material files, navigate to a Folder that's not in cache (let's call it "Music").
3. Select a subfolder (let's call it "Music/Some Artist") in order to copy it.
4. Copy it with Material Files to Downloads.

**Result:**

Material Files will only copy the first level of folders or even an empty folder.

**Expected result:**

Material Files should copy all sub-subfolders ("Music/Some Artist/Album 1" etc…) and files.

**Supposed reason:**

`DocumentsProvider.queryChildDocuments` may return incremental results (with extra "loading"=true). Material Files seems to take the first cursor as complete result. Instead, when the extra "loading" is true, it should wait until it receives the final result and then use it.

When DAVx⁵ is modified so that it returns the whole result of `queryChildDocuments` in one call, the problem doesn't occur.

**May also be interesting:**

AOSP Files doesn't have this problem. Maybe the code from there could be re-used.

**Comment by c64bob** [comment]
I can confirm this bug.

**Comment by zhanghai** [comment]
The architecture of Java 8 NIO2 File API can't easily accomodate optionally wait for the full result, so I've changed the implementation to always wait for the full result instead. This is what one would observe on desktop file managers like Nautilus anyway.
