### ISSUE TITLE
Add intent for Android to open archive (*.zip, *.tar.gz, *.tar.xz, *.tar.zst, ...)

### ISSUE THREAD

**Issue by evan0greenup** [zhanghai/MaterialFiles#605]
I have notice that MaterialFiles provide a rich set of features toward compressed archive.

It would be awesome if MaterialFile can provide a intent to Android system, whenever, download a archive from web browser, E-mail client, or instant message App, when choose available App to open archive file, it would be nice if MaterialFile App is in the candidate list.

It would be much more convenient for user.

**Comment by zhanghai** [comment]
Duplciate of #726.
