### ISSUE TITLE
[Feature Request] implement a second window

### ISSUE THREAD

**Issue by dmuiX** [zhanghai/MaterialFiles#612]
Would be nice to have a second window, then you can switch between two folders or storages.
The [Solid explorer](https://play.google.com/store/apps/details?id=pl.solidexplorer2) has a very good implementation. Fyi it has other flaws, like not correctly copying stuff on my usb stick, that's why i was looking for alternatives, but i really appreciate its interface, would be nice to see it in this wonderful app =)

**Comment by zhanghai** [comment]
You can use "New window" in the top-right menu, along with the system's task switching.
