### ISSUE TITLE
Native crash 

### ISSUE THREAD

**Issue by Kita2345** [zhanghai/MaterialFiles#614]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'asus/WW_Z00A/Z00A:5.0/LRX21V/2.20.40.206_20170627_2131_user:user/release-keys'
Revision: '0'
ABI: 'x86'
pid: 17269, tid: 17443, name: DefaultDispatch  >>> me.zhanghai.android.files <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x284504
    eax 00284504  ebx f4b6120c  ecx 00000818  edx c7b611c0
    esi c7b500d8  edi 00000818
    xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000013f  xss 0000002b
    eip f47a9c40  ebp c7a000b0  esp cb804b20  flags 00210202

backtrace:
    #00 pc 0017cc40  /system/lib/libpdfium.so (_ZN11CFXMEM_Page5AllocEj+48)
    #01 pc 0017d187  /system/lib/libpdfium.so (_ZN12CFXMEM_Pages5AllocEj+55)
    #02 pc 0017dea8  /system/lib/libpdfium.so (_ZN15CFXMEM_FixedMgr8AllocMidEj+72)
    #03 pc 0017e1fb  /system/lib/libpdfium.so (_ZN15CFXMEM_FixedMgr5AllocEj+91)
    #04 pc 0017e426  /system/lib/libpdfium.so
    #05 pc 0017bebe  /system/lib/libpdfium.so (_ZN13CFX_MemoryMgr5AllocEji+30)
    #06 pc 0017c184  /system/lib/libpdfium.so (FXMEM_DefaultAlloc2+52)
    #07 pc 000f6edb  /system/lib/libpdfium.so (_ZN26CPDF_StandardCryptoHandler10CryptStartEjji+363)
    #08 pc 000f64f7  /system/lib/libpdfium.so (_ZN26CPDF_StandardCryptoHandler12DecryptStartEjj+39)
    #09 pc 001048e6  /system/lib/libpdfium.so (_ZN17CPDF_SyntaxParser10ReadStreamEP15CPDF_DictionaryP13PARSE_CONTEXTjj+326)
    #10 pc 001056c2  /system/lib/libpdfium.so (_ZN17CPDF_SyntaxParser9GetObjectEP20CPDF_IndirectObjectsjjiP13PARSE_CONTEXTi+2770)
    #11 pc 0010594f  /system/lib/libpdfium.so (_ZN11CPDF_Parser21ParseIndirectObjectAtEP20CPDF_IndirectObjectsljP13PARSE_CONTEXT+367)
    #12 pc 001082c8  /system/lib/libpdfium.so (_ZN11CPDF_Parser19ParseIndirectObjectEP20CPDF_IndirectObjectsjP13PARSE_CONTEXT+760)
    #13 pc 000ff080  /system/lib/libpdfium.so (_ZN20CPDF_IndirectObjects17GetIndirectObjectEjP13PARSE_CONTEXT+112)
    #14 pc 000ffd35  /system/lib/libpdfium.so (_ZNK11CPDF_Object9GetDirectEv+69)
    #15 pc 000ffeba  /system/lib/libpdfium.so (_ZNK15CPDF_Dictionary15GetElementValueERK15CFX_ByteStringC+74)
    #16 pc 00100053  /system/lib/libpdfium.so (_ZNK15CPDF_Dictionary9GetStreamERK15CFX_ByteStringC+35)
    #17 pc 000c2e48  /system/lib/libpdfium.so (_ZN9CPDF_Font18LoadFontDescriptorEP15CPDF_Dictionary+920)
    #18 pc 000c6f88  /system/lib/libpdfium.so (_ZN15CPDF_SimpleFont10LoadCommonEv+88)
    #19 pc 000c785b  /system/lib/libpdfium.so (_ZN17CPDF_TrueTypeFont5_LoadEv+27)
    #20 pc 000c3221  /system/lib/libpdfium.so (_ZN9CPDF_Font4LoadEv+209)
    #21 pc 000c8436  /system/lib/libpdfium.so (_ZN9CPDF_Font11CreateFontFEP13CPDF_DocumentP15CPDF_Dictionary+358)
    #22 pc 000dbc6c  /system/lib/libpdfium.so (_ZN16CPDF_DocPageData7GetFontEP15CPDF_Dictionaryi+268)
    #23 pc 000dbcc8  /system/lib/libpdfium.so (_ZN13CPDF_Document8LoadFontEP15CPDF_Dictionary+56)
    #24 pc 000e85ed  /system/lib/libpdfium.so (_ZN24CPDF_StreamContentParser8FindFontERK14CFX_ByteString+141)
    #25 pc 000e86f1  /system/lib/libpdfium.so (_ZN24CPDF_StreamContentParser14Handle_SetFontEv+209)
    #26 pc 000e6bf0  /system/lib/libpdfium.so (_ZN24CPDF_StreamContentParser10OnOperatorEPKc+192)
    #27 pc 000ee757  /system/lib/libpdfium.so (_ZN24CPDF_StreamContentParser5ParseEPKhjj+375)
    #28 pc 000f04f7  /system/lib/libpdfium.so (_ZN18CPDF_ContentParser8ContinueEP9IFX_Pause+1207)
    #29 pc 000d384c  /system/lib/libpdfium.so (_ZN16CPDF_PageObjects13ContinueParseEP9IFX_Pause+44)
    #30 pc 000d3e8c  /system/lib/libpdfium.so (_ZN9CPDF_Page12ParseContentEP17CPDF_ParseOptionsi+60)
    #31 pc 00082d56  /system/lib/libpdfium.so (FPDF_LoadPage+134)
    #32 pc 0010045a  /system/lib/libandroid_runtime.so
    #33 pc 00afe806  /system/framework/x86/boot.oat

**Comment by zhanghai** [comment]
It's a bug in the system's PDF rendering library which I can't fix - please disable PDF thumbnail in settings.
