### ISSUE TITLE
Inactive switch on status bar

### ISSUE THREAD

**Issue by Valdnet** [zhanghai/MaterialFiles#620]
After adding the FTP Server switch to the status bar, after a while it becomes inactive (more light gray) and it is impossible to enable FTP Server.

Screenshot:

![obraz](https://user-images.githubusercontent.com/47037905/140406808-ca6385e4-2f2d-459b-bb3f-4308f4826199.png)

Only after starting the Material Files application, the switch becomes active and works fine. This is a problem with the application running in the background.

After setting the app as an exception for battery saver, the switch works fine.

Apps:
Android 10
Material Files 1.3.1

**Comment by zhanghai** [comment]
What is the device and system version you are using? This kind of things happens most often on OEM systems that are more aggressively killing apps, and it's usually hard for us (as an app) to do anything about it. If this isn't reproducible on a normal Android system (e.g. on Pixel devices), I don't think we should request turning off battery optimization.

**Comment by Valdnet** [comment]
> What is the device and system version you are using?

Android 10 HUAWEI device with EMUI.

**Comment by zhanghai** [comment]
Well, Huawei is notorious on killing apps, see also https://dontkillmyapp.com/ . There's not much I can do and your solution of turning off battery optimization seems correct.

**Comment by Valdnet** [comment]
I thought so too 😉. Unfortunately, this is how it is with these devices.

>  your solution of turning off battery optimization seems correct.

As always, disabling battery optimization helps in many cases 😉.

BTW:
@zhanghai I suggest you consider implementing this feature from issue #213. In my opinion, it would make the app more attractive. Many users would appreciate it.
