### ISSUE TITLE
SD card apk files do not display thumbnails

### ISSUE THREAD

**Issue by TarsChiu** [zhanghai/MaterialFiles#622]
As follow

sd：
![SDcard](https://user-images.githubusercontent.com/53161491/141648260-a717eaba-d9ae-4c84-be42-78e05e4dbcba.jpg)

internal：
![InternalStorage](https://user-images.githubusercontent.com/53161491/141648302-433b8cfa-3aac-4b59-bf8d-68ff38a4d1fd.jpg)

I hope it will be solve.
This will make it more beautiful.😊😃

**Comment by zhanghai** [comment]
This is a technical limitation of Android, there's not much this app can do.
