### ISSUE TITLE
Data loss in the activities AddStorageDialogActivity and FileListActivity

### ISSUE THREAD

**Issue by davirec** [zhanghai/MaterialFiles#623]
When I perform these sequences of events, the dialog on the screen disappears:
1. Go to the Main activity
2. In the top left, click on the hamburger menu button 
3. Tap in “add storage” to show the dialog on the screen
4. Force the pause from the activity and then return to the activity (double rotation).  Note the dialog disappears. note: the pause from activity can be performed in several ways, we suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

The expected behavior is the return to the previous state with the dialog box.
This bug also occurs in other parts of the app as we can see in the video.

https://user-images.githubusercontent.com/3637419/141888843-270546f5-bb7f-47d3-b721-ff09f2af2e4b.mp4

Device:
 - Device: Moto G30 with OS: Android 11
 - Device: MI5X with OS: Android 7.1.2
 - Version: 1.3.1(25)

**Comment by zhanghai** [comment]
Popup menu not being preserved is working as intended - Android just (typically) doesn't support that. I'll fix the dialog bug.
