### ISSUE TITLE
[Feature request] Standalone text editor

### ISSUE THREAD

**Issue by julianfairfax** [zhanghai/MaterialFiles#625]
I've used your app exclusively to edit text files. Why? Because I store my notes in text files and have them locally synced across my devices. I've found that your app is the most modern-looking and simplest way to edit these notes. It would be nice if this functionality could be available as a standalone app though, maybe something like Material Text Editor? I do love the file manager features, don't get me wrong, but I'm perfectly okay using the system file manager app for that. I'd love it even more if there were more features added and you released a Material Notes app, but I'm really just looking for a nice standalone app to edit text files. Is this something you'd be willing to look into doing?

**Comment by zhanghai** [comment]
Glad that you liked my text editor (and also a bit surprised as more people weren't happy enough with it and asked for more features). I've also thought of making a more powerful and proper text editor app for Android, e.g. supporting huge files and syntax highlighting etc, but I don't have the time and my day job is getting busier. So I would recommend you to find some other professional text editor apps, e.g. maybe [Pure Writer](https://play.google.com/store/apps/details?id=com.drakeet.purewriter) if you want to take notes.

**Comment by julianfairfax** [comment]
I did try that app, but like 99% of the FOSS notes apps for Android, it's stored in a database, not txt files. The only other real option is Markor, which looks 10 years older compared to your solution. Not necessarily a bad thing I suppose, but I'd rather just use the built-in functionality in your app, which works fine for me. Thanks again for making it!
