### ISSUE TITLE
Opening zip in external storage (SD card) redirects to another app

### ISSUE THREAD

**Issue by takase1121** [zhanghai/MaterialFiles#627]
When I try to open a zip file in internal storage, it opens correctly:
![Screenshot_20211122-183849_Material_Files](https://user-images.githubusercontent.com/20792268/142847130-a3d8cdeb-0efe-44c9-b57b-7e5b318c4d77.png)

When the file is in external storage (SD card):
![Screenshot_20211122-183901_Termux](https://user-images.githubusercontent.com/20792268/142847175-980318e7-52d8-4bb1-9423-a4da79b5ef7d.png)

**Comment by zhanghai** [comment]
Correct, the archive reading library used by this app requires a real file, however files on external SD card are only provided as a virtual SAF URI by the system, so this app can't open it.
