### ISSUE TITLE
Permission in File Properties

### ISSUE THREAD

**Issue by FarzadMansouri** [zhanghai/MaterialFiles#631]
when open file properties and swipe to permission, it has not any action

**Comment by zhanghai** [comment]
Please provide more details, e.g. where the file is, and a screenshot.

**Comment by FarzadMansouri** [comment]
after change mode it dosen't any change
![Screenshot_20211208-152653_Material_Files](https://user-images.githubusercontent.com/43640090/145205054-8af90901-5f89-45d1-b30b-aed61ab463f2.png)
![Screenshot_20211208-152704_Material_Files](https://user-images.githubusercontent.com/43640090/145205059-64decac9-50cb-4680-bd29-86fa43bb3d29.png)
![Screenshot_20211208-152718_Material_Files](https://user-images.githubusercontent.com/43640090/145205065-a505528e-b570-4c43-a305-92b7c7ac4660.png)

**Comment by zhanghai** [comment]
Ah, this is just how Android behaves - the app issues the syscalls to change the modes correctly, but for internal SD card the system (or the sdcardfs to be precise) ignores it, i.e. the system misbehaves. If you try to do this for files under `/data/local/tmp/` (requires root) it would work properly.
