### ISSUE TITLE
Sftp issue

### ISSUE THREAD

**Issue by Shidapu** [zhanghai/MaterialFiles#637]
Running a Filezilla server with TLS 1.3, and i get following error in console:

[Printscreen](https://gcloud.gmz.cx/s/AFpLmDc58dctxG2)

**Comment by zhanghai** [comment]
Could you provide more detail on how you are configuring your SFTP server, and how you are connecting to it?

**Comment by Shidapu** [comment]
> Could you provide more detail on how you are configuring your SFTP server, and how you are connecting to it?

It's configured with TLS 1.3, with certificates from cloudflare. The subdomain is not protected by cloudflare.

In Filezilla server, it's running in passive mode with ports 56000-57000, port 21 and 990 open, in a windows environment.

I'm connecting to it by Filezilla ftp client, and the admin GUI is available locally only. 

Please let me know if you need anything else.

**Comment by zhanghai** [comment]
Ah yes, was about to same the same thing as your edit. FTP(S) is a poor protocol for the purpose of implementing a file manager, but anyway this feature request is tracked in #213.
