### ISSUE TITLE
Display Nextcloud items like DocumentsUI

### ISSUE THREAD

**Issue by Extarys** [zhanghai/MaterialFiles#640]
I have no idea how to formulate this. In DocumentsUI, after installing and logging in on Nextcloud, I see a Nextcloud item on the left.

![image](https://user-images.githubusercontent.com/11581433/146685946-13ecf794-843a-4681-acfb-e5a55ea7b724.png)

Was it added by an event, or does nextcloud wrote a config file somewhere for DocumentsUI? It would be nice if MaterialFiles app could also display this.

I don't want a deep nextcloud integration, but simply having the Nextcloud item on the left for quick browsing is very practical.

**Comment by zhanghai** [comment]
NextCloud implemented a `DocumentsProvider` for this to appear in DocumentsUI. Material Files isn't the system DocumentsUI app so it can't automatically discover this `DocumentsProvider` provided by NextCloud. However, you can still try and see if using "Add storage" -> "External storage" allows you to select this NextCloud folder and add it to Material Files. (If not, then something has be done in NextCloud to enable selecting it in normal apps including Material Files)

**Comment by Extarys** [comment]
Oh that's sad :P
thanks for the reply, I appreciate it. I'll try your suggestion.

Happy coding and thanks for this nice app!
