### ISSUE TITLE
SMB Connexion Not Working

### ISSUE THREAD

**Issue by faxotherapy** [zhanghai/MaterialFiles#641]
Hi, I have activated SMB share on my Mac. The OS gives me the following: smb://192.168.178.20

I guess Material Files would be happy if I only provide: 192.168.178.20, account name and password, but unfortunately…

So, back on Material File app.
- Hostname: should I input `192.168.178.20` or `smb://192.168.178.20`? I guess I should only put `192.168.178.20` because Material Files is clever enough we're talking about SMB connexion here.
- Port: I guess it's default. So I do not touch.
- Path: I put nothing. MacOS gives me only `smb://192.168.178.20` – However, I tried to put the following `~` sign to access home folder as well.
- Name: I guess I shall leave it as defaults
- Username: I put username of my regular account on my Mac
- Password: I put password of my regular account on my Mac

Outcome: not working.

Also, automatic detection not working even thought SMB share activated on MacOS. Material Files in not able to probe for SMB share on a local network.

**Comment by zhanghai** [comment]
- Hostname - put only the IP address, as the protocol name isn't part of the hostname.
- Port - I don't know Mac but I would try the default first as well.
- Path - put nothing or a real path, depending on your Mac's configuration. If I were you I would try putting nothing first. I suppose `~` which is an alias only supported in certain parts of the system won't work for SMB.
- Username & password: I'm not sure how Mac SMB works.

I think I've never used a Mac for more than 1 hour, so unfortunately I can't help with you on what the configuration is expected to be for a Mac SMB share :/
