### ISSUE TITLE
SFTP Not Working When Using Key Authentication

### ISSUE THREAD

**Issue by faxotherapy** [zhanghai/MaterialFiles#642]
Hi,

I input server IP + port number + username, then select private key. Corresponding public key is on server. Unfortunately, it does not work as I've got the following message: 

![SystemError](https://user-images.githubusercontent.com/6538008/147368610-5390dd7a-c9e1-4241-b620-7f1bf85b9fba.png)

Entering these details from my computer work. 

Thanks for your help.

**Comment by zhanghai** [comment]
Seems that the SSHJ library [recently added support for `chacha20-poly1305@openssh.com`](https://github.com/hierynomus/sshj#release-history) so I'll just update the SSHJ version in this app.
