### ISSUE TITLE
Cannot Access Location

### ISSUE THREAD

**Issue by Jaybhingare** [zhanghai/MaterialFiles#643]
![Screenshot_20211225-020824](https://user-images.githubusercontent.com/96635278/147371919-d5b1ad48-3547-4090-af95-dd03b7f15083.png)
This location 
Internal>Android>Data cannot be accessed...
It says

me.zhanghai.android.files.provider.remote.RemoteFile SystemException: Cannot launch su shell, exit code -3

**Comment by zhanghai** [comment]
See #611.
