### ISSUE TITLE
Direct SD Card write access on android 11

### ISSUE THREAD

**Issue by SebiderSushi** [zhanghai/MaterialFiles#646]
On my OnePlus X and on my Xiaomi Redmi 4X, both running unofficial LineageOS 18.1 builds (each by a separate maintainer) i can get legacy write access to the sd card without root access.

One app that can do it is the closed-source file manager `nextapp.fx` for example, but i can also do it in MaterialFiles with some initial setup. (i tested FX version `8.0.3.0`, version code 8008 which does not hold the `MANAGE_EXTERNAL_STORAGE` permission, has the `requestLegacyExternalStorage` manifest attribute set to `true` and targets SDK version 29)

As it appears the only issue with the current version `1.3.1` of MaterialFiles on LineageOS 18.1 seems to be that the directory `/storage` can't be read which makes it impossible to browse the sd card path. However, if i work around this issue using root access and create a bookmark for the full sd card path legacy write access still works even if root access is disabled. Sadly, MaterialFiles only offers to create bookmarks of directories it can access and pasting directory paths is impossible in MaterialFiles so even if i know the full path to the sd card i can't create that bookmark without root access.

The full sd card path can be inferred from the output of [`Context.getExternalFilesDirs(null)`](https://developer.android.com/reference/android/content/Context#getExternalFilesDirs(java.lang.String)). I don't know if there is any better way to do it but both [Vanilla Music](https://github.com/vanilla-music/vanilla/blob/5763ab5d1210f070572ee2b07e0d161ba267307e/app/src/main/java/ch/blinkenlights/android/vanilla/FileUtils.java#L263) and the [Simple Mobile Tools](https://github.com/SimpleMobileTools/Simple-Commons/blob/6204bcd684c64e2dc507b769b6dff9a2b6381a43/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/Context-storage.kt#L92) apps do it this way and artificially populate the directory listing for `/storage` with those values or generate their list of storage devices from it.

It would be very useful if MaterialFiles could offer any way to access the legacy sd card path on android 11 without depending on root access.

**Comment by SebiderSushi** [comment]
This looks like a cleaner way to achieve the same thing, available on API level 24 and above: https://developer.android.com/reference/android/os/storage/StorageManager#getStorageVolumes()

**Comment by zhanghai** [comment]
Add storage -> External storage is the official way to do that. Does it work for you?

**Comment by SebiderSushi** [comment]
Yes that does work, although i would appreciate any method that lets me avoid SAF if possible. If my ROM offers legacy write acces to the SD Card i really want to make use of it and not suffer SAF performance issues, the inability to rename filesystem entries & loss of last modified timestamps.

I can understand if you don't want to maintain a second solution in parallel to SAF SD-Card access.
 Would it be possible to add a feature that lets users enter a custom filepath to navigate to? This would give me the ability to work around the issue in my specific use case since i could simply create a bookmark to the legacy SD Card path if i determine it myself.

**Comment by zhanghai** [comment]
That would be #587.

Though is it specific to LineageOS, or is it actually guaranteed for apps with "All files access" to be able to access external storage volumes directly on Android 11+? If it's the latter case I can add it into this app.

**Comment by SebiderSushi** [comment]
Sadly i do not have any stock android 11 ROM to test with, but it would be news to me if LineageOS changed anything about storage behavior.

**Comment by zhanghai** [comment]
Looks like it's official behavior so we can utilize it in Android 11+:

> ## Operations that MANAGE_EXTERNAL_STORAGE allows
> The MANAGE_EXTERNAL_STORAGE permission grants the following:
>
> - Read and write access to all files within [shared storage](https://developer.android.com/training/data-storage/shared).
>
>     Note: The /sdcard/Android/media⁠ directory is part of shared storage.
>
> - Access to the contents of the [MediaStore.Files](https://developer.android.com/reference/android/provider/MediaStore.Files) table.
>
> - Access to the root directory of both the USB on-the-go (OTG) drive and the SD card.
>
> - Write access to all internal storage directories⁠, except for /Android/data/, /sdcard/Android, and most subdirectories of /sdcard/Android. This write access includes [direct file path](https://developer.android.com/training/data-storage/shared/media#direct-file-paths) access.
>
>     Apps that are granted this permission still cannot access the [app-specific directories](https://developer.android.com/training/data-storage/app-specific) that belong to other apps because these directories appear as subdirectories of Android/data/ on a storage volume.
>
> When an app has the MANAGE_EXTERNAL_STORAGE permission, it can access these additional files and directories using either the [MediaStore](https://developer.android.com/reference/android/provider/MediaStore) API or [direct file paths](https://developer.android.com/training/data-storage/shared/media#direct-file-paths). When you use the [Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files), however, you can only access a file or directory if you could do so without having the MANAGE_EXTERNAL_STORAGE permission.

**Comment by zhanghai** [comment]
SD cards and USB OTG drvies will automatically show up in the app drawer on Android 11+ in the next release.

**Comment by SebiderSushi** [comment]
Awesome, thanks a lot!

**Comment by proninyaroslav** [comment]
@zhanghai 
Did you manage to pass moderation on Google Play? As far as I know, many have had difficulties with `MANAGE_EXTERNAL_STORAGE`

**Comment by zhanghai** [comment]
I haven't tried yet - if it can't pass, I may have to delist from Play.

**Comment by proninyaroslav** [comment]
@zhanghai 
Alternatively, you can make a release flavor without this permission for Play.

**Comment by zhanghai** [comment]
The app won't work without the permission. It used to work without it because the target SDK version requirement wasn't raised back then, but now that it is raised, the app has to get the permission in order to work on Android 11+.

**Comment by SebiderSushi** [comment]
Thanks for the new release, i've had some time now to test things out. The new feature works very well. Thank you very much for listening and implementing it this quick!

**Comment by Ged296123** [comment]
On Android 12 with Samsung FES21, root folder of sd card cannot be added as external storage. The system forces to selec a folder under SD Card to access. Issue same as #652
