### ISSUE TITLE
Adding a SMB Server crashes the app

### ISSUE THREAD

**Issue by rodriigodzilla** [zhanghai/MaterialFiles#648]
Hello,

The app is crashing when adding "SMB" storage on my Android 6.0.1 Marshmallow device.
I'm using a Cat S60 and I downloaded the app via F-Droid.

Steps to reproduce:
1. Open the hamburger menu
2. Select "Add storage..." option
3. Select "SMB Server"

**Comment by OMTDesign** [comment]
Hello, 

I also experienced this problem using the latest 1.3.1 version on my Samsung Note 4 which runs Android 6.0.1
I reverted to version 1.2.1, and the bug goes away.

However this problem with 1.3.1 does not exist on my Samsung Note 9 which runs Android 10.

**Comment by zhanghai** [comment]
Seems like Android 6.0 `TextView` triggered a bug in `ForegroundTextView`:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean me.zhanghai.android.foregroundcompat.ForegroundHelper.verifyDrawable(android.graphics.drawable.Drawable)' on a null object reference
```

I'll need to fix it in the library.
