### ISSUE TITLE
[Feature Request & Issue: ]  new Window option & Open in Terminal

### ISSUE THREAD

**Issue by pixincreate** [zhanghai/MaterialFiles#649]
Why do `New Window` option open a new app instance?   
It'd be useful if you allow users to swipe through across the windows for convenience [just like we see on Solid Explorer], coming from a long time Solid Explorer user, I admired that option a lot!!!  
Open in Terminal means which application? It doesn't support **Termux** at the first place.     
  
And eagerly waiting for v1.4.0 to get Grid View.

**Comment by zhanghai** [comment]
It's not a new app instance, but just a new window, so that you can use the navigation gestures provided by the system to easily swtich between them. If you open multiple documents in Google Doc, it's the same behavior. This app doesn't support multi-panel like Solid.

Termux support is #32 - the only terminal app that currently supports simply passing in an initial working directory is the classic [Terminal Emulator](https://play.google.com/store/apps/details?id=jackpal.androidterm).

**Comment by pixincreate** [comment]
> so that you can use the navigation gestures provided by the system to easily switch between them

Yea, I underwent but still, I more or less feel it like it's inconvenient at the first place. Replace it with multi-panel would really help. I know you'd disagree with my view as you've already 100 of hours designing multiple widow function. Atleast, try to optimise it so that it doesn't feel slow like the page gets empty for about a visible fraction of seconds and then it opens another window which feels slow even if it's not. I hope you're getting what I'm trying to say, I can explain in detail I'd your ask so.:)

**Comment by zhanghai** [comment]
> try to optimise it so that it doesn't feel slow like the page gets empty for about a visible fraction of seconds and then it opens another window which feels slow even if it's not.

The existing window was never empty when I creates a new window, and the new window is only empty (loading) for a very smal amount of time and gets loaded even before the window switching animation completes. Could you explain in detail what you are seeing? (A video showing the problem would be even better.)

**Comment by pixincreate** [comment]
Yea, you were right, it open in an instant.    
I wonder how much RAM would that consume of I open n number of windows.

But, I really prefer it opens within the app like a panel that has certain limit while the new window had infinite amount unless RAM restricts.

**Comment by Argoneon1810** [comment]
well, I can see that it's a long-closed issue, but as a Samsung's DeX user, a multi instance app is super duper better than a swipe-through multi pannel app.
Just saytin...
