### ISSUE TITLE
[Feature Request:] Add Recycle Bin and an option have Nav bar at bottom along with a save to option

### ISSUE THREAD

**Issue by pixincreate** [zhanghai/MaterialFiles#653]
Title says it all.

- A Recycle Bin would be really helpful at every time.  
- And having an option to set nav bar at bottom would make working easier on phones that are longer liner 6.5+ inches.  
- And you don't need **root** access for accessing the **data** and **obb** directory under the **Android** folder. If you've observed Solid Explorer, it asks you specific permission to allow access to those followers separately like **scoped storage Allow Access**. So, that might help normal users who don't have root access on their phone. In such cases they'll depend on Solid Explorer for that reason. If you add this, then we'll be learning the chances of users getting away from using Material Files. 
- A option as **Save to Files** in the Share Sheet Menu would be really handy and it really reduces the burden of saving some files manually externally.

**Comment by zhanghai** [comment]
All these items have separate issues tracking them.
