### ISSUE TITLE
[Bug]cannot extract Archives with password protection. 

### ISSUE THREAD

**Issue by Hk-178** [zhanghai/MaterialFiles#657]
When i tried to extract a zip, it shows an error as quoted down : 

"Error while extracting "TING_SOUND_EFFECT.mp3"

There was an error extracting the file into "TING_SOUND_EFFECT". org.apache.commons.compress. Pa sswordRequired Exception: Cannot read encrypted content from /storage/ emulated/0/1/TING_SOUND_EFFECT.7z without a password."

Please add an option to input password

**Comment by zhanghai** [comment]
There is an existing issue for this.

**Comment by fohfuu** [comment]
I can't find the original issue. Was this resolved?
