### ISSUE TITLE
Multiple users on same SFTP server don't work

### ISSUE THREAD

**Issue by anagramka** [zhanghai/MaterialFiles#660]
I have a user on SFTP server. If i add second user on the same server, logging in with it brings me to first user's folder. If i remove first user, kill app, and wait few minutes for session close, i can login under second user account. Adding first user again leaves me stuck on second user account.
I've reproduced it multiple times, both with password or key authentication.

Material files 1.3.1 F-droid, LOS 18.1

**Comment by zhanghai** [comment]
Yes this is a missing feature. I will need to add username as part of the authority that identifies a SFTP server.
