### ISSUE TITLE
Allow anonymous FTP connections as a client

### ISSUE THREAD

**Issue by yephny** [zhanghai/MaterialFiles#662]
Material Files requires you to have a username, which should instead be left blank if you are connecting to a server that accepts only anonymous connections. Material Files should allow you to leave the credential fields blank.

**Comment by zhanghai** [comment]
Do you mean SFTP client? Material Files currently doesn't have a FTP client.

Regarding no username, could you share more details about that configuration? To my knowledge SFTP must have a username.

**Comment by yephny** [comment]
You are certainly correct, it was my mistake that I thought the SFTP client worked also as an FTP client.

**Comment by yephny** [comment]
As of 1.5.0, this issue is relevant.
