### ISSUE TITLE
[Feature Request:] Add other app's providers

### ISSUE THREAD

**Issue by RichardLuo0** [zhanghai/MaterialFiles#664]
![Screenshot_20220128-170921_文件~2](https://user-images.githubusercontent.com/22096448/151519698-7f6328f1-01a0-442b-bea7-d299cde875dd.png)
Like in android's stock file app, other apps can provide content to the file app.

**Comment by zhanghai** [comment]
This app supports adding external storage. If those apps don't show up in the system file picker when you chose to add external storage, it means those app don't support access from this app.
