### ISSUE TITLE
File list overlaps soft buttons in portrait orientation

### ISSUE THREAD

**Issue by rparkins999** [zhanghai/MaterialFiles#667]
Some newer Android devices (e. g. Samsung Galaxy S21) have a display which covers the whole of the front of the device, and use soft buttons in the display for Recent, Home, and Back instead of the traditional physical buttons. Applications should not normally display anything on top of the soft buttons. In portrait orientation, MaterialFiles' file listing overlaps the soft buttons.

**Comment by zhanghai** [comment]
Do you have a screenshot? software navigation button isn't a new thing.

**Comment by rparkins999** [comment]
On Sunday, 6 February 2022, 07:59:42 GMT, Hai Zhang ***@***.***> wrote:  
 
 


Do you have a screenshot? software navigation button isn't a new thing.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhanghai** [comment]
You didn't send a screenshot with your last comment - it's just empty.

**Comment by rparkins999** [comment]
The screenshot was definitely there: I've just checked my sent mail folder. Maybe github filtered it out.
I've put a copy on my web page athttp://www.zen224037.zen.co.uk/Screenshot_20220206-105408_MaterialFiles.jpg

    On Monday, 7 February 2022, 09:07:59 GMT, Hai Zhang ***@***.***> wrote:  
 
 


You didn't send a screenshot with your last comment - it's just empty.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhanghai** [comment]
The link works now - but this is the standard design nowadays. The navigation bar will have a semi-transparent background with app content beneath it.
