### ISSUE TITLE
自定义访问文件夹

### ISSUE THREAD

**Issue by yutong-yt** [zhanghai/MaterialFiles#685]
为什么不能快速转跳文件夹

**Comment by zhanghai** [comment]
你是指书签文件夹？

**Comment by yutong-yt** [comment]
> 你是指文件夹吗？

就是向mt管理器一样可以直接转跳指定的文件夹

**Comment by zhanghai** [comment]
不用 mt，不太理解…

**Comment by yutong-yt** [comment]
就是这个功能


---原始邮件---
发件人: "Hai ***@***.***&gt;
发送时间: 2022年3月4日(周五) 下午2:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhanghai/MaterialFiles] 自定义访问文件夹 (Issue #685)




 
不用 mt，不太理解…

**Comment by yutong-yt** [comment]
就是这个功能
![Screenshot_20220304_155254_bin mt plus](https://user-images.githubusercontent.com/84581911/156728950-8f87e1d2-fcbe-4d82-b401-3b3bf602bcf6.jpg)

**Comment by zhanghai** [comment]
Duplicate of #587.

**Comment by yutong-yt** [comment]
> 不用mt，理解…

![Screenshot_20220304_155254_bin mt plus](https://user-images.githubusercontent.com/84581911/156729047-47241bba-a3e9-4543-a362-8f28cc822486.jpg)
像mt管理器里面的这个功能一样，不支持转跳，太麻烦了，别人发一个文件地址需要自己找，支持这个功能就可以直接转跳了
