### ISSUE TITLE
i18n: There is no text string in Transifex

### ISSUE THREAD

**Issue by Valdnet** [zhanghai/MaterialFiles#696]
The following text string is missing in Transifex to translate:

https://github.com/zhanghai/MaterialFiles/blob/37332d788957bbbaf83d480da3c64d294e635448/app/src/main/res/values/strings.xml#L649

Translated text string into Polish:

`<item>Automatyczny</item> `

https://github.com/zhanghai/MaterialFiles/blob/37332d788957bbbaf83d480da3c64d294e635448/app/src/main/res/values-pl/strings.xml#L604

**Comment by zhanghai** [comment]
Ah, it was a last minute string change to fix an issue blocking v1.4.0 release. I've updated the strings.xml on Transifex now.
