### ISSUE TITLE
Remove junrar from F-Droid build

### ISSUE THREAD

**Issue by linsui** [zhanghai/MaterialFiles#699]
Could you please remove junrar from F-Droid build? It's licensed under UnRAR, which is not an open source license. https://fedoraproject.org/wiki/Licensing:Unrar Not sure how file roller do that. Thanks!

**Comment by zhanghai** [comment]
I agree unrar doesn't have a good license despite being open-sourced, but I also want to be pratical here - there are users who do prefer the functionality, and the usage of unrar in this app is definitely not a direct inclusion of unrar source code, but indirect and as an unmodifiable dependency, which is a bit inherently vague in terms of copyright similar to classpath & linking.

So if there is an F-Droid ban on junrar, similar to [the one on cloudrail because it turned proprietary](https://gitlab.com/fdroid/fdroiddata/-/issues/1817) that prevented Amaze from being updated, I'll surely go ahead and remove junrar from F-Droid build.

**Comment by linsui** [comment]
Yes, I'm also a user of that function. :( It's better if there is an alternative. But I guess it's pretty difficult to find an FOSS rar lib. File roller uses unarchiver for rar files. But it has some problems with some rar files and I'm not sure if there is a java wrapper.

Since F-Droid is featured as an FOSS app store, we'll ban junrar. I'm going to add junrar into the scanner list. Before we finally ban junrar we will wait until most affected apps updated, i.e. when a new version of MaterialFiles without junrar in the F-Droid build ready. Thanks!

**Comment by zhanghai** [comment]
Got it - I'll exclude junrar from F-Droid build in the next version.

I did some research and it seems file-roller is using libarchive, which has a clean room implementation of unrar. I don't think anyone will write a Java port or wrapper for it in the near future though.

**Comment by linsui** [comment]
Thanks!

**Comment by zhanghai** [comment]
Tested locally that the app builds fine after the existing magic in F-Droid build metadata removes junrar.

**Comment by linsui** [comment]
Thanks!

**Comment by linsui** [comment]
JFI, [Seeneva](https://seeneva.app/) use libarchive for CBR. But it's wrapped in [seeneva-lib](https://github.com/Seeneva/seeneva-lib) with libarchive-rs.

**Comment by zhanghai** [comment]
Hi @linsui , I'm planning to do a patch release to resolve a relatively frequent app crash in the upcoming days, so I'm wonder if the junrar ban has been implemented on F-Droid? If not, I would like to temporarily revert this change to avoid breaking functionality with patch releases if possible. However if it has been enforced, I'll also be fine.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1091 My MR has been merged so junrar is already banned in F-Droid.

**Comment by zhanghai** [comment]
I see, thanks for the info!

**Comment by Valdnet** [comment]
@linsui After reviewing the above license, I wanted to ask: On what legal basis do you say that you should not block applications using the Unrar code?

**Comment by linsui** [comment]
> On what legal basis do you say that you should not block applications using the Unrar code?

Do you want to say "On what legal basis do you say that you should ~~not~~ block applications using the Unrar code?"

I'm not a lawyer. F-Droid only regards licenses approved by FSF/OSI/Debian as open source licenses.

**Comment by zhanghai** [comment]
Hi @linsui, I'm considering sevenzipjbinding in #141, however I found your comments at junrar saying it's frowned upon as well due to unrar code usage. If this app ever switch to sevenzipjbinding for archive support, will that mean I'll need to remove support for all archives on F-Droid build?

**Comment by linsui** [comment]
The 7-zip can be compiled without the unrar part (`DISABLE_RAR_COMPRESS=true`). I don't know about the binding. If the unrar part can't be disabled, we need to disable the whole 7zip.
