### ISSUE TITLE
English似乎有错字

### ISSUE THREAD

**Issue by AngelofMe** [zhanghai/MaterialFiles#706]
因为这个App的作者好像不是英语母语，所以我反馈这个应该没什么问题吧？
Ellipisize不是椭圆吗？
你想表达的是不是Ellipsis, Ellipsism这类代表省略吧？总之就是感觉很怪异
因为我用的其他同类App没见过这么用词的，只遇到过Marquee，所以我也不敢确定
吐槽一点，解压缩zip速度似乎比ZArchiver慢很多

**Comment by zhanghai** [comment]
1. 即使某个项目的作者母语是英语，有 typo 也是正常的，我觉得都可以反馈。
2. 但是椭圆是 [ellipse](https://www.google.com/search?q=defien+ellipse) 不是 ellipisize。
3. Ellipsize 是 [Android 官方的用语](https://developer.android.com/reference/android/widget/TextView#attr_android:ellipsize)。
