### ISSUE TITLE
Animation tearing issue when accessing drawer

### ISSUE THREAD

**Issue by regaldude** [zhanghai/MaterialFiles#712]
Attaching a screen capture of the issue:

https://user-images.githubusercontent.com/63294824/159110763-ca225356-d41d-42f8-96ed-19b035979db5.mp4

Notice the purple bars that show up when swiping.

I am on Android 12.

**Comment by regaldude** [comment]
This doesn't seem to be an app issue. Something is wrong with the animations on my phone. My bad.

**Comment by drakeet** [comment]
This should be the performance of an OLED screen.
