### ISSUE TITLE
Transifex & Hebrew

### ISSUE THREAD

**Issue by tzagim** [zhanghai/MaterialFiles#718]
Since Google changed the language code for Hebrew from HE to IW on Android, need to check whether Transifex supports exporting files in the appropriate format.

**Comment by zhanghai** [comment]
It's not that Google changed the language code from HE to IW on Android - it's just the old language code for Hebrew was IW so when Android was designing its app resources system it used IW as well. The language code was later changed to HE by ISO but for compatibility reasons it remained IW in Android resources system.

Transifex simply exports the file with a naming containing HE, and I'm manually moving them into the IW resource directory, so there's no file format issue (it's the same as any other language, just a different language code) and I think it should be okay.
