### ISSUE TITLE
Data loss on double screen rotation

### ISSUE THREAD

**Issue by davirec** [zhanghai/MaterialFiles#721]
Hi, this issue has a relation with #623.

We found failures similar in the activity:
FileListActivity: path bar settles on-screen, popup menu disappears, various properties of the view change.

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159774835-b9f4a7d4-72dc-4544-b81c-b892fcc60be6.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159774828-763cd1bf-3ce7-42ab-b1a2-219ffffe6fe7.png" width=20% height=20%>
</figure>

</div> 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159775105-26385f62-c5a3-4704-9aa9-45111a6fb472.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159775054-f9b78171-4dc4-4069-b3e1-c3c9894e9ec9.png" width=20% height=20%>
</figure>

</div> 

ScrollEvent(direction=FULL_DOWN)	
IntentEvent(intent='am start me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity')	
ScrollEvent(direction=FULL_LEFT)	
LongTouchEvent(duration=2000)	[[176,152],[338,236]]
ScrollEvent(direction=FULL_LEFT)	
FillUIEvent	
**Cap01:** capture screen properties before rotation
DoubleRotationEvent
**Cap02:** capture screen properties after rotation
Cap01 != Cap02 (lost several properties)

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

**Comment by zhanghai** [comment]
Losing popup menu is expected behavior as clarified in #623.

The change of scroll position is an unfortunate side effect due to how scroll position is saved and restored. So if the rotation has changed the available size of the scrollable container, having inconsistent scroll position after rotating back is also expected.
