### ISSUE TITLE
SFTP symbolic link not reported

### ISSUE THREAD

**Issue by anedroid** [zhanghai/MaterialFiles#722]
If I use Termux as a SSH client, and type e.g. `mv somebigfile.mkv ~/Videos`, moving file take place immediately, but in Material Files it's very slow. I think it's because Material Files always download files from remote locations before copying or moving file. Instead it should check whether source and destination are on the same server and if so, execute the operation on the remote machine.

Btw, since Material Files can display symlinks on root filesystem, why don't implement this feature for SSH?

**Comment by zhanghai** [comment]
SFTP isn't the same thing as SSH so it doesn't work like issuing a simple `mv` command. The code does try renaming the file first when moving the file (see [here](https://github.com/zhanghai/MaterialFiles/blob/4f37397b42ef9b94d3bac248993a2c78ec0aacd4/app/src/main/java/me/zhanghai/android/files/provider/sftp/client/Client.kt#L122)), but SFTP doesn't support server side copy so copies have to go through downloading and then uploading.

SFTP does support symbolic links, and I also wrote support for it. Maybe your server didn't report them as symbolic link?

**Comment by anedroid** [comment]
I know it does report it, because Nautilus displays little arrow in symlinks when I connect to this server over SFTP.

**Comment by anedroid** [comment]
If SFTP doesn't support server-side copying, maybe Material Files could open temporary second SSH session, execute `cp` command and close session?

**Comment by zhanghai** [comment]
Symbolic link: OK sounds like a bug, I can investigate it.

Server-side copy: No, it's not always possible to have an SSH connection when there's SFTP.

**Comment by zhanghai** [comment]
Verified that the server side move works fine and symbolic link has been fixed in 7f7bb53.
