### ISSUE TITLE
Error: No such file or directory

### ISSUE THREAD

**Issue by eshagh79** [zhanghai/MaterialFiles#723]
Hi, when we delete one of the standard folders or the marked folders and then try to enter the folder we deleted before through the menu; An error occurs.
Reproduction steps:
1. Open the program and go to the internal memory
2. Delete the movie folder from the internal memory
3. Open the program menu and select the Movies folder from the standard folders.
4. We see the error.

![Screenshot_2022-03-25-09-25-05](https://user-images.githubusercontent.com/52137191/160061471-9c0a2d97-152e-4c4d-be5d-fd58efc5ee36.png)
![Screenshot_2022-03-25-09-24-54](https://user-images.githubusercontent.com/52137191/160061486-d8329c4b-5359-44a6-bebf-c1be56d4940c.png)

**Comment by zhanghai** [comment]
That sounds like expected behavior - are you expecting anything else?

**Comment by eshagh79** [comment]
Instead of this long error, which is only useful for developers and in prototypes, there is only one page that says this folder does not exist.

**Comment by eshagh79** [comment]
Displaying this error causes the user to assume that the application has a problem and may damage the data.

**Comment by zhanghai** [comment]
Isn't "No such file or directory" saying that the fodler doesn't exist?

For generally localizing errors - it is hard because there are so many possible errors. We can still priortize and only localize some of them, but that's still on the TODO list.

**Comment by eshagh79** [comment]
In my opinion, this error occurs more often than other cases and it is better to prioritize it over other errors.
I think other people like me will report this in the future.

**Comment by zhanghai** [comment]
See also #150.
