### ISSUE TITLE
FTP server crashes before API 24.

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#731]

**Comment by adzwanjulkanain-netizen** [comment]
Check out this cool app on Play Store!

https://play.google.com/store/apps/details?id=com.zenhub.gfx

**Comment by adzwanjulkanain-netizen** [comment]
Check out this cool app on Play Store!

https://play.google.com/store/apps/details?id=com.zenhub.gfx

**Comment by sidatesidibe2021-code** [comment]
99999

**Comment by sidatesidibe2021-code** [comment]
999999
