### ISSUE TITLE
Use libarchive

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#735]
It's better designed, backs file-roller, and supports RAR & RAR5 without the non-free RAR license.

https://github.com/libarchive/libarchive

https://github.com/libarchive/libarchive/issues/942

https://github.com/libarchive/libarchive/blob/master/contrib/android/Android.mk

https://github.com/libarchive/libarchive/blob/master/CMakeLists.txt

https://github.com/libarchive/libarchive/blob/master/libarchive/CMakeLists.txt

https://github.com/green-green-avk/build-libarchive-minitar-android

https://developer.android.com/ndk/guides/other_build_systems

**Comment by Stu75e** [comment]
Thank you veryyyy much
