### ISSUE TITLE
写文件bug

### ISSUE THREAD

**Issue by woshigenm** [zhanghai/MaterialFiles#739]
有时删除文字，再保存文件管理器会将删除的文字重新写入文件，望修改

**Comment by zhanghai** [comment]
无法重现。请问具体怎样重现这个问题？

**Comment by woshigenm** [comment]
> 无法重现。请问具体怎样重现这个问题？
![Uploading Screenshot_20220402_195857_me.zhanghai.android.files.jpg…]()
如图

**Comment by woshigenm** [comment]
> 无法重现。请问具体怎样重现这个问题？
如果调用其他的文本编辑器，再返回，质感文件会将在其他的文本编辑器所编辑的内容，重新写入文件
如图
![Uploading Screenshot_20220402_195857_me.zhanghai.android.files.jpg…]()

**Comment by woshigenm** [comment]
![Uploading Screenshot_20220402_195857_me.zhanghai.android.files.jpg…]()

**Comment by zhanghai** [comment]
你的图片没有上传成功。一般来说调用其他的文本编辑器的话，质感文件不会在它写入文件后又重新写入的，代码里没有这个逻辑。

**Comment by woshigenm** [comment]
前
![Screenshot_20220403_220504_me zhanghai android files](https://user-images.githubusercontent.com/99122353/161431974-22c78037-734d-41a9-8429-17e4ae2f0a4d.jpg)
后
![Uploading Screenshot_20220403_220514_me.zhanghai.android.files.jpg…]()

**Comment by woshigenm** [comment]
后![Uploading Screenshot_20220403_220514_me.zhanghai.android.files.jpg…]()

**Comment by woshigenm** [comment]
![Uploading Screenshot_20220403_220514_me.zhanghai.android.files.jpg…]()
后

**Comment by woshigenm** [comment]
![Uploading Screenshot_20220403_220514_me.zhanghai.android.files.jpg…]()

**Comment by woshigenm** [comment]
[https://xiaoniuma.coding.net/p/niubi/d/image/git/raw/master/2022-04-03.jpg](url)

**Comment by woshigenm** [comment]
![Uploading Screenshot_20220403_220514_me.zhanghai.android.files.jpg…]()

**Comment by woshigenm** [comment]
![Uploading https://xiaoniuma.coding.net/p/niubi/d/image/git/raw/master/2022-04-03.jpg]()

**Comment by woshigenm** [comment]
![Screenshot_20220403_220514_me zhanghai android files](https://user-images.githubusercontent.com/99122353/161432540-d08d35a9-ff73-4684-8603-ff556d46be1c.jpg)

**Comment by woshigenm** [comment]
@zhanghai 如图

**Comment by woshigenm** [comment]
质感文件在我调用其他文件管理器保存后，给文件重新写入了删除的内容

**Comment by woshigenm** [comment]
![Screenshot_20220403_225734_me zhanghai android files](https://user-images.githubusercontent.com/99122353/161434095-edfda3f3-476e-40f0-a434-4e62ffb8e9e6.jpg)

**Comment by zhanghai** [comment]
为什么你认为是质感文件写入的，而不是其他 app 的保存有问题？
