### ISSUE TITLE
Extract archive files and view archived files

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#74]
Beware `..` security issue, and child of symbolic link.

**Comment by naloder** [comment]
最好能支持全部格式的压缩包解压(以及压缩包编码切换，因为有时候外区压缩的压缩包需要切换编码才能解压)

**Comment by zhanghai** [comment]
@naloder 在设置中已经支持压缩包默认文件名编码切换；目前支持所有 [Apache Commons Compress](https://commons.apache.org/proper/commons-compress/) 支持的文件格式。

**Comment by zhanghai** [comment]
Need to change `boolean forCopy` to `enum` with `COPY`, `EXTRACT` and `MOVE`.

**Comment by zhanghai** [comment]
Done.
