### ISSUE TITLE
Cant update latest version in fdroid

### ISSUE THREAD

**Issue by itsme24082004** [zhanghai/MaterialFiles#741]
@zhanghai bro i tried updating this app in fdroid but it is throwing some error 
![IMG_20220402_114810](https://user-images.githubusercontent.com/91739986/161369787-d650a5cc-a860-4d75-a4e0-99f5d520eef3.jpg)

How to solve this problem

**Comment by zhanghai** [comment]
The APK link in the screenshot (https://f-droid.org/repo/me.zhanghai.android.files_28.apk) works fine for me. Maybe you need a retry or have a network problem.

**Comment by linsui** [comment]
This problem sometimes happens when the mirror server is not up-to-date.

**Comment by itsme24082004** [comment]
@zhanghai thankyou for helping me sorry for my late response
