### ISSUE TITLE
Cant change last modified sorting order 

### ISSUE THREAD

**Issue by Raif1** [zhanghai/MaterialFiles#742]

**Comment by zhanghai** [comment]
Not sure what you meant - you can uncheck the "Ascending" option.

**Comment by Raif1** [comment]
> Not sure what you meant - you can uncheck the "Ascending" option.

Checked last modified. Cant uncheck

**Comment by zhanghai** [comment]
I'm not saying you should uncheck "Last modified" - I was saying you should uncheck "Ascending"

**Comment by Raif1** [comment]
I was trying to say i cant uncheck last modified option after checking

**Comment by zhanghai** [comment]
Yes you have to choose one way of sorting - you can uncheck "Last modiifed" by selecting one of the other three sorting keys.

**Comment by Raif1** [comment]
Uh ok i was wrong with the size type and last modified one of them must be ticked i will be closing the issue then
