### ISSUE TITLE
The three dot action item in app bar is behind navigation bar in landscape

### ISSUE THREAD

**Issue by GithubContributor832** [zhanghai/MaterialFiles#751]
Please allow to gather URI path for internal storage like external storage along with making the default path to the file not the URI path for both internal and external storage when copying. This is much more convenient when needing a files path as on external storage the default path is the URI. Thanks for all your work and hope I'm not a bother. Not a big deal though.

**Comment by zhanghai** [comment]
What do you mean by URI path and what do you mean by gathering them?

**Comment by GithubContributor832** [comment]
When I copy the path to the file for my own needs on external storage it copies the URI not the normal path to the folder. When I need the URI to the whole internal storage its not there like external storage when editing storage from long press. There's times a may need the uniform resource identifier.

**Comment by zhanghai** [comment]
> When I copy the path to the file for my own needs on external storage it copies the URI not the normal path to the folder.

That's expected because the app doesn't have access to the actual path for external storage on Android 10.

> When I need the URI to the whole internal storage its not there like external storage when editing storage from long press

What is the URI to the whole internal storage? The app by default uses raw file access for internal storage so there's no URI.

> There's times a may need the uniform resource identifier.

When would it be useful? The URIs are only meaningful within this app, and this app currently doesn't have any place for you to input a URI.

**Comment by GithubContributor832** [comment]
I would also like to mention the hamburger menu is greyed out in horizontal view for some reason. This is not the case obviously in normal vertical view.

**Comment by zhanghai** [comment]
> I can get actual path of external storage but not for individual files. I have to copy external storage path then manually add the rest of the actual path.

That's the correct behavior. The content URI is an opaque string and it just happens that the URI path is also the file system path.

**Comment by zhanghai** [comment]
Note that "Go to" a certain folder has been implemented in 1.5.0.

**Comment by GithubContributor832** [comment]
OK thanks. Did you happen to fox the greyed out hamburger menu in horizontal view?

**Comment by zhanghai** [comment]
I'm not sure what you meant by that. Could you post a screenshot?

**Comment by GithubContributor832** [comment]
![Screenshot_20220426-010342_Material_Files](https://user-images.githubusercontent.com/92182796/165226614-182c93c6-26f6-448a-a272-67db9db1d30f.png)

**Comment by zhanghai** [comment]
I vaguely remember it wasn't like this a long time ago. Do you happen to know in which app version this started to happen?

**Comment by GithubContributor832** [comment]
Sorry I do not. I don't go to horizontal view often and noticed it in the current latest release.

**Comment by zhanghai** [comment]
I've fixed the three dots, but there' still the funny bug of the drawer being obscured by navigation bar if you turn your phone 180 degrees.

**Comment by GithubContributor832** [comment]
OK thanks.

**Comment by zhanghai** [comment]
Fixed now.

![image](https://user-images.githubusercontent.com/4469895/165419336-c0302abb-bb5b-4db0-9d94-37a985ba3e21.png)
