### ISSUE TITLE
SMB Encryption

### ISSUE THREAD

**Issue by sepspring** [zhanghai/MaterialFiles#760]
Hi,

Thank you for a great Android File Manager.

Does Material FIles support SMB 3's end-to-end encryption ?
https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-security

Thanks for your help,
Sep

**Comment by zhanghai** [comment]
I don't know, I'm not an SMB user and the SMB functionality is implemented on top of [hierynomus/smbj](https://github.com/hierynomus/smbj). I would suggest you to try it yourself instead of asking.

**Comment by sepspring** [comment]
Thanks for the quick reply.
I do not have a SMB server yet, try to see whether it is worth investing in one.
Anyway I have posted the same question to smbj now.
Thanks again.
