### ISSUE TITLE
没有显示U盘的文件目录

### ISSUE THREAD

**Issue by zhangjingex** [zhanghai/MaterialFiles#761]
如题

**Comment by zhanghai** [comment]
系统版本、应用版本和复现步骤是？

**Comment by zhangjingex** [comment]
https://user-images.githubusercontent.com/45728042/163782671-e721d077-04a7-4f08-926c-c166ab0ca46c.mp4

在质感文件里我没找到如何访问U盘中的文件，但在ES中是可以访问的
Android5.1  质感文件1.4.2

**Comment by zhanghai** [comment]
5.1 上需要添加存储->外部存储然后授权。Android 11 以上能够自动显示。

**Comment by zhangjingex** [comment]
https://user-images.githubusercontent.com/45728042/163787994-6766c10b-62ca-4a57-8fd9-d3e75bd762a3.mp4

并没有找到。我觉得我用的系统应该是有问题的，自带的文件管理也没办法使用，可能是系统没有自动挂载U盘，但是ES是可以的。

**Comment by zhanghai** [comment]
那可能确实不行，可能低版本没有自动挂载 USB 设备，需要手动走 `UsbManager` 来访问吧。但是我没有计划为低版本专门写大段的新代码（其实我已经被多次建议不要支持 5.x 了），所以除非高版本系统的 USB 设备也有这个问题我才能看看怎么解决。
