### ISSUE TITLE
Extracting multiple archives

### ISSUE THREAD

**Issue by takase1121** [zhanghai/MaterialFiles#769]
Currently Material Files allows extracting individual archives by clicking the 3 dots on the right and select Extract. This would be time consuming if there's multiple archives to extract. Is it possible to allow users to select multiple archives and extract them?

**Comment by zhanghai** [comment]
That would only make sense when all the selected file are archive files, while currently all the actions in the selection menu are generic ones. Maybe we can make it an optional menu.

**Comment by takase1121** [comment]
> That would only make sense when all the selected file are archive files, while currently all the actions in the selection menu are generic ones. Maybe we can make it an optional menu.

That makes sense, thanks for considering!
