### ISSUE TITLE
Cannot open file in Archive: root isn't available

### ISSUE THREAD

**Issue by takase1121** [zhanghai/MaterialFiles#779]
I'm unsure why this error happened, but I used to be able to open files in archives directly. 

Version: 1.5.1
https://user-images.githubusercontent.com/20792268/167276806-3f70c901-0bb9-4bd4-a865-0f7b0309302a.mp4

I tried downgrading the app to 1.4.2, and the issue remains. I recalled that it worked on my old rooted Redmi 7A, but I'm not sure if the Root  in the error message refers to that root.

**Comment by zhanghai** [comment]
Oh, I can imagine what's wrong here, and I think the regression is in 1.4.0. Too bad this missed 1.5.1 release by hours :/
