### ISSUE TITLE
Error while deleting files within folder

### ISSUE THREAD

**Issue by thoriqadillah** [zhanghai/MaterialFiles#783]
So I was deleting a folder that has movies inside it with total of 3 GB plus, but I was having some issue where I can't pull my notif bar down while deleting the folder. So I thought this must be not responding, because my storage was only 8 GB left when the movies present. Anyway, I restarted my phone, and when I check the movie, it was gone from my media player and material files and basically not found where I put it, but my storage not freed up and still 8 GB left. Any solution where the (un)deleted files could be? Thanks in advance

**Comment by zhanghai** [comment]
Honestly I don't know. You described a very strange device state and unfortunately it's nearly impossible for me to help you with the information available.
