### ISSUE TITLE
Is there an API that allows other apps to open a certain path?

### ISSUE THREAD

**Issue by drakeet** [zhanghai/MaterialFiles#785]
My app used to use `FileListActivity` and `org.openintents.extra.ABSOLUTE_PATH` to open a path of MaterialFiles, but now ABSOLUTE_PATH no longer exists, is there a replacement?

<img src="https://user-images.githubusercontent.com/5214214/167611081-7a45b14d-2a3d-44d1-a83c-d6bd47fb37e3.png" width=240 />

My old solution:
```kotlin
val fileIntent = Intent(Intent.ACTION_VIEW)
fileIntent.type = "vnd.android.document/directory"
fileIntent.component = ComponentName("me.zhanghai.android.files", "me.zhanghai.android.files.filelist.FileListActivity")
fileIntent.putExtra("org.openintents.extra.ABSOLUTE_PATH", path)
fileIntent.putExtra(DocumentsContractCompat.EXTRA_INITIAL_URI, rootUri)
fileIntent.putExtra(DocumentsContractCompat.EXTRA_SHOW_ADVANCED, true)
startActivity(fileIntent)
```

Thanks!

**Comment by zhanghai** [comment]
What do you mean by ABSOLUTE_PATH no longer exists? I can't remember removing support for it in this app.

**Comment by drakeet** [comment]
Sorry, about ABSOLUTE_PATH, looks like I remembered something wrong or confused something. 
Anyway, for the ask of this issue, do you know if there is a ready-made API?

**Comment by drakeet** [comment]
It was possible to open Material Files via My old solution, but now it fails.

**Comment by zhanghai** [comment]
The following command can launch Material Files with the designated path successfully:

```
adb shell am start -n 'me.zhanghai.android.files/me.zhanghai.android.files.filelist.FileListActivity' -a android.intent.action.VIEW -t 'vnd.android.document/directory' -e 'org.openintents.extra.ABSOLUTE_PATH' '/storage/emulated/0/Music'
```

The change since 1.4.0 was that if you pass in `EXTRA_INITIAL_URI` Material Files will try to read it (in case it's an archive file) but will fail if it's a directory. A simple fix would be not passing `EXTRA_INITIAL_URI` if you are trying to use Material Files to view a directory.

**Comment by drakeet** [comment]
Got, thank a lot.
