### ISSUE TITLE
Material 3 overscroll effect before Android 12

### ISSUE THREAD

**Issue by godalming123** [zhanghai/MaterialFiles#787]
When you switch to material 3 the new pulldown gesture doesn't appear to be updated

**Comment by zhanghai** [comment]
What is the pull down gesture expected for Material 3?

**Comment by godalming123** [comment]
It animates the top margin of list items when you pull down but I couldn't find a demo of it amywhere

**Comment by zhanghai** [comment]
I don't think I've ever heard of that as part of Material 3 - that actually sounds more like Android 2.x era pull-to-refresh design, which was replace by horizontal progress bar in Holo and then a small floating circular progress in Material.

Do you have any other references (not necessarily a demo) for such a design being part of Material 3?

**Comment by godalming123** [comment]
I couldn't find any mentions in the guidelines but on andriod 12 you can see it

**Comment by zhanghai** [comment]
No, I'm not seeing anything special related to what you said on Android 12 (or 13).

**Comment by OxygenCobalt** [comment]
Are you running Android 12, or no? I know that below Android 12, the overscroll effect will remain the same, albeit there is some progress on porting it with [RecyclerView 1.3.0](https://developer.android.com/jetpack/androidx/releases/recyclerview#recyclerview-1.3.0-alpha01)

**Comment by zhanghai** [comment]
Thanks for the clarification. Yes unfortunately the overscroll effect is currently limited to Android 12+.

**Comment by godalming123** [comment]
Ok that explains my problem I'm on Android 11

**Comment by zhanghai** [comment]
The support for configurable edge effect type is later removed in RecyclerView 1.3.0 in https://android.googlesource.com/platform/frameworks/support/+/05faf6a4a0cc665273d002913c26e930b13f71bc . So this is infeasible in Material Files on older platform versions as well.
