### ISSUE TITLE
Archive with password cannot be handle

### ISSUE THREAD

**Issue by KuwaLee** [zhanghai/MaterialFiles#788]
As the title 

![Screenshot_20220513-020745~2](https://user-images.githubusercontent.com/30096511/168140803-0556bc24-69f5-4729-a89f-262b37994577.png)

**Comment by zhanghai** [comment]
The archive support in this file manager is not meant to fully replace a dedicated archive manager (with fancy archive formats, multi-threading and password support), so you can still open the archive file in one of those apps.
