### ISSUE TITLE
Show ftp url in notification

### ISSUE THREAD

**Issue by KaranKad** [zhanghai/MaterialFiles#792]
I use quick actions to turn on the ftp server without opening the app itself. However I need to open the app any way to view the ftp url. 
It would be really helpful if ftp url was shown in notification itself.
![IMG_20220514_152612.jpg](https://user-images.githubusercontent.com/71691514/168420863-98022163-a486-4128-acbe-7b41f5a5edeb.jpg)

**Comment by zhanghai** [comment]
Do you prefer seeing the URL in notification text (which can't be copied), or just have a `Copy URL` action (alongside `Stop`) which may protect privacy to a agree, or both?

**Comment by KaranKad** [comment]
I prefer seeing url in notification as I usually have to enter the url on my pc.

X-plore file manager displays ftp url in notification when activated.
https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore

![Screenshot_2022-05-15-17-23-03-265_com microsoft emmx](https://user-images.githubusercontent.com/71691514/168471418-d4a853d8-130d-464e-8d3b-c1b6dab046c3.png)

**Comment by Valdnet** [comment]
I also miss this information. When adding an FTP server, I must always view the address in the FTP settings.

**Comment by VishnuSanal** [comment]
Hi! Can I work on this issue? :)

**Comment by zhanghai** [comment]
@VishnuSanal Sorry, I don't have plan to accept code contributions to this project for now. I can work on this before the next version though.

**Comment by leuasseurfarrelds247-arch** [comment]
[]()

**Comment by leuasseurfarrelds247-arch** [comment]
- [ ] -
