### ISSUE TITLE
[Bug] Root is required to preview unextracted archive contents.

### ISSUE THREAD

**Issue by nucspl** [zhanghai/MaterialFiles#795]
~~I don't get why it would need root permissions when trying to access /sdcard/android/data and sdcard/android/obb manually, they're both in internal storage, not root filesystem. Most if not all file managers don't have this issue.~~ And attempting to extract a zip archive also requires root access too apparently. Below are the images.

**EDIT:** Just read the pinned issue, but yeah, viewing archive contents still requires root permissions.
[removed android/data and android/obb images]

![Screenshot_20220518-220810_Material Files](https://user-images.githubusercontent.com/80261260/169061835-f2e9578b-3c99-4851-aac1-3d44d2da3db2.png)
Attempted to open README.pdf without extracting, requires root permissions.

**Comment by zhanghai** [comment]
The issue should have been fixed in 1.5.2. What is you app version?
