### ISSUE TITLE
dynamic android 12 icon

### ISSUE THREAD

**Issue by andsofine** [zhanghai/MaterialFiles#798]

**Comment by zhanghai** [comment]
You mean the start-up screen?

**Comment by andsofine** [comment]
> You mean the start-up screen? This app already have the Android 12 monochrome icon.

I meant this
![olgb84l16zu71_1](https://user-images.githubusercontent.com/99369164/169650662-5596538f-2b47-4dad-8cef-cf920ae509a8.png)

**Comment by zhanghai** [comment]
It's already implemented ([launcher_icon_monochrome.xml](https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/res/drawable/launcher_icon_monochrome.xml)) and it works fine for me.

**Comment by andsofine** [comment]
oh, then the problem is on my side. sorry, thanks
