### ISSUE TITLE
Code editor

### ISSUE THREAD

**Issue by AndroMaster436** [zhanghai/MaterialFiles#805]
Please make a code editor like in mixplorer. Thank you in advance

**Comment by zhanghai** [comment]
I would suggest finding a dedicated code eidtor app for now. Thats Linux & Android philosophy anyway, each tool should do its own thing and do it well.

**Comment by itsmeboy0** [comment]
> I would suggest finding a dedicated code eidtor app for now. That's Linux & Android philosophy anyway, each tool should do its own thing and do it well.

Yep, a file manager should only manage files and nothing else out of scope.

@AndroMaster436 as for what you are looking for, try out [Acode](https://acode.foxdebug.com/).
