### ISSUE TITLE
[BUG] Google+ Is still listed in the about page

### ISSUE THREAD

**Issue by PandoraHayami** [zhanghai/MaterialFiles#808]
When you open the about page in material files, a Google+ Link is still listed there. 

![Screenshot_20220530-161952](https://user-images.githubusercontent.com/79670265/171064783-d8699fa5-5be1-4715-9bd8-f611e93d5745.png)

Now, this isn't that big of a deal, just a little oversight, but is still there, I guess.

**Comment by zhanghai** [comment]
It isn't a bug now, some people including me can still use Google+ (with Currents) because we have GSuite.
