### ISSUE TITLE
[Bug] Document providers

### ISSUE THREAD

**Issue by Vixeliz** [zhanghai/MaterialFiles#810]
Let's say we have two document providers in material files. DocProv1 and DocProv2. If you try copying a file from DocProv1 to DocProv2 let's say in DocProv1 the file's path from root of that DocProv is "games/test" and you try to copy the test file to DocProv2 in the "games/" directory. You will get an error saying can't copy a file over itself. At first I thought it was the way I was implementing the documentprovider for the application im working on but realized it happened with other apps documentproviders too.  I then tested with totalcommander and it worked fine.

**Comment by zhanghai** [comment]
Yes it's a but in the `Path` implementation of this app - I forgot to check for different file systems within the same provider when implementing `Path.startsWith()`. This has been fixed on `master` now.
