### ISSUE TITLE
Can't open files with SFTP using IPv6

### ISSUE THREAD

**Issue by 0e4ef622** [zhanghai/MaterialFiles#811]
I can browse files just fine, but I get an error when I try to open one.
![material_files_ipv6_bug_small](https://user-images.githubusercontent.com/8326135/172085425-eafe6d4d-680c-4256-bfc7-45f68a772ef0.jpg)

**Comment by zhanghai** [comment]
Do you really have a server at `[1234:5678:90ab:cdef::]`?

**Comment by 0e4ef622** [comment]
Haha no, just a fun way to hide my IP instead of covering it. :P

**Comment by ZReC** [comment]
tried with SMB and it doesn't appear to work either

**Comment by 0e4ef622** [comment]
I found a workaround, which is to surround the IPv6 address in square brackets when typing it in. This probably also hints at the underlying issue.

**Comment by zhanghai** [comment]
Due to the parsing of URIs, that may actually be the right thing to do.
