### ISSUE TITLE
Two feature requests - WebDAV Support and App Manager

### ISSUE THREAD

**Issue by FanboyStudios** [zhanghai/MaterialFiles#823]
As a Nextcloud user, it would be nice if we could have WebDAV support so we can access and sync files.

Also Amaze File Manager (another nice FOSS app) has an App Manager that can be used to backup app apks and such. This would allow  users to keep offline backups in case apps get deleted or uninstall from app stores, devices, etc.

**Comment by NePoCz** [comment]
I would really like to see the app manager as well, very useful to be able to backup/share installed apks without a special app. And as mentioned, many explorers support it. 

Regarding the webdav/nextcloud, that is already (partially) supported. You can mount WebDAV with DAVx5 and then it should be available through SAF. For Nextcloud, you have another option to use their app, login and then the "Nextcloud" files will also be available through SAF. Either way, you should be able to add those locations to MaterialFiles using Add storage > External Storage and then browse to these SAF locations.

**Comment by LeOS-GSI** [comment]
There several cloud servers available with webdav access. So I think it would be a good option to have webdav available

**Comment by LeOS-GSI** [comment]
Mhm, OK, i can't see that it is a duplicate and I can't see an implantation :(
