### ISSUE TITLE
Can't open Android/data in work profile 

### ISSUE THREAD

**Issue by HinataKato** [zhanghai/MaterialFiles#826]
Continuing the title, on my device, even after granting Sui/Root access, I still can't open Android/data (looks like it's because my ROM can't access /storage/emulated, maybe add an option to let it access /data/media?)
![Screenshot_20220709-011921_Quickstep](https://user-images.githubusercontent.com/57648531/178040108-59bc77db-1b54-465b-b9f0-f1a1e3097ec1.png)
![Screenshot_20220709-010523](https://user-images.githubusercontent.com/57648531/178038858-8eb0516f-6475-47d4-8821-e0aa3cd1ca37.png)
![Screenshot_20220709-010513_Settings_1](https://user-images.githubusercontent.com/57648531/178038872-0a3d1c72-0434-4128-b785-c28cbbbaf5ec.png)

**Comment by linsui** [comment]
https://github.com/zhanghai/MaterialFiles/issues/487 Looks like the same issue.

**Comment by zhanghai** [comment]
@HinataKato could you test if it works after changing "Root access mode" to "Root access only"?

**Comment by HinataKato** [comment]
> @HinataKato could you test if it works after changing "Root access mode" to "Root access only"?

It doesn't, and can't even access internal storage anymore🫥
![Screenshot_20220714-141547_Quickstep](https://user-images.githubusercontent.com/57648531/178913227-232ed449-9961-47b7-a6a9-d8eb656807ac.png)
![Screenshot_20220714-141606_Quickstep](https://user-images.githubusercontent.com/57648531/178913283-9cc11ac5-72ee-4c52-8f5d-6e2ae577bafe.png)

**Comment by zhanghai** [comment]
I can't reproduce this on latest OxygenOS Android 12 - if I select "Root access only", Material Files will ask for root and then it is able to access internal SD card as well as `Android/data` on it directly. Actually, not being able to access internal SD card itself under root sounds like something is very off here. Maybe something wrong with your root or this ArrowOS?

**Comment by HinataKato** [comment]
> I can't reproduce this on latest OxygenOS Android 12 - if I select "Root access only", Material Files will ask for root and then it is able to access internal SD card as well as `Android/data` on it directly. Actually, not being able to access internal SD card under root sounds like something is very off here. Maybe something wrong with your root or this ArrowOS?

Sorry for the late reply, I should have asked you on Telegram before, it is probably just an Arrow OS issue, but I'm not sure exactly what they did (and I'm not good at ROM development), I think the easiest way is to add an option to select /data/media or /storage/emulated under root privileges :(

**Comment by zhanghai** [comment]
Not sure what they did either. You can just go to those directories manually.
