### ISSUE TITLE
Can not connect to ipv6 sftp server using hostname

### ISSUE THREAD

**Issue by zcx980605** [zhanghai/MaterialFiles#828]
When I try to connect to my ipv6 sftp server using hostname, I always get 'java.net.UnknownHostException: xxx.xxxx.xyz'. However, if I type in my server's ipv6 address instead, the app works fine.

The DNS server I currently using supports ipv6. Besides, the hostname 'xxx.xxxx.xyz' (only associted with an AAAA record) works well in other apps.

**Comment by zhanghai** [comment]
That's strange, this app itself doesn't handle name resolution (except for SMB), so it seems to me the name resolution should just be the system default one...

**Comment by zcx980605** [comment]
Thanks for your reply. Everything is fine after I reboot my phone.
