### ISSUE TITLE
Add shortcut to DocumentsUI

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#845]
And probably for Android/data and Android/obb

**Comment by zhanghai** [comment]
Note that this command works for openning a directory in DocumentsUI: `am start -a 'android.intent.action.VIEW' -t 'vnd.android.document/directory' -d 'content://com.android.externalstorage.documents/document/primary%3AAlarms'`

**Comment by OKaNaRCHY** [comment]
How can I use these commands?
Can we write and save in the Go to tab?

**Comment by zhanghai** [comment]
@OKaNaRCHY No, it is meant for a shell and won't work in Go to...

**Comment by OKaNaRCHY** [comment]
Understood thanks.
