### ISSUE TITLE
Back button only goes back a folder

### ISSUE THREAD

**Issue by breaking-loss** [zhanghai/MaterialFiles#849]
When using the app if I use the back gesture in material file image viewer and text editor  it goes back to internal storage ignoring the folder path I took to reach there . I hope this issue can be fixed.I remember it working well before . Or is this a device specific issue ?

P.S love the app

**Comment by araafroyall** [comment]
No. There is no such bug. Its working fine for me

**Comment by breaking-loss** [comment]
It was a ROM specific bug I think . On havoc os it didn't work but on Corvus is it works just fine .
