### ISSUE TITLE
Failed to open compressed RAR files.

### ISSUE THREAD

**Issue by JahidFariz** [zhanghai/MaterialFiles#855]
Android Version: 12
Device: Samsung galaxy S10 plus

![Screenshot_20220913-191810_Material Files.jpg](https://user-images.githubusercontent.com/50825690/189918442-46773267-875d-43dd-903a-80a867d46ea7.jpg)

**Comment by LeducBastien** [comment]
I got the exact same problem.

I know my RAR file is a RARv5, maybe the library used for RAR management is not up to date?

**Comment by prismacolorgold** [comment]
I am having the same issues too

Android Version: 12
Device: Samsung Galaxy Note 10+
Device: Samsung Galaxy Tab S8+

**Comment by zhanghai** [comment]
RAR 5 is now supported via libarchive (#735). Note that encryption isn't supported by libarchive yet.
