### ISSUE TITLE
大文件夹的大小显示不正确

### ISSUE THREAD

**Issue by Decem6er** [zhanghai/MaterialFiles#864]
大文件夹的大小显示不正确。我已尝试更换多个文件管理器，仅 Material Files 显示错误。另外对于另一个较小的文件夹（372B）能够正确显示。

![MaterialFiles](https://user-images.githubusercontent.com/16839570/193642038-a4244b4d-4283-4524-869b-9c8127f12bdc.jpg)

![AnotherProgram](https://user-images.githubusercontent.com/16839570/193642170-17169b26-491f-452e-a89f-c9eae69b7d27.jpg)

**Comment by zhanghai** [comment]
没有问题，这是 GB 和 GiB 的区别。
