### ISSUE TITLE
希望更好适配墨水屏

### ISSUE THREAD

**Issue by shieep** [zhanghai/MaterialFiles#869]
墨水屏阅读器下一直没有很好用的文件管理器，今天用了咱们这个软件，感觉很不错，建议为墨水屏做下优化。
手机刷新率高，所以文件列表下拉的时候是滑动。墨水屏滑动就会产生刷新问题，建议增加个墨水屏模式，或者墨水屏版。
建议做以下优化：
1，主题颜色：墨水屏只要两种颜色，黑白就可以了，颜色主题比较简单
2，文件下拉翻页模式，就是在文件列表下拉时，也不要采用滑动模式，而是像电子书那样，直接刷新下一页。
3，取消所有动画，点击菜单时的滑出动画等动画全部取消，直接刷新菜单就好。

如果有时间能为墨水屏做下优化，将非常感谢您。

**Comment by zhanghai** [comment]
我个人不是墨水屏用户，所以你可以自己 fork 然后实现。

以及关闭动画的话，在标准的 Android 设备上是可以通过将开发者选项中的动画速度设为 0 倍来实现的，不需要更改应用代码。
