### ISSUE TITLE
[Bug] Unable to grant storage permission on AndroidTV 12

### ISSUE THREAD

**Issue by extropyst** [zhanghai/MaterialFiles#875]
I have installed the app on my Google TV (4K version), which is updated to version 12. 

The interface works smoothly, even better than other apps natively released for AndroidTV, however, it is not possible to use it because the permission of storage cannot be activated, it does not work when the app requests it, nor when it is tried from the AndroidTV system settings.

I would like you to release an AndroidTV optimized version of this app, and if possible an .APKS bundle, or .APKM in APK-Mirror, with PlayStore verification signature.
https://developer.android.com/studio/command-line/bundletool

**Comment by zhanghai** [comment]
This app relies on the "All files access" special app access on Android 12+, which is an Android API. How is TV different in this, is the "All files access" removed on TVs? And how did you know the app works well if you weren't able to grant the access?

**Comment by extropista** [comment]
When opening the application in AndroidTV 12, it throws the message that it requires the storage permission, but when pressing return, it is possible to access the app and enter all the system folders, only that no file appears (they are empty) .

 PS: _The other drawback is that the application icon does not appear in the AndroidTV menu, so I run it from the applications section of the system settings._

**Comment by zhanghai** [comment]
Unfortunately I'm not a TV app developer (and don't own an Android TV), so I don't know how I can keep the app working without the "All files access" support from the system.

**Comment by dhammel** [comment]
I tried it on the same device, android 12 and it appears to not even list any permissions under the App Info's permission list. No option to allow, or deny the all files permission as its not there.

Though when launching the app, system will prompt for the permission and when selecting OK, it will close app with no error.

The app seems to work fine, as expected in chromecast with android 10, and on shield tv running android 11. Must be a conflict with android tv v12.

**Comment by alexanderadam** [comment]
> Unfortunately I'm not a TV app developer (and don't own an Android TV), so I don't know how I can keep the app working without the "All files access" support from the system.

[Google provides documentation] on what is needed for proper Android TV support (i.e. [a handy checklist](https://developer.android.com/training/tv/publishing/checklist)) and apparently it is possible [to work with virtual devices](https://developer.android.com/training/tv/start/start#run-on-a-virtual-device).

In my case, on Android TV OS 12, the message `App needs access to manage all files. Please allow the access in the upcoming system setting.` appears but after clicking `OK` the app just closes and no system settings appears.

If I'm manually going to the permissions screen of the app settings I don't even have the option to give the permission.
No permissions are here listed.

In ["Amaze file manager" app](https://github.com/TeamAmaze/AmazeFileManager?tab=readme-ov-file#amaze-file-manager) there's [the "Files and media" permission](https://developer.android.com/about/versions/11/privacy/storage#permissions) listed.

**Comment by andybotting** [comment]
Just to follow up the previous comment, Amaze does work.

I had issues with its "You need to enable permissions..." dialog, but going into the Android app permissions, it does have a 'Files and Media' permission listed, where as Material Files did not.
