### ISSUE TITLE
Integrate Android/{data,obb} into explorer

### ISSUE THREAD

**Issue by babaric-dev** [zhanghai/MaterialFiles#881]
Currently, we need SAF to access Android/data and Android/obb. It makes hovering around those directories tedious  (say, from Download folder to Android/data).

Possible to integrate those 2 folders so it uses SAF transparently? Makes browsing files 100x faster.

**Comment by gargamel17** [comment]
I second this

**Comment by Chinese-Cyq20100313** [comment]
In Android 13, Android/data is not longer available in SAF.

**Comment by babaric-dev** [comment]
Yes. I created this issue while im still on Android 12. Im using A13 now 😂

**Comment by babaric-dev** [comment]
so this feature will render useless on 13+
