### ISSUE TITLE
Cannot display avif image file

### ISSUE THREAD

**Issue by Coro365** [zhanghai/MaterialFiles#884]
I tried to display avif via smb and got the following error: 
```
java.lang.IllegalStateException: BitmapFactory returned a null bitmap.
Often this means BitmapFactpry could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as valid image format
```
![Screenshot_20221117-200621](https://user-images.githubusercontent.com/6727442/202432416-28df58bd-8bca-4f0c-bc31-3a78b3d9ea0e.png)

Thank you!

**Comment by zhanghai** [comment]
What is your Android version, and does displaying local AVI file work for you?

**Comment by Coro365** [comment]
The version was Edge2-android-12-v20220920.
https://github.com/khadas/android_manifest/tree/khadas-edge2-android12

Local display did not work either, so I don't think it was an issue with this app.
My apologies. And thank you for your kind reply.
