### ISSUE TITLE
增加内置WebDav支持

### ISSUE THREAD

**Issue by s949492225** [zhanghai/MaterialFiles#885]
大部分网盘或者云存储都可以转换为webdav,比如谷歌,百度,阿里.
希望作者可已加入webdav支持.

**Comment by ENuiOWyTv55o** [comment]
+1 希望能够增加webdav的支持，如果能支持挂载rclone就更好了。

**Comment by Hakuin123** [comment]
同求

**Comment by raining1123** [comment]
+1

**Comment by BartemX** [comment]
+1

**Comment by wc7086** [comment]
Duplicate of https://github.com/zhanghai/MaterialFiles/issues/191.

**Comment by raining1123** [comment]
所以作者是不打算原生支持了吗？
