### ISSUE TITLE
Github Version Without Trackers?

### ISSUE THREAD

**Issue by mitchwalton** [zhanghai/MaterialFiles#907]
The fdroid version of the app is fantastic but would it be possible to release the github version without trackers as well? This way I can be at complete peace from Google with the extra features such as RAR extraction. Thanks!

**Comment by zhanghai** [comment]
RAR 5 is now supported via libarchive (#735), and will be available in the next release. Note that encryption isn't supported by libarchive yet.

**Comment by mitchwalton** [comment]
Ok, thank you and incredible work by the way. Your new update after so many months was greatly appreciated. Keep up the great work as the app is so powerful but not bloated like proprietary apps:)
