### ISSUE TITLE
[FR] Optionally keep device unlocked with FTP server running

### ISSUE THREAD

**Issue by Offerel** [zhanghai/MaterialFiles#908]
If start the FTP server and copy a lot of files to the device, this can take some time. In the meantime, the device locks the screen. If this is the case, the transfer of files stops. Can you please keep the screen (optionally) alive, when the FTP server is running? In my case, i copy between 50 and 120GB files to the device. Single files are between 90MB - 200MB in size.

BTW: I use your app no since some time but discovered the FTP server today the first time. I'm impressed how fast the files are transferred to the phone. I really love this. Its a lot faster as MTP. Many, many thx for this.

**Comment by zhanghai** [comment]
I think it might be an OEM-specific battery optimization (for which there should be a Setting). IIUC the server should be able to keep working if the system has AOSP behavior.

**Comment by Offerel** [comment]
You are right. I have disabled battery optimization on my Samsung S20 and i can us it also after the screen goes off. Many thx for the tip. I'm closing the issue. Maybe you can add a hint for the same on the FTP config screen in a future version.
