### ISSUE TITLE
请问哪个版本的AndroidStudio？

### ISSUE THREAD

**Issue by lishangwl** [zhanghai/MaterialFiles#917]
请问哪个版本的AndroidStudio？

**Comment by zhanghai** [comment]
现在是最新版本的了。

**Comment by lishangwl** [comment]
我看mt管理器。授权就行。而且遍历的速度也非常快。您知道是什么方法吗？

**Comment by lishangwl** [comment]
我突然发现添加存储就能进入Android/data。

**Comment by zhanghai** [comment]
喔，你是 Android 11 然后也没 Google Play System Update。Android 12 应该就不行了。

**Comment by lishangwl** [comment]
DocumentFile遍历文件很慢。非常慢。请问您有什么好办法吗？

**Comment by zhanghai** [comment]
请使用 StackOverflow 等论坛询问一般的开发问题。

**Comment by lishangwl** [comment]
好的。，麻烦大佬了
