### ISSUE TITLE
Thumbnails not working in ftp storage 

### ISSUE THREAD

**Issue by alhongb** [zhanghai/MaterialFiles#927]
![Screenshot_20230222-011104](https://user-images.githubusercontent.com/49089579/220413526-4792de32-c980-4247-a754-bf306e5b2d9e.png)

It is Ok in SMB storage

**Comment by zhanghai** [comment]
That's a limitation of the FTP protocol, reading thumbnails would be super slow because FTP connection is sync and can't be multiplexed.
