### ISSUE TITLE
求求作者大大，加入 webdav 协议的支持

### ISSUE THREAD

**Issue by strplay** [zhanghai/MaterialFiles#928]
我放弃了smb，ftps，全面转向webdav。就差安卓有个好用的webdav客户端了

**Comment by strplay** [comment]
support webdav protocol hope plz

**Comment by raining1123** [comment]
+1

**Comment by minico** [comment]
+1

**Comment by murazi** [comment]
同上，质感文件很简洁，如果有Webdav支持，基本上可以替代大部分文件管理了

**Comment by laoxipi** [comment]
+1

**Comment by fbigun** [comment]
> 我放弃了smb，ftps，全面转向webdav。就差安卓有个好用的webdav客户端了

支持

**Comment by comomberchese** [comment]
+1  Most cloud storage and file sharing services work with webdav. This is a popular feature among users.

**Comment by YUNDAN21** [comment]
> 我放弃了smb，ftps，全面转向webdav。就差安卓有个好用的webdav客户端了

支持

**Comment by wc7086** [comment]
Duplicate of https://github.com/zhanghai/MaterialFiles/issues/191.

**Comment by raining1123** [comment]
所以作者是不打算原生支持了吗？

**Comment by zhanghai** [comment]
正在写，下个版本会支持，关闭是因为重复了。

**Comment by raining1123** [comment]
> 正在写，下个版本会支持，关闭是因为重复了。

太棒了！v1.7.0 已支持webdav！感谢大大！ 
https://github.com/zhanghai/MaterialFiles/releases/tag/v1.7.0
