### ISSUE TITLE
Cannot Add "data" and "obb" Folders from "+ Add Storage" tab with Android 13

### ISSUE THREAD

**Issue by OKaNaRCHY** [zhanghai/MaterialFiles#939]
Hello,

Android 13 (MIUI 14) update came to my Xiaomi K40 (Poco F3 Rom installed).
After the update, all settings of Material Files application except FTP were reset. I fixed the settings again. I was able to add and access Android/data and Andriod/obb folders from the "Add Storage" tab before. Now when I want to add those folders in the same way; "Choose another folder to protect your privacy" warning pops up in the built-in file manager.

Do I need to make an extra setting for this or has this access been removed in Android 13?

**Comment by zhanghai** [comment]
The ability to add data and obb was indeed removed in Android 13. You can still use the standard DocumentsUI system app to access them.

**Comment by OKaNaRCHY** [comment]
Thanks a lot for the information.

**Comment by OKaNaRCHY** [comment]
As in Xiaomi's built-in file manager; Is it possible to set it to open in DocumentsUI when the data and obb folders are clicked?

**Comment by zhanghai** [comment]
Yes, that is #845.
