### ISSUE TITLE
Cannot be used as the default file manager

### ISSUE THREAD

**Issue by Ahuababa** [zhanghai/MaterialFiles#94]
![Screenshot_Android_系统_20190526-234202](https://user-images.githubusercontent.com/41805937/58384057-0304f780-8010-11e9-9223-e2cae2c66072.png)
![Screenshot_Quickstep_20190526-234051](https://user-images.githubusercontent.com/41805937/58384062-1021e680-8010-11e9-8fce-e62e405ec1da.png)

**Comment by zhanghai** [comment]
Thanks for the suggestion! See #34.
