### ISSUE TITLE
Can't access shared storage Android/{data,obb}: "Root isn't available" on LOS

### ISSUE THREAD

**Issue by ManDay** [zhanghai/MaterialFiles#967]
If I recall correctly, no such problem existed on Google's AOSP, but on LineageOS I can't access the directories and the files therein. For example, OsmAnd stores data such as Tracks in there, which now remain unaccessible.

LineageOS own "Files" app can access the directories correctly.

**Comment by fukiame** [comment]
seems like a duplication of #611, read it there and maybe close this issue
also, LineageOS's Files app is DocumentsUI so it can read those, yes.
