### ISSUE TITLE
Custom viewing options for specific folder

### ISSUE THREAD

**Issue by demolg** [zhanghai/MaterialFiles#97]
Overall, I like to sort by name.  For some folders, I prefer to sort by time, such as "Download" and "Pictures".

**Comment by zhanghai** [comment]
Is there any existing app that provides this functionality? The feature request sounds kinda ambiguous so having some reference would be great.

**Comment by demolg** [comment]
@zhanghai Solid Explorer
![](https://imgchr.com/i/Ve5VeIcvv)

**Comment by demolg** [comment]
@zhanghai solid explorer
screenshot https://imgchr.com/i/Ve5VeI

**Comment by zhanghai** [comment]
I see. Added to the TODO list.

**Comment by zhanghai** [comment]
Done.
