### ISSUE TITLE
一些功能请求_(:з」∠)_

### ISSUE THREAD

**Issue by naloder** [zhanghai/MaterialFiles#98]
- [ ] 加入文本编辑(查看)器支持，且支持多国家编码选择，对巨大大小的文本进行打开速度优化。
- [ ] 对某目录下的文件实现排序选择(指仅对该目录生效)

其余建议使用中再提 _(:з」∠)_

**Comment by zhanghai** [comment]
感谢，参见 #99 和 #97。

**Comment by naloder** [comment]
似乎1种的多编码切换编辑器还未支持，是稍后需要完善编辑器功能吗。。另外压缩格式库有没有找到合适的解决方案了。。
