### ISSUE TITLE
file extensions in scroll bar pop up

### ISSUE THREAD

**Issue by Appology7** [zhanghai/MaterialFiles#981]
When sorting by type it would be more helpful if scrolling by dragging the bar would show the extension you're at instead of the first character of the file.

Here's a mockup I made:
![mock-up.png](https://github.com/zhanghai/MaterialFiles/assets/54844825/c86f7f17-89e6-413c-afc3-1dca4efef2e7)

**Comment by zhanghai** [comment]
Good idea. Similarly the app should shaw date when sorted by last modified, or size when sorted by file size.
