### ISSUE TITLE
Consider removing mention of Phonograph in README

### ISSUE THREAD

**Issue by lazytownfan** [zhanghai/MaterialFiles#983]
Please consider removing the mention of [Phonograph](https://github.com/kabouzeid/Phonograph) in the README, under the "Why Material Files?" [section](https://github.com/zhanghai/MaterialFiles#why-material-files).

This is because the latest app version tag v1.3.5 was released in September 2020 and the repo was archived on February 4, 2023.

I would've deleted this mention, but this would significantly affect the flow of writing before and after this part in the README.

**Comment by zhanghai** [comment]
I like Phonograph even if it's archived, so I'll just keep it.
