### ISSUE TITLE
This unexpected extra white space 

### ISSUE THREAD

**Issue by abdarker** [zhanghai/MaterialFiles#984]
this is unexpected white space ![Screenshot_2023-08-01-17-13-37-08_29c0a1e3aaa5223e1ffcd3f9ab52a346~2](https://github.com/zhanghai/MaterialFiles/assets/14371506/eb9650ee-266e-4c56-b67f-7a6ff51f4c6c)

if it looks like this it will be a perfect replacement for Google file manager
![Screenshot_2023-08-01-17-15-35-06_29c0a1e3aaa5223e1ffcd3f9ab52a346](https://github.com/zhanghai/MaterialFiles/assets/14371506/aaacb77c-872c-4e44-9d8b-5476ec5b6064)

**Comment by zhanghai** [comment]
It's working as intended so that all texts are aligned to the same vertical line.
