### ISSUE TITLE
Add TV support that can be published on Google Play

### ISSUE THREAD

**Issue by zhanghai** [zhanghai/MaterialFiles#997]
This is a continuation of #987, which is half disabled because Google Play requires TV apps to be published with AAB.

See also 136efa2.

https://developer.android.com/guide/app-bundle/faq#i_want_to_use_the_same_app_signing_key_for_play_and_other_app_stores_is_this_still_possible

**Comment by Pentaphon** [comment]
@zhanghai I have not been able to find Material Files on the Play Store as of a few minutes ago. Any idea on when it will be published?

**Comment by zhanghai** [comment]
The latest release on Play store was cancelled due to having two major bugs (see GitHub releases). Please wait for the next patch release in the next few days

**Comment by duyfken** [comment]
Still not available on Play Store for TV? Tried on a CCwGTV (sabrina) late last week with this result:

![signal-2024-09-20-15-49-04-284](https://github.com/user-attachments/assets/737cfc2c-fda6-42e6-b7ff-35c460ad2768)
